### ISSUE TITLE
@react-navigation/material-top-tabs navigation.navigate not working at RTL

### ISSUE THREAD

**Issue by YogiHa** [react-navigation/react-navigation#10157]
### Current behavior

Hello there and thanks for this great package!

I have an app that supports a few i18n, some of them are RTL.

The same button that functionality navigate perfectly while the app is LTR just doesn't work while the app is RTL.

```
const jumpTo = useCallback(() => {
        navigation.navigate('some screen')
    }, [])
}
<TouchableOpacity onPress={jumpTo } ... 

```
BTW, dragging works normally and as expected in both scenarios, the issue occurs only at IOS

### Expected behavior

RTL will work as LTR (and as on android)

### Reproduction

https://snack.expo.dev/TcyqC1rEv

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native           | 6.0.2
| @react-navigation/material-top-tabs    | 6.0.6
| react-native-safe-area-context      |   3.3.2
| react-native-screens               |   3.7.2
| react-native-gesture-handler     |     1.10.3
| react-native-tab-view            |     3.1.1
| react-native-pager-view         |       5.4.8
| react-native                    |       0.65.1
| node                        |          16.11.1
| npm            |          8.0.0

**Comment by YogiHa** [comment]
BTW, 
`useFocusEffect` of next screen indeed fired, just the tab view is not switching

**Comment by YogiHa** [comment]
Reopen until https://github.com/callstack/react-native-pager-view/pull/485#issue-1065293397 will merged...

**Comment by react-one** [comment]
I spend a good time, I reached the same thing. Was about to push a pr to find it already handled. I wish I checked again the issue.

**Comment by react-one** [comment]
I was about to push a PR, to find all was handled. I wish i get to check the issue first.

The direction between RTL and LTR reverse. What's forward take the reverse direction in RTL. But then the index just take the right sense. forward is in the positive direction.

Seeing the PR above there is a one-line to be changed. i left a small review.

react-native-tabs-view need to updated too.

**Comment by PeterAbdalla** [comment]
Still an issue even after updating ReactNativePagerView.m

**Comment by MohamedLamineAllal** [comment]
@PeterAbdalla did u use the changes made by this [PR]( https://github.com/callstack/react-native-pager-view/pull/485 ) ??
As it is not merged yet !
As I remember when I tested those changes. It did fix the problem.

**Comment by PeterAbdalla** [comment]
@MohamedLamineAllal Yes, I rechecked it now. I made same the changes he did to ReactNativePagerView.m, but still the tabs are not pressed. I don't know what am I doing wrong if it worked for you.

**Comment by syedamirali14** [comment]
i have fixed this issue on iOS will submit a PR

**Comment by alzalabany** [comment]
is it merged yet?

**Comment by procapital** [comment]
Can someone merge it please?

**Comment by sebasg0** [comment]
Hey @procapital @alzalabany @YogiHa , issue coming from rn-pager-view and fixed it raising this pr https://github.com/callstack/react-native-pager-view/pull/613 help me get this merged asap please

**Comment by Roshdy** [comment]
> Hey @procapital @alzalabany @YogiHa , issue coming from rn-pager-view and fixed it raising this pr [callstack/react-native-pager-view#613](https://github.com/callstack/react-native-pager-view/pull/613) help me get this merged asap please

Not that this has been merged successfully, what is required to update react-navigation with the new dependency?

**Comment by sebasg0** [comment]
Just update react-native-pager-view to latest version in your project. For me is working fine after my pr for merged

**Comment by sebasg0** [comment]
@satya164 we should be able to close this out as it was a problem in pager view and I already fixed

**Comment by Roshdy** [comment]
Expo objects (incompatible version warning), is it safe to proceed?

**Comment by Roshdy** [comment]
Actually I just upgraded pager to 6.0.1, but it's still not working in RTL. No press action what so ever

**Comment by sebasg0** [comment]
Expo I haven’t tried, won’t be able to tell you. The issue was on iOS in their native implementation.

**Comment by Roshdy** [comment]
I guess since expo haven't upgraded their recommended version of react-navigation or pager to 6x, then it won't work until they do.
I'll have to sadly eject

**Comment by Roshdy** [comment]
I believe it's not an Expo issue

Here is a Snack for `top-tabs` (*Not Working*)
https://snack.expo.dev/@mohroshdy/e36ec4

Here is a Snack for `bottom-tabs` (*Working*)
https://snack.expo.dev/@mohroshdy/bb79a0

**Comment by anasalaqeel** [comment]
react-native-pager-view have a prop to support RTL  layout `layoutDirection: ('ltr' | 'rtl' | 'locale')` but this prop has still not been passed to  material-top-tabs for no real reason

**Comment by talhazi** [comment]
@YogiHa @anasalaqeel is there any update re-this one? I still encountering the same issue

**Comment by anasalaqeel** [comment]
@talhazi still nothing, for now, I just had to re-create top tabs from scratch to achieve what I want

**Comment by talhazi** [comment]
@anasalaqeel I see, but it's working for the bottom-tabs - doesn't it just require passing the correct prop `layoutDirection: ('ltr' | 'rtl' | 'locale')` to react-native-pager-view?

**Comment by satya164** [comment]
Closing as this should be fixed in [db6433a](https://github.com/react-navigation/react-navigation/commit/db6433ab7995fb5ccf06b9d3adf418756f45db31). Please upgrade to `react-native-tab-view@5.0.0-alpha.9` and give it a try.
