### ISSUE TITLE
Tab.Screen not expanding to full height on first load (iOS only)

### ISSUE THREAD

**Issue by ajtosh77** [react-navigation/react-navigation#10528]
### Current behavior

Sample Code: https://github.com/JarX-Concepts/NavBug

***

import * as React from 'react';
import {View} from 'react-native';
import {NavigationContainer} from '@react-navigation/native';
import {createMaterialTopTabNavigator} from '@react-navigation/material-top-tabs';
import {createBottomTabNavigator} from '@react-navigation/bottom-tabs';

export const ChildScreen1 = ({route}) => {
  return <View style={{flex: 1, backgroundColor: 'green'}} />;
};

export const ChildScreen2 = ({route}) => {
  return <View style={{flex: 1, backgroundColor: 'red'}} />;
};

const ScreenTab = createMaterialTopTabNavigator();
export const ExploreScreen = () => {
  return (
    <ScreenTab.Navigator>
      <ScreenTab.Screen name="Child 1" component={ChildScreen1} />
      <ScreenTab.Screen name="Child 2" component={ChildScreen2} />
    </ScreenTab.Navigator>
  );
};

const Tab = createBottomTabNavigator();
function App() {
  return (
    <NavigationContainer>
      <View style={{flex: 1, backgroundColor: 'blue'}}>
        <Tab.Navigator>
          <Tab.Screen name="Feed" component={ExploreScreen} />
        </Tab.Navigator>
      </View>
    </NavigationContainer>
  );
}

export default App;

***

On first render (iOS only) it usually does not flex to the full height:

<img width="400" alt="Screen Shot 2022-04-18 at 10 16 08 AM" src="https://user-images.githubusercontent.com/76704643/163847636-eb861cf0-de00-4ae4-baa6-0afd5bd46fc4.png">

If you navigate to another screen and come back, it expands as expected. Video:

https://user-images.githubusercontent.com/76704643/163847606-bdc50378-01f3-45bc-b4c7-99d2223559a8.mov

  "dependencies": {
    "@react-navigation/bottom-tabs": "^6.3.1",
    "@react-navigation/material-top-tabs": "^6.2.1",
    "@react-navigation/native": "^6.0.10",
    "@react-navigation/native-stack": "^6.6.1",
    "react": "17.0.2",
    "react-native": "0.68.1",
    "react-native-pager-view": "^5.4.15",
    "react-native-safe-area-context": "^4.2.4",
    "react-native-screens": "^3.13.1"
  },

### Expected behavior

I expected the "child 1" screen to flex to the full height on the first load.

### Reproduction

https://github.com/JarX-Concepts/NavBug

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.2.1
| @react-navigation/bottom-tabs          | ^6.3.1
| @react-navigation/material-bottom-tabs | ^6.2.1
| @react-navigation/material-top-tabs    | ^6.2.1
| @react-navigation/native-stack         | ^6.6.1
| react-native-safe-area-context         | ^4.2.4
| react-native-screens                   | ^3.13.1
| react-native-pager-view                | ^5.4.15
| react-native                           | 0.68.1
| node                                   | v16.9.1
| npm or yarn                            | npm

**Comment by harisraza123** [comment]
I am facing the same issue

**Comment by PatrickBokhove** [comment]
For me this bug was caused by `react-native-pager-view` which is a dependency of `@react-navigation/material-top-tabs`

My `react-native-pager-view` was on version 5.4.15 and when i reverted it to 5.4.1 it was fixed. Don't forget to also downgrade the version in your pod files.

**Comment by ajtosh77** [comment]
Thank you @PatrickBokhove ! That fixes it for me too!

**Comment by gersomvg** [comment]
@PatrickBokhove Good catch. Unfortunately this is not a solution for expo sdk 45

**Comment by ajtosh77** [comment]
> @PatrickBokhove Good catch. Unfortunately this is not a solution for expo sdk 45
> 
> A solution that seems to work is to set a `key` prop on the material tab navigator component and update this key directly after the initial mount 🤷🏻

**Comment by ajtosh77** [comment]
> @PatrickBokhove Good catch. Unfortunately this is not a solution for expo sdk 45
> 
> A solution that seems to work is to set a `key` prop on the material tab navigator component and update this key directly after the initial mount 🤷🏻

I think that would cause it to get recreated immediately, which makes sense why it works as a workaround. But a seems a little inefficient. 

Looks like the issue is captured here: https://github.com/callstack/react-native-pager-view/issues/523

Hopefully, it gets resolved in pager-view...

**Comment by MichaelPHolstein** [comment]
> @PatrickBokhove Good catch. Unfortunately this is not a solution for expo sdk 45
> 
> A solution that seems to work is to set a `key` prop on the material tab navigator component and update this key directly after the initial mount 🤷🏻

@gersomvg  Can you provide a small example of how to update a key prop? I'm facing the same issue (also using expo sdk 45) and looking for a temporary fix till it's been updated.

**Comment by gersomvg** [comment]
> @gersomvg Can you provide a small example of how to update a key prop? I'm facing the same issue (also using expo sdk 45) and looking for a temporary fix till it's been updated.

```
const [flipKey, setFlipKey] = React.useState(0)
React.useEffect(() => {
    setFlipKey(1)
}, [])

...

<Tab.Navigator key={flipKey}>
```

Be aware that it causes a slight flicker, although I think that's more noticeable in the development build than the production build.

**Comment by apedroferreira** [comment]
same issue

**Comment by ajtosh77** [comment]
My work around for this issue is to remove the change from react-native-pager-view:

https://github.com/callstack/react-native-pager-view/issues/523#issuecomment-1129731887

Hopefully there is a permeant fix in an upcoming react-native-pager-view

**Comment by gustavomanolo** [comment]
Hi everyone, I'm experiencing the same issue in Expo 46, were you able to get around this issue?
Thanks :)

**Comment by Brune04** [comment]
I'm also having the same issue with Expo 46. Would love to know if there was a solution to this

**Comment by gersomvg** [comment]
@Brune04 only `5.4.24` is included with expo 46. I think there is no way to update to `5.4.25` when using the managed workflow, someone correct me if I'm wrong.

**Comment by raajnadar** [comment]
@Brune04 you can use a custom dev client, by creating your own expo go app.

If the update is JS only on that library it should work with the version bumped unless there are no native changes, but you need to ignore the warning of `expo doctor`

**Comment by gersomvg** [comment]
@raajnadar There are native changes.

**Comment by raajnadar** [comment]
> @raajnadar There are native changes.

Use expo dev client

**Comment by gersomvg** [comment]
@raajnadar is that the new term for `bare workflow` in the new EAS Build flow? Otherwise I'm a bit confused where that fits into the mental model of managed vs. bare.

But indeed, with the bare workflow this should be possible. Although I'm not sure if custom dev clients work with legacy expo-updates, which I'm on.

**Comment by raajnadar** [comment]
> @raajnadar is that the new term for `bare workflow` in the new EAS Build flow? Otherwise I'm a bit confused where that fits into the mental model of managed vs. bare.
> 
> But indeed, with the bare workflow this should be possible. Although I'm not sure if custom dev clients work with legacy expo-updates, which I'm on.

You create your own copy of expo go with your custom native changes, you are still in managed flow with your code,

You need to do your native changes, create a build with EAS, install that in you device, when you open the app it will be like expo go app but with your native code, as long as you do only JS changes you can use the same build

Full documentation here https://docs.expo.dev/development/getting-started/

**Comment by anbumadasamy** [comment]
i also have this problem..now its fixed

> @Brune04 only `5.4.24` is included with expo 46. I think there is no way to update to `5.4.25` when using the managed workflow, someone correct me if I'm wrong.

Thanks. working for me

**Comment by Carles11** [comment]
Same here. 
Working in expo 46. My `react-native-pager-view `was on version 5.4.24 and when i ugraded it to "6.1.0" it was fixed. 
Thanks @PatrickBokhove!

**Comment by hyenaManager** [comment]
Im still facing this error in "react-native-pager-view": "6.2.0", :)
