### ISSUE TITLE
 requireNativeComponent: "RNCViewPager" was ton found in the UIManager

### ISSUE THREAD

**Issue by bimix** [react-navigation/react-navigation#10537]
### Current behavior

I followed the steps presented in the [documentation ](https://reactnavigation.org/docs/material-top-tab-navigator) but when I tried to run the app it shows this error:

 **

> requireNativeComponent: "RNCViewPager" was ton found in the UIManager

**

### Expected behavior

The app should run without issues. 

### Reproduction

https://snack.expo.dev/MneN5bkC69

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [X] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.0.10
| @react-navigation/drawer               | 6.4.1
| @react-navigation/material-top-tabs    | 6.2.1
| @react-navigation/stack                | 6.2.1
| react-native-safe-area-context         | 4.2.4
| react-native-screens                   | 3.13.1
| react-native-gesture-handler           | 2.3.2
| react-native-reanimated                | 2.2.4
| react-native-tab-view                  | 3.1.1
| react-native-pager-view                | 5.4.15
| react-native                           | 0.68.0
| node                                   | v16.13.1
| npm                            | 8.3.0

**Comment by bimix** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `@react-navigation/bottom-tabs`
> * `@react-navigation/material-bottom-tabs`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.

Bad bot! You couldnt find them because I am not using them.

**Comment by raajnadar** [comment]
Are you using expo? or recently upgraded the react-native version?

**Comment by bimix** [comment]
> Are you using expo? or recently upgraded the react-native version?
> 
> P.S. - Your repro is not running they have some errors

I am using RN but I think I fixed the problem by manually linking like this:

`npm i -S react-native-pager-view@next
`npx react-native link react-native-pager-view

**Comment by devbiansor** [comment]
Same issue with RN 0.69

**Comment by fongchinghinunsw** [comment]
This issue is still occuring in `"react-native-pager-view": "6.1.2"`, I'm using `"react-native": "0.71.7"` and the link command has been deprecated, does anyone know an elegant solution?

**Comment by raajnadar** [comment]
I am closing this because this is not a library bug most likely a configuration issue on your codebase

https://github.com/callstack/react-native-pager-view/blob/master/MIGRATION.md

Make sure you follow both the steps correctly as per the platform

https://reactnavigation.org/docs/getting-started

https://reactnavigation.org/docs/material-top-tab-navigator/
