### ISSUE TITLE
[Android] content goes behind header in @react-navigation/native-stack 

### ISSUE THREAD

**Issue by osliver** [react-navigation/react-navigation#10531]
### Current behavior

on android content appears behind header
![Screenshot_1650373585](https://user-images.githubusercontent.com/97607365/164011075-3b91d918-f922-45c1-9f7c-1dc65af52227.png)

```ts
import React from 'react';
import {View, Text} from 'react-native';

export const Content: React.FC = () => {
  return (
    <View style={{flex: 1, backgroundColor: 'lightblue'}}>
      <Text>Content</Text>
      <Text>Content</Text>
      <Text>Content</Text>
      <Text>Content</Text>
      <Text>Content</Text>
      <Text>Content</Text>
      <Text>Content</Text>
      <Text>Content</Text>
      <Text>Content</Text>
      <Text>Content</Text>
    </View>
  );
};
```

Navigation screen
```ts
     <MainStack.Screen
        name={Screens.Content}
        component={Content}
        options={{
          title: '',
          headerShown: true,
        }}
        />
      ```

### Expected behavior

content starts below header

### Reproduction

found issue during corporate project

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |6.0.10
| @react-navigation/bottom-tabs          |6.3.1
| @react-navigation/drawer               |-
| @react-navigation/material-bottom-tabs |-
| @react-navigation/material-top-tabs    |-
| @react-navigation/stack                |6.2.1
| @react-navigation/native-stack         |6.6.1
| react-native-safe-area-context         |4.2.4
| react-native-screens                   |3.13.1
| react-native-gesture-handler           |2.2.0
| react-native-reanimated                |2.6.0
| react-native-tab-view                  |-
| react-native-pager-view                |-
| react-native                           |0.66.4
| expo                                   |-
| node                                   |12.22.11
| npm or yarn                            |npm

**Comment by PatrickBokhove** [comment]
I was encountering this issue too, and it got fixed for me when i downgraded `@react-navigation/native-stack` from 6.6.1 back to 6.2.2. Looking at their [changelog](https://github.com/react-navigation/react-navigation/blob/main/packages/native-stack/CHANGELOG.md), they did a lot of changes to the header since then.

**Comment by channeladam** [comment]
Same issue here - on Android, the content is hidden behind the header

**Comment by fleecmf** [comment]
I was encountering this issue too

@react-navigation/native: 6.6.2
react-native: 0.68.0
 react-native-reanimated : 2.8.0

**Comment by wcastand** [comment]
by adding `enableLayoutAnimations(false);` in my `App.tsx` the issue disappears. just in case it could help some people that don't use layout animations.

**Comment by anwersolangi** [comment]
Facing the same issue when using entering or exiting animation from the Reanimated, currently I have fixed using [channeladam](https://github.com/channeladam) solution, but we need a permanent fix.

**Comment by janicduplessis** [comment]
I tracked down the issue to this code in react-native-reanimated

```diff
diff --git a/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java b/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
index b0e33b0..dd754dd 100644
--- a/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
+++ b/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/layoutReanimation/ReanimatedNativeHierarchyManager.java
@@ -272,28 +272,6 @@ public class ReanimatedNativeHierarchyManager extends NativeViewHierarchyManager
   public synchronized void updateLayout(
       int parentTag, int tag, int x, int y, int width, int height) {
     super.updateLayout(parentTag, tag, x, y, width, height);
-    if (isLayoutAnimationDisabled()) {
-      return;
-    }
-    try {
-      View viewToUpdate = this.resolveView(tag);
-      ViewManager viewManager = this.resolveViewManager(tag);
-      String viewManagerName = viewManager.getName();
-      View container = resolveView(parentTag);
-      if (container != null
-          && viewManagerName.equals("RNSScreen")
-          && this.mReaLayoutAnimator != null) {
-        this.mReaLayoutAnimator.applyLayoutUpdate(
-            viewToUpdate,
-            (int) container.getX(),
-            (int) container.getY(),
-            container.getWidth(),
-            container.getHeight());
-      }
-    } catch (IllegalViewOperationException e) {
-      // (IllegalViewOperationException) == (vm == null)
-      e.printStackTrace();
-    }
   }
 
   @Override
 ```

**Comment by alzalabany** [comment]
alright, so to sum it up for a villager like me. how to resolve this?

**Comment by efstathiosntonas** [comment]
fixed it using this patch on `6.9.1`:

`@react-navigation+native-stack+6.9.1.patch`

```patch
diff --git a/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx b/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
index f605bd8..c5b4228 100644
--- a/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
+++ b/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
@@ -324,6 +324,7 @@ const SceneView = ({
                   headerTopInsetEnabled={headerTopInsetEnabled}
                 >
                   <HeaderBackContext.Provider value={headerBack}>
+                    {headerShown !== false && isAndroid && <View style={{marginTop:headerHeight}}></View>}
                     {render()}
                   </HeaderBackContext.Provider>
                 </MaybeNestedStack>

```

**Comment by Maxth** [comment]
> this is what happening, it's well explained on docs: https://reactnavigation.org/docs/native-stack-navigator#headertransparent
> 
> fixed it using this patch on `6.9.1`:
> 
> `@react-navigation+native-stack+6.9.1.patch`
> 
> ```diff
> diff --git a/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx b/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
> index f605bd8..c5b4228 100644
> --- a/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
> +++ b/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
> @@ -324,6 +324,7 @@ const SceneView = ({
>                    headerTopInsetEnabled={headerTopInsetEnabled}
>                  >
>                    <HeaderBackContext.Provider value={headerBack}>
> +                    {headerShown !== false && isAndroid && <View style={{marginTop:headerHeight}}></View>}
>                      {render()}
>                    </HeaderBackContext.Provider>
>                  </MaybeNestedStack>
> ```

I tried this solution but then I got a gap the same height like the header underneath each header. For me it worked putting the extra View further up the markup hierarchy:

```
diff --git a/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx b/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
index f605bd8..7df21b7 100644
--- a/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
+++ b/node_modules/@react-navigation/native-stack/src/views/NativeStackView.native.tsx
@@ -280,6 +280,7 @@ const SceneView = ({
       // this prop is available since rn-screens 3.16
       freezeOnBlur={freezeOnBlur}
     >
+      {headerShown !== false && isAndroid && <View style={{marginTop: headerHeight}} />}
       <NavigationContext.Provider value={navigation}>
         <NavigationRouteContext.Provider value={route}>
           <HeaderShownContext.Provider
```

When using transition animations this causes flickering though - not an ideal workaround.

**Comment by efstathiosntonas** [comment]
@Maxth thank you for pointing out the flickering, I totally forgot that I had applied it and I was wondering why the screen was flickering when the keyboard was opened on Android and an absolute positioned animated `TextInput` was pulled up from the bottom of the screen. I've just applied my patch, fast tested on Android and then got back to iOS simulator to continue working and forgot about it.

I've applied your patch version and the issue persists as you mentioned. The only way for the flickering to go away is to use:

```
<IndexStack.Screen
          name="XXX"
          component={XXX}
          options={{
            headerTransparent: true
          }}
        />
```

demo video, no patch applied, at the beginning `headerTransparent: true` and at the end `headerTransparent: false (default value)`:


https://user-images.githubusercontent.com/717975/197127491-b4f1c7a3-1420-4c18-915b-e5693085327e.mp4

**Comment by ScreamZ** [comment]
Still having content appearing behind the header, but only when i go to the screen then i go back then i go again (the second time and others, the header mask part of content)

**Comment by Maxth** [comment]
@efstathiosntonas Thanks, will try your solution to get rid of flickering.

**Comment by bebe84** [comment]
I can confirm that indeed this is issue with react-native-reanimated lib, enableLayoutAnimations(false) does the job for now. I wonder why they are doing such nasty thing and only for Android.

**Comment by Maxth** [comment]
For anyone referencing this thread for a solution the issue was fixed by reanimated 2.14

**Comment by efstathiosntonas** [comment]
And here’s the PR that addresses this: https://github.com/software-mansion/react-native-reanimated/pull/3791

**Comment by FedeRBeije** [comment]
Hi, still having the same issue on android. 
    "react-native-reanimated": "2.14.4",
    "@react-navigation/bottom-tabs": "^6.5.3",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/native-stack": "^6.7.0",

**Comment by Glaubenio** [comment]
Still having the same issue here
