### ISSUE TITLE
@react-navigation/material-top-tabs delay and lag on tab press

### ISSUE THREAD

**Issue by Jamal-ReachFirst** [react-navigation/react-navigation#11047]
### Current behavior

I am using topTab(scrollable) inside another screen.

Swipe b/w tabs are faster but facing issues when tabbar is pressed (delay and lag).

### Expected behavior

Swipe and tab press should perform the same way, without delays and lag.

### Reproduction

https://snack.expo.dev/@jamal_rn/tob-tabbar

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [X] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

    "@react-navigation/material-top-tabs": "^6.3.1",
    "@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
    "react": "17.0.2",
    "react-native": "0.67.4",
    "react-native-pager-view": "^6.1.1",
    "react-native-reanimated": "^2.9.1",
    "react-native-safe-area-context": "^4.3.1",
    "react-native-screens": "^3.15.0",
    "react-native-tab-view": "^3.3.0",

**Comment by Jamal-ReachFirst** [comment]
> Couldn't find version numbers for the following packages in the issue:
> 
> * `flipper-plugin-react-navigation`
> 
> Can you update the issue to include version numbers for those packages? The version numbers must match the format 1.2.3.
> 
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/native` (found: `6.0.11`, latest: `6.0.14`)
> * `@react-navigation/stack` (found: `6.2.2`, latest: `6.3.5`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Updated but still facing the same issue.

**Comment by Jamal-ReachFirst** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/material-top-tabs` (found: `6.3.1`, latest: `6.5.1`)
> * `@react-navigation/native` (found: `6.0.14`, latest: `6.1.1`)
> * `@react-navigation/stack` (found: `6.3.5`, latest: `6.3.9`)
> * `react-native-tab-view` (found: `3.3.0`, latest: `3.3.4`)
> * `flipper-plugin-react-navigation` (found: `1.3.16`, latest: `1.3.20`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

Everything up to date.

**Comment by okwasniewski** [comment]
Hey, @Jamal-ReachFirst I've created a PR that tries to fix this issue. It would be awesome if you could run the example app from the PR and check if this fixes the issue for you.

**Comment by Jamal-ReachFirst** [comment]
> Hey, @Jamal-ReachFirst I've created a PR that tries to fix this issue. It would be awesome if you could run the example app from the PR and check if this fixes the issue for you.

Ok i will try

**Comment by Jamal-ReachFirst** [comment]
Have a look please


https://user-images.githubusercontent.com/112681358/208080014-9b9ef344-200f-4779-becd-bf62dc1a6fce.mov

**Comment by okwasniewski** [comment]
Okay @Jamal-ReachFirst I didn't know it's that bad. It depends on the version of android you are running. So maybe the solution would be to allow users to disable the touchable ripple effect, what do you think?

**Comment by Jamal-ReachFirst** [comment]
> 

But why swipe b/w screen are faster and the press item has this delay(getting worse with number of tabs and items inside tab screes).

I don't think ripple effect is causing the issue, can you please provide the fix I will try it.

**Comment by Jamal-ReachFirst** [comment]
> @Jamal-ReachFirst I've updated the PR to use other implementation of the underlying button the same as other touchable ripple buttons across react navigation. Can you launch the example app in expo by scanning the QR code [here](https://expo.dev/@react-navigation/react-navigation-example?serviceType=eas&distribution=expo-go&scheme=exp+react-navigation-example&channel=pr-11105&sdkVersion=46.0.0) in the PR and check if this solves it for you?

No repo found!!
Please update your repo link.

**Comment by Jamal-ReachFirst** [comment]
Any progress??

**Comment by ReeturajThakur7** [comment]
Facing this same issue. Any update for the same

**Comment by andonivianez** [comment]
same here, any update?

**Comment by Jamal-ReachFirst** [comment]
Look at the output [here](https://github.com/react-navigation/react-navigation/issues/11047#issuecomment-1354534536)

**Comment by andonivianez** [comment]
> Look at the output [here](https://github.com/react-navigation/react-navigation/issues/11047#issuecomment-1354534536)

yes, I´m facing the same issue. Did you fixed it?

**Comment by danielrhodes** [comment]
I'm seeing this on iOS as well with bottom tabs. The tab is not re-rendering either - it's just the switch.

**Comment by sagarj-iprogrammer** [comment]
"@react-native-masked-view/masked-view": "^0.2.9",
    "@react-navigation/material-top-tabs": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
    "react": "18.2.0",
    "react-native": "0.72.2",
    "react-native-gesture-handler": "^2.12.0",
    "react-native-pager-view": "^6.2.1",
    "react-native-reanimated": "^3.4.0",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.23.0",
    "react-native-tab-view": "^3.5.2"
    crash on click on tab multiple time  for new Arch true

**Comment by sagarj-iprogrammer** [comment]
"@react-navigation/material-top-tabs": "^6.2.2",
"@react-navigation/native": "^6.0.11",
    "@react-navigation/stack": "^6.2.2",
"react-native": "0.71.13",
"react-native-pager-view": "^6.1.0",
"react-native-reanimated": "3.0.2",
 "react-native-tab-view": "3.1.1",
new Arch  = true  
 "react-native-tab-view if use  latest version than 
 width:'auto' not working  if remove then to much gap between tabs 
tabBarItemStyle:{
          width:'auto'
        },

tabBarIndicatorStyle={ 
 backgroundColor: '#EAF2FC',
          height: 42,
          borderBottomWidth: 2,
          borderBottomColor: 'red',
}  and if  also app is crash switching between tabs multiple time  also to much laggs between tabs

**Comment by senghuotlay** [comment]
any update on this guys?

**Comment by narnau** [comment]
any update on this guys?

**Comment by thenxkk** [comment]
same , any update?

**Comment by bakiicelebi** [comment]
> @okwasniewski Have a look please,
> 
>  TestApp.mov


I faced the same issue yesterday, but I'm not sure if it's fixed dynamically.


## React Native TabView, The Issue of Centering When Clicking The TabBar Button

"node_modules\react-native-tab-view\src\TabBar.tsx"

![image](https://github.com/react-navigation/react-navigation/assets/115392938/92e493d0-29cc-4848-8393-0ea7b75a6e96)

The above code is causing the tab to center, and we're forced to wait for it.

#### And I did't want a feedback from the button, I fixed it like this ->

## React Native TabView, Preventing feedback when clicking the TabBar button

"node_modules\react-native-tab-view\src\PlatformPressable.tsx"

![image](https://github.com/react-navigation/react-navigation/assets/115392938/2ba823c6-92cd-4239-b39d-0e9b1dc4a423)

**Comment by lhguerra** [comment]
Will this ever be addressed?

**Comment by coofzilla** [comment]
some issue, anyone have a workaround?

**Comment by rxeal** [comment]
I found a way to remove the initial delay when switching tabs! Setting `lazy: false` in `screenOptions` ensures all tabs are preloaded, so there's no lag on the first press.  

Here’s the working solution:  

```tsx
<Tabs
  screenOptions={{
    lazy: false,
  }}
>
```

If memory usage becomes an issue, another option is keeping `lazy: true` but using `renderLazyPlaceholder` to preload content in the background.

**Comment by sayan-avantai** [comment]
scrolling is fine, but while pressing the active tab is showing inaccurate. it is acting weird.

**Comment by vsk-mo** [comment]
For me the issue resolved with below version


   ```
 "@react-navigation/bottom-tabs": "7.4.5",
    "@react-navigation/drawer": "7.5.6",
    "@react-navigation/material-top-tabs": "7.3.5",
    "@react-navigation/native": "7.1.17",
    "@react-navigation/stack": "7.4.5",
```


```
    "react": "19.0.0",
    "react-native": "0.79.5",
```

**Comment by abdullatifHH** [comment]
this issue persist, none of them above solutions didnt worked ..
