### ISSUE TITLE
Swiping during an animation causes TabView to stop responding to navigationState

### ISSUE THREAD

**Issue by Matias-A** [react-navigation/react-navigation#11088]
### Current behavior

Whenever the tab is changed by swiping during an ongoing animation, TabView stops responding to index changes altogether. Steps to reproduce (can be reproduced in the example Snack project): 
- Click "Second" tab in the tab bar to start a tab change animation
- Before the animation finishes, **quickly** swipe right to navigate back to the "First" tab
- Now TabView no longer responds to index changes initiated by changes in `navigationState` (e.g. clicking on a tab in the tab bar doesn't do anything now), but only to swiping (however, even changing screens by swiping breaks if lazy loading is enabled, since apparently the internal `navigationState` is stuck to its original value)

Seemingly only happens in iOS.

https://user-images.githubusercontent.com/8319613/206811868-dd031f79-2540-403a-a434-7a319092de6b.mov

### Expected behavior

TabView should respond to changes in `navigationState`

### Reproduction

https://snack.expo.dev/@satya164/react-native-tab-view-quick-start?platform=ios

### Platform

- [ ] Android
- [X] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/​bottom-tabs
- [ ] @react-navigation/​drawer
- [ ] @react-navigation/​material-bottom-tabs
- [ ] @react-navigation/​material-top-tabs
- [ ] @react-navigation/​stack
- [ ] @react-navigation/​native-stack
- [X] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| react-native-tab-view                  | 3.3.2

**Comment by okwasniewski** [comment]
Hey, this should be fixed in the latest version of react-native-pager-view, please update to `6.1.2` and let me know 👍

**Comment by engincankizilyar** [comment]
tried with react-native-pager-view version `6.1.2` but the issue still continues
