### ISSUE TITLE
Cannot read property 'prototype' in React Navigation 5

### ISSUE THREAD

**Issue by Victorcassiano** [react-navigation/react-navigation#11160]
### Current behavior

`
import React, { createRef, useEffect } from 'react';
import { DrawerLayoutAndroid } from 'react-native'
import { createStackNavigator } from '@react-navigation/stack';
import { createDrawerNavigator } from '@react-navigation/drawer';
import { NavigationContainer } from '@react-navigation/native';
import SplashScreen from 'react-native-splash-screen';

import Home from '../pages/Home';
// import DrawerScreen from './Drawer';
import About from '../pages/About';

const Stack = createStackNavigator();
const Drawer = createDrawerNavigator();

export const drawer = createRef<DrawerLayoutAndroid>();

const Routes: React.FC = () => {

  useEffect(() => {
    SplashScreen.hide();
  });

  return (
    <NavigationContainer>
      <Drawer.Navigator initialRouteName="Home">
        <Drawer.Screen name="Home" component={Home} />
        <Drawer.Screen name="About" component={About} />
      </Drawer.Navigator>
      <Stack.Navigator
        screenOptions={{
          headerShown: false,
          cardStyle: {
            backgroundColor: 'transparent',
          },
        }}
        initialRouteName="Home"
      >
        <Stack.Screen name="Home" component={Home} />
        <Drawer.Screen name="About" component={About} />
      </Stack.Navigator>
    </NavigationContainer>
  );
};
`

<img src="https://i.imgur.com/MQVmTgR.png" alt="MarineGEO circle logo" style="height: 100px; width:100px;"/>

### Expected behavior

[![Video]()](https://www.youtube.com/watch?v=gG097DJ5JBE)

What I would like to happen!

### Reproduction

https://snack.expo.dev/@victorcassiano/drawer

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-bottom-tabs
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view
- [ ] flipper-plugin-react-navigation

### Environment

{
  "name": "snapdown",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "build": "generateApk.cmd",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/drawer": "^5.11.2",
    "@react-navigation/native": "^5.9.2",
    "@react-navigation/stack": "^5.14.3",
    "@unform/core": "^2.1.6",
    "@unform/mobile": "^2.1.6",
    "add": "^2.0.6",
    "axios": "^0.24.0",
    "date-fns": "^2.19.0",
    "date-fns-tz": "^1.1.6",
    "dotenv": "^8.2.0",
    "intl": "^1.2.5",
    "lottie-ios": "3.1.8",
    "lottie-react-native": "^4.0.2",
    "react": "18.1.0",
    "react-native": "0.70.6",
    "react-native-animated-webp": "^0.0.8",
    "react-native-device-info": "^10.3.0",
    "react-native-fast-image": "^8.6.3",
    "react-native-gesture-handler": "^2.9.0",
    "react-native-modalize": "^2.0.12",
    "react-native-normalize": "^1.0.1",
    "react-native-paper": "^5.1.2",
    "react-native-reanimated": "^3.0.0-rc.9",
    "react-native-safe-area-context": "^3.3.2",
    "react-native-screens": "^3.10.1",
    "react-native-splash-screen": "^3.3.0",
    "react-native-svg": "^12.1.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-video": "^5.2.1",
    "react-native-ytdl": "^4.8.3",
    "react-timer-hook": "^3.0.5",
    "rn-fetch-blob": "^0.12.0",
    "styled-components": "^5.3.6",
    "styled-components-react-native": "^1.0.0",
    "twitter-url-direct": "^1.0.8",
    "yarn": "^1.22.19",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.70.6",
    "@types/react-native-vector-icons": "^6.4.13",
    "@types/react-native-video": "^5.0.14",
    "@types/react-test-renderer": "^18.0.0",
    "@types/styled-components-react-native": "^5.2.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "eslint-plugin-prettier": "^3.1.1",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "prettier": "^1.18.2",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}

**Comment by Victorcassiano** [comment]
> The versions mentioned in the issue for the following packages differ from the latest versions on npm:
> 
> * `@react-navigation/drawer` (found: `5.11.2`, latest: `6.5.7`)
> * `@react-navigation/native` (found: `5.9.2`, latest: `6.1.2`)
> * `@react-navigation/stack` (found: `5.14.3`, latest: `6.3.11`)
> 
> Can you verify that the issue still exists after upgrading to the latest versions of these packages?

yes, already checked

**Comment by anuragipankaj** [comment]
same issue

**Comment by pietro-marrone-dka** [comment]
Same issue

**Comment by maulikdhameliya** [comment]
It got fixed by updating to version 6

Previous
```
    "@react-navigation/drawer": "^5.11.4",
    "@react-navigation/native": "^5.9.8",
    "@react-navigation/stack": "^5.12.8",
```

Updated

```
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/stack": "^6.3.17",
```

**Comment by Zeusmist** [comment]
I got this same issue and I already updated all packages and followed the documentation, but I still get this same error.

Here is a detailed stack trace:
![image](https://github.com/react-navigation/react-navigation/assets/51177741/f13ba368-6707-4628-8505-e8ac8bd6482c)


@Victorcassiano If you were able to resolve this issue, would you mind sharing how you did?

**Comment by fujikazu** [comment]
same error

```
 BUNDLE  ./index.js 

 LOG  Running "*****_app" with {"rootTag":1,"initialProps":{}}
 ERROR  TypeError: Cannot read property 'prototype' of undefined, js engine: hermes
 ERROR  Error: Requiring module "node_modules/@react-navigation/drawer/src/views/legacy/Drawer.tsx", which threw an exception: TypeError: Cannot read property 'prototype' of undefined, js engine: hermes
 ERROR  TypeError: Cannot read property 'default' of undefined


This error is located at:
    in DrawerViewBase (at DrawerView.tsx:320)
    in RCTView (at View.js:32)
    in View (at GestureHandlerRootView.tsx:17)
    in GestureHandlerRootView (at DrawerView.tsx:319)
    in RCTView (at View.js:32)
    in View (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at DrawerView.tsx:318)
    in DrawerView (at createDrawerNavigator.tsx:126)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:696)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createDrawerNavigator.tsx:125)
    in DrawerNavigator (at DrawerStack.js:32)
    in Drawer (at navigators/index.js:31)
    in RCTView (at View.js:32)
    in View (at navigators/index.js:29)
    in TabBarWrapScreen (at SceneView.tsx:132)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:217)
    in RCTView (at View.js:32)
    in View (at DebugContainer.native.tsx:27)
    in DebugContainer (at NativeStackView.native.tsx:80)
    in MaybeNestedStack (at NativeStackView.native.tsx:319)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at src/index.native.tsx:260)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:163)
    in DelayedFreeze (at src/index.native.tsx:259)
    in InnerScreen (at src/index.native.tsx:422)
    in Screen (at NativeStackView.native.tsx:236)
    in SceneView (at NativeStackView.native.tsx:360)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:163)
    in DelayedFreeze (at src/index.native.tsx:177)
    in RNSScreenStack (at src/index.native.tsx:184)
    in ScreenStack (at NativeStackView.native.tsx:349)
    in NativeStackViewInner (at NativeStackView.native.tsx:420)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:87)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:419)
    in NativeStackView (at createNativeStackNavigator.tsx:72)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:696)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createNativeStackNavigator.tsx:71)
    in NativeStackNavigator (at navigators/index.js:71)
    in Root (at src/index.js:54)
    in QueryClientProvider (at src/index.js:52)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at src/index.js:44)
    in PersistGate (at src/index.js:43)
    in Provider (at src/index.js:42)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in *****_app(RootComponent) (at renderApplication.js:60), js engine: hermes
 ERROR  TypeError: Cannot read property 'default' of undefined

This error is located at:
    in DrawerViewBase (at DrawerView.tsx:320)
    in RCTView (at View.js:32)
    in View (at GestureHandlerRootView.tsx:17)
    in GestureHandlerRootView (at DrawerView.tsx:319)
    in RCTView (at View.js:32)
    in View (at SafeAreaProviderCompat.tsx:42)
    in SafeAreaProviderCompat (at DrawerView.tsx:318)
    in DrawerView (at createDrawerNavigator.tsx:126)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:696)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createDrawerNavigator.tsx:125)
    in DrawerNavigator (at DrawerStack.js:32)
    in Drawer (at navigators/index.js:31)
    in RCTView (at View.js:32)
    in View (at navigators/index.js:29)
    in TabBarWrapScreen (at SceneView.tsx:132)
    in StaticContainer
    in EnsureSingleNavigator (at SceneView.tsx:124)
    in SceneView (at useDescriptors.tsx:217)
    in RCTView (at View.js:32)
    in View (at DebugContainer.native.tsx:27)
    in DebugContainer (at NativeStackView.native.tsx:80)
    in MaybeNestedStack (at NativeStackView.native.tsx:319)
    in RNSScreen (at createAnimatedComponent.js:211)
    in AnimatedComponent (at createAnimatedComponent.js:264)
    in AnimatedComponentWrapper (at src/index.native.tsx:260)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:163)
    in DelayedFreeze (at src/index.native.tsx:259)
    in InnerScreen (at src/index.native.tsx:422)
    in Screen (at NativeStackView.native.tsx:236)
    in SceneView (at NativeStackView.native.tsx:360)
    in Suspender (at src/index.tsx:40)
    in Suspense (at src/index.tsx:39)
    in Freeze (at src/index.native.tsx:163)
    in DelayedFreeze (at src/index.native.tsx:177)
    in RNSScreenStack (at src/index.native.tsx:184)
    in ScreenStack (at NativeStackView.native.tsx:349)
    in NativeStackViewInner (at NativeStackView.native.tsx:420)
    in RNCSafeAreaProvider (at SafeAreaContext.tsx:87)
    in SafeAreaProvider (at SafeAreaProviderCompat.tsx:46)
    in SafeAreaProviderCompat (at NativeStackView.native.tsx:419)
    in NativeStackView (at createNativeStackNavigator.tsx:72)
    in PreventRemoveProvider (at useNavigationBuilder.tsx:696)
    in NavigationContent (at useComponent.tsx:35)
    in Unknown (at createNativeStackNavigator.tsx:71)
    in NativeStackNavigator (at navigators/index.js:71)
    in Root (at src/index.js:54)
    in QueryClientProvider (at src/index.js:52)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:430)
    in BaseNavigationContainer (at NavigationContainer.tsx:132)
    in ThemeProvider (at NavigationContainer.tsx:131)
    in NavigationContainerInner (at src/index.js:44)
    in PersistGate (at src/index.js:43)
    in Provider (at src/index.js:42)
    in App (at renderApplication.js:50)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:92)
    in RCTView (at View.js:32)
    in View (at AppContainer.js:119)
    in AppContainer (at renderApplication.js:43)
    in *****_app(RootComponent) (at renderApplication.js:60), js engine: hermes

```

```


yarn list | grep react-navigation

├─ @react-navigation/core@6.3.0
│  ├─ @react-navigation/routers@^6.1.2
├─ @react-navigation/drawer@6.3.0
│  ├─ @react-navigation/elements@^1.3.1
├─ @react-navigation/elements@1.3.6
├─ @react-navigation/material-top-tabs@6.2.3
├─ @react-navigation/native-stack@6.8.0
│  ├─ @react-navigation/elements@^1.3.5
│  ├─ @react-navigation/elements@1.3.5
├─ @react-navigation/native@6.0.12
│  ├─ @react-navigation/core@^6.3.0
├─ @react-navigation/routers@6.1.2

```

**Comment by gillicarmon** [comment]
Same error after updating RN to 72. Anyone found a solution?

**Comment by julianD77** [comment]
This may help: https://github.com/software-mansion/react-native-reanimated/issues/4420#issuecomment-1734857719

**Comment by osdnk** [comment]
Hi, 
The issue is resolved at https://github.com/software-mansion/react-native-reanimated/issues/4420#issuecomment-1734857719

**Comment by abinash101** [comment]
![Screenshot_1700671285](https://github.com/react-navigation/react-navigation/assets/127082200/ad115d98-4fc9-4eb2-9762-1394d4fe19e7)
Can anyone help on this.

**Comment by VladSt90** [comment]
Upgraded "react-native-tab-view" to "^3.4.4" and it solved

**Comment by alexandre-ducarne** [comment]
> Upgraded "react-native-tab-view" to "^3.4.4" and it solved

Anyone has a fix for version 2.16.0 ? We don't want to update to version 3 given it doesn't support tabView in ScrollView and the maintainers have decided never to

**Comment by mayank-paryani** [comment]
Hi @alexandre-ducarne did you found anything for this problem I am also on tav-view version 2.16.0 with react-navigation v6 and dont want to upgrade to version 3 given it doesn't support tabView in ScrollView.

Please help if you have any solution for this.

> > Upgraded "react-native-tab-view" to "^3.4.4" and it solved
> 
> Anyone has a fix for version 2.16.0 ? We don't want to update to version 3 given it doesn't support tabView in ScrollView and the maintainers have decided never to

**Comment by DanielWoldehana** [comment]
> > Upgraded "react-native-tab-view" to "^3.4.4" and it solved
> 
> Anyone has a fix for version 2.16.0 ? We don't want to update to version 3 given it doesn't support tabView in ScrollView and the maintainers have decided never to

Hi @alexandre-ducarne  I am also having the Same issue were you or anyone else able to solve this issue?

**Comment by kuldeep-IT** [comment]
> Same error after updating RN to 72. Anyone found a solution? Upgrading to 6x didn't solve the issue.

Did you solved while upgrading 72?

**Comment by Akarikev** [comment]
anyone solved this yet?
