### ISSUE TITLE
Inconsistent padding/margins between BottomTab and Stack header

### ISSUE THREAD

**Issue by stefan-schweiger** [react-navigation/react-navigation#11295]
### Current behavior

When using headerLeft/headerRight in the header of a BottomTab (first header) the no paddings seem to be applied to the elements. But in the header of a NativeStack (second header) some kind of padding/margin is applied. 

![5DEAFECC-605F-41F5-BBD5-EEB0D65D302D](https://user-images.githubusercontent.com/3532342/226563848-fde4de05-779e-4a9b-b4cf-d5ccc75b49d0.PNG)

### Expected behavior

The header of the BottomTab should use the same margin/padding like NativeStack.

### Reproduction

https://snack.expo.dev/@stefan-5gpay/frowning-turkish-delight

### Platform

- [X] Android
- [X] iOS
- [X] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [X] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [X] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [x] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | ^6.1.1 |
| @react-navigation/bottom-tabs          | ^6.5.2 |
| @react-navigation/native-stack         | ^6.9.7 |
| react-native-safe-area-context         | 4.4.1  |
| react-native-screens                   | ~3.18.0 |
| expo                                   | ^47.0.0 |

**Comment by stefan-schweiger** [comment]
Yes the semver resolves to the latest version were the issue still exists

**Comment by Airborn22** [comment]
Hey there! I have the same issue with

- `@react-navigation/native` version `6.1.6`
- `@react-navigation/bottom-tabs` version `6.5.7`
- `@react-navigation/native-stack` version `6.9.12`

**Comment by alrightsure** [comment]
Having this issue as well

**Comment by kaunglvlv** [comment]
Same but I'm using `expo-router` version `2.0.0`. From their [repo](https://github.com/expo/router/blob/530821d12aa52851501b99b3435359f997037399/packages/expo-router/package.json#L110), it looks like they're using the following:

```
"@react-navigation/bottom-tabs": "~6.5.7",
"@react-navigation/native": "~6.1.6",
"@react-navigation/native-stack": "~6.9.12",
```

**Comment by Robert27** [comment]
Any updates or workarounds?

**Comment by t1gu1** [comment]
Also I think it should simply remove the horizontal margin if we add a **custom headerLeft and headerRight**.
I'm saying that because it create a gap where it's simply not clickable.

**Comment by jp1987** [comment]
Having the same issue, did you find a work around @stefan-schweiger ? My only option is to render single screens in a stack navigator as well, but not sure about the performance implications.

**Comment by t1gu1** [comment]
- `@react-navigation/native-stack": "6.9.13` **<-- Works fine**
- `@react-navigation/native-stack": "6.9.14` **And more recent, got the issue**

**Comment by MuckT** [comment]
Ran into this recently and was able to adjust icon placement used in the stack navigator to match those from the tab navigator by using a negative margin: https://github.com/valora-inc/wallet/pull/5141.

```TypesScript
headerLeft: () => (
  // The negative margin is to fix an issue with margin added via the stack navigator
  <View style={{ marginLeft: -16 }}>
    <Text>Test</Text>
  </View>
)
```

**Comment by Mirthis** [comment]
Just ended up here as I'm facing the same issues. Drawer and Tabs being different positioning than Stack.
Similar to what suggest by MuckT for now I solved by wrapping `headerLeft` content with `<View style={{marginLeft: -16, marginRight: 16 }}>` (only removing left margin was causing the title in the header to get misaligned reason why I added the same margin to the right)

**Comment by Mirthis** [comment]
The header button show in the exact position as in the other screens after applying the margins and I haven't noticed any problem tapping it (I've only tested that on the emulator and one physical device for now).

**Comment by CalNicklin** [comment]
This is absolutely still a bug. Applying specific margin to icons on one stack doesn't fix the issue for all devices. For example, I set margins of 16 on the headerLeft + headerRight which works on Android and smaller iOS, but on e.g. iPhone 15 Pro Max it doesn't fix it. I guess it's something to do with the horizontal insets? I've tried to patch the native Header components but can't get it to work.

**Comment by busybox11** [comment]
If anyone has an update on this, it would be highly appreciated.

This might be wrong. I'm using a nested Stack navigator inside a Tabs navigator, in order to have different tab-level stack nav with an individual header back button for each tab stack.
All screens that don't have nested Stack navs have the correct amount of margin, but the ones that do do indeed have 16px more.

**Comment by busybox11** [comment]
I just realised they also don't have the same shadow intensity.
<img width="368" alt="image" src="https://github.com/react-navigation/react-navigation/assets/29630035/64373718-775c-4e33-9448-5aea2ffe32c1">
<img width="373" alt="image" src="https://github.com/react-navigation/react-navigation/assets/29630035/af6e5e52-ac1e-42bb-8335-b5bc6919b06a">

**Comment by joseph-kh** [comment]
i am using expo-router latest version and this issue is happening too.

Headers are inconsistent between Tab and Stack layouts.

As you can see stack headers (auth), (tabs) contain some shadow, unlike Tabs header (wallet)

Another issue is happening too, in stack header you can only style `backgroundColor` in `headerStyle`, meanwhile on Tab header you can style `headerStyle` with whatever you want. it doesn't make a lot of sense

![image](https://github.com/user-attachments/assets/35ef8aa5-0b2b-4035-bddb-41d484de7b0f)

**Comment by aimz-yeah** [comment]
In case anyone is suffering with this problem and finding that even with margins added things are still incredibly inconsistent cross-platform, or have concerns that this solution is hacky, my solution was to simply just never use tab headers.

![Image](https://github.com/user-attachments/assets/f2cc778d-4a9a-4652-8924-acb62d7f6f15)

In Tabs.Screen set headerShown to false. Link to a nested route with a _layout.tsx file.

```
<Tabs.Screen name="messages" options={{ headerShown: false }} />
```

In the nested layout (`messages/layout.tsx`) use <Stack.screen/> linking to the index.tsx component where the route is.

```
<Stack screenOptions={...}>
    <Stack.Screen name="index" options={{ headerShown: true }} />
</Stack>
```

Do this for every tab header. Quite annoying but seems to 'fix' the immediate problem.

**Comment by MarvinVrdoljak** [comment]
I was turning off all the default headers and inserted my own CustomHeader:

```
import React from 'react'
import {View, Text, StyleSheet, TouchableOpacity} from 'react-native'
import {ArrowLeft} from 'lucide-react-native'
import globalStyles from '@/styles/globalStyles'
import {router} from 'expo-router'

// Define props type
interface CustomHeaderProps {
  title?: string
  defaultBackLink?: string
  headerRight?: React.ReactNode
}

const CustomHeader: React.FC<CustomHeaderProps> = ({title, defaultBackLink, headerRight}) => {
  return (
    <View style={styles.header}>
      <View style={styles.headerLeft}>
        {defaultBackLink && (
          <TouchableOpacity
            onPress={() => {
              if (router.canGoBack()) {
                router.back()
              } else {
                router.push(defaultBackLink as any)
              }
            }}>
            <ArrowLeft size={24} color={globalStyles.textColor} />
          </TouchableOpacity>
        )}
      </View>
      {title && <Text style={styles.headerText}>{title}</Text>}
      <View style={styles.headerRight}>{headerRight && headerRight}</View>
    </View>
  )
}

const styles = StyleSheet.create({
  header: {
    width: '100%',
    backgroundColor: globalStyles.backgroundColor,
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingTop: 60, // Adjust for status bar
    flexDirection: 'row',
    paddingBottom: 10,
  },
  headerText: {
    color: globalStyles.textColor,
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerLeft: {
    width: 50,
    marginLeft: globalStyles.containerSidePadding,
  },
  headerRight: {
    marginRight: globalStyles.containerSidePadding,
    width: 50,
    alignItems: 'flex-end',
  },
})

export default CustomHeader

```

**Comment by sampie777** [comment]
I've got the same inconsistency, but with the vertical alignment of `headerRight` (using ```navigation.setOptions({ headerRight: () => ...``` in a `useLayoutEffect` hook. 
It appears that on iPhone only I need to add `top: -10` to the style. 

<img width="691" height="524" alt="Image" src="https://github.com/user-attachments/assets/206f2c13-fecf-4497-8dee-82a0164ebbad" />

I'm running the latest versions: 
```
# package.json
...
    "@react-navigation/bottom-tabs": "7.4.7",
    "@react-navigation/native": "7.1.17",
    "@react-navigation/native-stack": "7.3.26",
...
    "react": "19.1.0",
    "react-native": "0.81.4",
...
```

**Comment by jamalx31** [comment]
Its funny that this is still an issue after all this time.
the only solution I found is to explicitly control header padding

```
headerLeftContainerStyle: {
  paddingLeft: 16,
},
headerRightContainerStyle: {
  paddingRight: 16,
},
```

**Comment by dillonbonk** [comment]
Well that was a fun rabbit hole to go down. First time playing with expo layout and thought I was missing something. Can confirm adjusting padding on Tabs like @jamalx31 did is the only way to fix this. If you need to update spacing using a Stack, wrap your headerLeft and headerRight in a View and style with left and right

`
<View style={{ left: -16 }}>
`
