### ISSUE TITLE
Drawer Navigator not navigating to screen in android.

### ISSUE THREAD

**Issue by neeteshraj** [react-navigation/react-navigation#11405]
### Current behavior

Drawer navigator is not navigating to the screens in android. In case of ios it is working fine. In case of android the onPress function inside the custom drawer navigator is not being triggered. I tried to implement it without using custom drawer. Even there it is not being navigated to another screen.
![Screenshot_20230607_211010_MBL](https://github.com/react-navigation/react-navigation/assets/37995777/f45ee9f9-4e96-4963-928c-7b1a011aa680)

```
import React from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import { DrawerContentScrollView } from '@react-navigation/drawer';
import { useNavigation } from '@react-navigation/native';

interface CustomDrawerProps {
    state: any;
    navigation: any;
}

const CustomDrawer: React.FC<CustomDrawerProps> = ({ state, navigation }) => {
    const navigate  = useNavigation();

    const handleNavigation = (route: string) => {
        navigation.closeDrawer();
        console.log("I am here")
        navigate.navigate(route)
    };

    return (
        <DrawerContentScrollView>
            {state.routeNames.map((route: string, index: number) => (
                <TouchableOpacity
                    key={index}
                    style={styles.drawerItem}
                    onPress={() => handleNavigation(route)}
                >
                    <Text style={styles.drawerItemText}>{route}</Text>
                </TouchableOpacity>
            ))}
        </DrawerContentScrollView>
    );
};

const styles = StyleSheet.create({
    drawerItem: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#EAEAEA',
    },
    drawerItemText: {
        fontSize: 16,
        color: '#000',
    },
});

export default CustomDrawer;
```

### Expected behavior

I am expecting to navigate to screens mentioned in the drawer navigator. In case of ios it is working fine. But in android. It is not navigating to screens.

### Reproduction

https://snack.expo.dev/@neeteshraj/mbl

### Platform

- [X] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [X] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.6
| @react-navigation/bottom-tabs          |^6.5.7
| @react-navigation/drawer               |^6.6.2
| @react-navigation/stack                |^6.3.16
| @react-navigation/native-stack         |^6.9.12
| react-native-safe-area-context         |^4.5.3
| react-native-screens                   |^3.2.0
| react-native-gesture-handler           |^2.10.0
| react-native-reanimated                |3.0.2
| react-native                           |0.71.8
| node                                   |18.12.0
| npm or yarn                            | 3.6.0

**Comment by kambie10** [comment]
I have the same problem with the react-native-gesture-handler 2.11.0 & react-native-reanimated 3.2.0 library upgrade, is there a solution to fix it?

**Comment by matiasim** [comment]
I have the same issue with `react-native-gesture-handler 2.10.2` and `react-native-reanimated 3.0.2`

**Comment by rohanps630** [comment]
I have the same issue with the `react-native-gesture-handler2.9.0` & `react-native-reanimated 3.0.2`

**Comment by surbhidavara99** [comment]
In my case, I am not able to open a drawer on click of the hamburger Icon, it's getting a white screen with `react-native-reanimated": "^3.2.0` & `react-native-gesture-handler": "^2.10.1`

**Comment by surbhidavara99** [comment]
I have downgraded the package `react-native-reanimated": "3.1.0` and it worked

**Comment by kambie10** [comment]
> I have downgraded the package `react-native-reanimated": "3.1.0` and it worked

thanks... it worked for me...

**Comment by whiteHatCip** [comment]
Having the same issue with react-native-reanimated: 3.2.0. using version 3.1.0 seems to solve the issue.
It would happen on iOS too, by the way.

**Comment by kacperkapusciak** [comment]
The issue should be now resolved in `react-native-reanimated` v3.3.0 🎉 

Upgrade this dependency in your project and it should work just fine

Cheers ✌️

**Comment by Koxx3** [comment]
I have the same issue even with react-native-reanimated v3.3.0.
I am using newArchitecture ... no idea if this can be an issue

**Comment by Code-Divine** [comment]
This is still happening

"dependencies": {
    "@react-navigation/drawer": "^7.0.19",
    "@react-navigation/native": "^7.0.13",
    "@react-navigation/native-stack": "^7.1.14",
    "expo": "~52.0.17",
    "expo-status-bar": "~2.0.0",
    "react": "18.3.1",
    "react-hook-form": "^7.54.0",
    "react-native": "0.76.3",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "4.12.0",
    "react-native-screens": "~4.1.0"
  },
