### ISSUE TITLE
Drawer.Navigator not working perfectly with React 0.76.5 android platform

### ISSUE THREAD

**Issue by TonyFTannous-Byd** [react-navigation/react-navigation#12370]
### Current behavior

My react native app was in react native 0.75.4, react navigation v6.x and it work perfectly.  when i upgrade it to version 0.76.5, when i logout and navigate to login screen (another Stack.Navigator with one screen which is login screen) from a Stack.Navigator (with many screens), the first screen is a drawer navigation i have an error:
Cannot remove child at index 0 from parent ViewGroup [944], only 1 children in parent.
Warnning: childCount may be incorrect
![Image](https://github.com/user-attachments/assets/a3532fe4-33bd-45b5-9539-d38031401292)

### Expected behavior

should i can switch to the Stack.Navigator that contain the login without any error

### Reproduction

https://github.com/react-navigation/react-navigation/issues/new?q=0.76&template=bug-report.yml

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [x] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               |
| @react-navigation/bottom-tabs          |
| @react-navigation/drawer               |
| @react-navigation/material-top-tabs    |
| @react-navigation/stack                |
| @react-navigation/native-stack         |
| react-native-drawer-layout             |
| react-native-tab-view                  |
| react-native-screens                   |
| react-native-safe-area-context         |
| react-native-gesture-handler           |
| react-native-reanimated                |
| react-native-pager-view                |
| react-native                           |
| expo                                   |
| node                                   |
| npm or yarn                            |

**Comment by TonyFTannous-Byd** [comment]
"@fortawesome/fontawesome-svg-core": "^6.7.1",
    "@fortawesome/free-brands-svg-icons": "^6.7.1",
    "@fortawesome/free-regular-svg-icons": "^6.7.1",
    "@fortawesome/free-solid-svg-icons": "^6.7.1",
    "@fortawesome/react-native-fontawesome": "^0.3.2",
    "@gorhom/bottom-sheet": "^4.6.4",
    "@react-native-async-storage/async-storage": "^2.1.0",
    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/bottom-tabs": "^6.6.1",
    "@react-navigation/drawer": "^6.7.2",
    "@react-navigation/native": "^6.1.18",
    "@react-navigation/native-stack": "^6.11.0",
    "@reduxjs/toolkit": "^2.2.7",
    "axios": "^1.7.4",
    "dayjs": "^1.11.12",
    "i": "^0.3.7",
    "jwt-decode": "^4.0.0",
    "npm": "^10.8.2",
    "patch-package": "^8.0.0",
    "react": "18.3.1",
    "react-native": "^0.76.5",
    "react-native-biometrics": "^3.0.1",
    "react-native-bootsplash": "^6.1.1",
    "react-native-chart-kit": "^6.12.0",
    "react-native-config": "^1.5.3",
    "react-native-crypto-js": "^1.0.0",
    "react-native-device-info": "^14.0.0",
    "react-native-gesture-handler": "^2.20.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-popup-menu": "^0.16.1",
    "react-native-reanimated": "^3.16.1",
    "react-native-root-toast": "^3.6.0",
    "react-native-safe-area-context": "^4.10.9",
    "react-native-screens": "^3.34.0",
    "react-native-svg": "^15.5.0",
    "react-native-ui-datepicker": "^2.0.4",
    "react-redux": "^9.1.2",
    "redux-persist": "^6.0.0"

**Comment by TonyFTannous-Byd** [comment]
solved, by upgrade react-native-screens to 4.4.0

**Comment by TonyFTannous-Byd** [comment]
Solved by upgrade react-native-screens to 4.4.0

**Comment by akshSekhon** [comment]
@TonyFTannous-Byd my react-native-screens  version is "^4.6.0" . but still facing this error, have you found any solution, please help me

**Comment by TonyFTannous-Byd** [comment]
it should work, when i update react-native-screen to 4.4.0 + it work normaly
Note: my app is created without a framework (it is not expo, it is CLI)

**Comment by DoHue97** [comment]
> I'm having the same error with no framework + RN 0.76.7 and:
> 
> ```
>     "@react-navigation/bottom-tabs": "^7.2.1",
>     "@react-navigation/native": "^7.0.15",
>     "@react-navigation/native-stack": "^7.2.1",
>     "react-native-screens": "^4.9.1",
> ```

Hi do you have any solution (expect downgrade react-native-screens)?
