### ISSUE TITLE
Material Top Tabs is very unstable when screens contains lists inside

### ISSUE THREAD

**Issue by aik117** [react-navigation/react-navigation#12493]
### Current behavior

Hi,
I am using Material Top Tabs v 6.6.14, i have a dynamic tab navigator that can contain as much tabs as possible, where the lists item contains separate graphs. I am also hiding tabs label and updating the title of the screen when a tab is swiped. The first problem is when i swipe the tab, the screen title update is very slow. I checked the focus event in the listener where i wanted to update the tab title but the focus event inside listeners is being called after some delay. Also when i quickly swipe between tabs, the tabs start weird behavior and jumping between every tab infinitely. Can someone please help on this, i have spent so much time on this and couldn't find a way to solve.

This is my dynamic tab navigator

        `import React, { useEffect, useState } from 'react';
        import { Dimensions, StyleSheet, Text, View } from 'react-native'
        import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
        import { getFocusedRouteNameFromRoute, useNavigation } from '@react-navigation/native';
        import WidgetsContainer from './WidgetsContainer';
        import { useSelector } from 'react-redux';
        import TextWrapper from './TextWrapper';
        import LoaderKit from 'react-native-loader-kit';
        import { colorStyles } from '../css/AppStyles';
        
        const Tab = createMaterialTopTabNavigator();

        const UserTabs = (props) => {
      	//console.log("props", props);
      	const navigation = useNavigation();
      	const { setFocusedTabDetails, parentNavigation, removeItem } = props;

	const tabsAndWidgets = useSelector((state) => state.userTabsAndWidgetsReducer.userTabsAndWidgets);

	const getHeaderTitle = (route) => {
		console.log("route", route);
		// If the focused route is not found, we need to assume it's the initial screen
		// This can happen during if there hasn't been any navigation inside the screen
		// In our case, it's "Feed" as that's the first screen inside the navigator
		//const routeName = getFocusedRouteNameFromRoute(route);
		//console.log("routeName", routeName);
		return route.name;
	}

	return (
		<Tab.Navigator 
			initialRouteName={'Home'} 
			screenOptions={{ 
				tabBarStyle: { display: "none" }, 
				lazy: true,
				lazyPlaceholder: () => 
					<View style={styles.lazyPlaceHolderStyle}>
						<LoaderKit
							style={styles.loaderStyle}
							name={'BallSpinFadeLoader'}
							color={colorStyles.headerColor}
						/>
						<TextWrapper style={{color: colorStyles.headerColor}}>Loading...\nPlease wait</TextWrapper>
					</View>
			}}>
			{ 
				tabsAndWidgets?.map((tab, index) =>
					<Tab.Screen 
						key={index} 
						name={tab?.tabName}
						listeners={{
							blur: (e) => {
								//console.log("tab blurred");
							},
							tabPress: e => console.log('Tab press', e.target),
							focus: (e) => {
								//parentNavigation.setParams({ showDeleteButton: tab.systemTab ? false : true });
								//parentNavigation.setOptions({ headerTitle: tab.tabName });
								//setFocusedTabDetails({ tabID: tab.tabID, "tabName": tab.tabName, "tabIndex": index, "systemTab": tab.systemTab });
								//console.log('Tab focus', e)
							},
							swipeStart: (e) => {
								//console.log("swipe start called", e);
							},
							swipeEnd: (e) => {
								//console.log("swipe end called", e);
							},
						}}
					>
						{ props =>
							<WidgetsContainer 
								{...props} 
								extraParams = {{ 
									"tabDetails": tab, 
									"tabIndex": index, 
									"parentNavigation": parentNavigation, 
									"setFocusedTabDetails": setFocusedTabDetails,
									"removeItem": removeItem
								}} 
							/>
						}
					</Tab.Screen>
				)
			}
		</Tab.Navigator>
	);
        }

        const styles = StyleSheet.create({
        	lazyPlaceHolderStyle: {
        		flex: 1,
        		flexDirection: "row",
        		justifyContent: "center",
        		alignItems: "center"
        	},
        	loaderStyle: {
        		width: 40,
        		height: 40,
        		marginHorizontal: 10
        	},
        });
        
        export default UserTabs;`

and this is the code where i update the screen title inside useEffect function

        `const isFocused = useIsFocused();
        	useEffect(() => {
        		console.log("isFocused");
        		if (isFocused) {
        			// console.log("extraparams", extraParams.tabDetails);
        			const tab = extraParams.tabDetails;
        			const tabIndex = extraParams.tabIndex;
        			extraParams.setFocusedTabDetails({ tabID: tab.tabID, "tabName": tab.tabName, "tabIndex": tabIndex, "systemTab": tab.systemTab });
        			//setLoading({load: true, loadingText: "Populating Widgets...\nPlease wait."});
        			//setTimeout(() => setLoading({load: false, loadingText: ""}), 2000);
        			//navigation.setOptions({ swipeEnabled: false });
        			//setTimeout(() => navigation.setOptions({ swipeEnabled: true }), 2000);
        		}
        	}, [isFocused]);`

The title update and tabs jumping becomes much worse when more tabs are added. Also is there a way that we can know when a tab is fully rendered so until then we can atleast limit the user from quickly swiping back and forth? Please advise. Thanks.

### Expected behavior

The tabs should behave fast and responsive when swiped

### Reproduction

not available

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/drawer
- [x] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack

### Environment

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 6.1.18
| @react-navigation/drawer               | 6.7.2
| @react-navigation/material-top-tabs    | 6.6.14
| @react-navigation/stack                | 6.4.1
| react-native-screens                   | 3.29.0
| react-native-safe-area-context         | 4.10.8
| react-native-gesture-handler           | 2.18.0
| react-native-reanimated                | 3.14.0
| react-native-pager-view                | 6.4.1
| react-native                           | 0.74.5

**Comment by santhosh-umapathi-wikifolio** [comment]
+ 1, similar issue

https://github.com/user-attachments/assets/eeae43cd-ddc0-4389-8684-74f0137795e1

**Comment by santhosh-umapathi-wikifolio** [comment]
Still issue is present

**Comment by hugohutri** [comment]
I am facing the same issue as in the video. When swiping the tab pages, the indicator initially moves to the correct place, but then bounces a bit back (same thing as in the video)

Versions:
"@react-navigation/material-top-tabs": "7.2.12",
"react-native": "0.79.2",
New arch enabled

**Comment by ya-s-u** [comment]
same here

**Comment by sttaseen** [comment]
Would be nice to have a fix for this

**Comment by ENoLTC** [comment]
same here. When swiping the tab pages, the indicator initially moves to the correct place, but then bounces a bit back (same thing as in the video)

Versions:
"@react-navigation/material-top-tabs": "7.3.2",
"react-native": "0.79.4",
New arch enabled

**Comment by AlexCernik** [comment]
The temporary solution seems to be to add swipeEnabled: false or test  #12664

**Comment by sttaseen** [comment]
> The temporary solution seems to be to add swipeEnabled: false.
> 
> **Update** Can you test if this works? [#12664](https://github.com/react-navigation/react-navigation/pull/12664)

This disables the swipe but even then, the top tabs is still unstable. 

Clicking on a tab makes it go to that tab and then do a quick back and forth (as seen in the video). Is there a way to apply the offset fix that you have in the PR for material-top-tabs? (Thanks for helping with the PR!)

https://github.com/user-attachments/assets/7511a685-6b6b-4be2-9b23-b339208e491c

**Comment by AlexCernik** [comment]
@sttaseen Have you also tried with swipeEnabled: true?, this PR only work with swipe.

**Comment by sttaseen** [comment]
> [@sttaseen](https://github.com/sttaseen) Have you also tried with swipeEnabled: true?, this PR only work with swipe.

Yup, I just tried it. The bug is still there. It seems like it only occurs when you have multiple tabs that contain lists.

**EDIT:** The `swipeEnable=false` doesn't work but adding `offset.setValue(0);` (from your [PR](https://github.com/react-navigation/react-navigation/pull/12664)) to `react-native-tab-view/lib/module/PagerViewAdapter.js` seems to do the trick! I am doing the patch-package now to keep it. Thanks @AlexCernik!

**Comment by qqiwi92** [comment]
Same here. So the solution is to disable the swiping? That kinda defeats the whole purpose...

**Comment by AlexCernik** [comment]
> Same here. So the solution is to disable the swiping? That kinda defeats the whole purpose...

Hi, try add this [PR](https://github.com/react-navigation/react-navigation/pull/12664)

**Comment by santhosh-umapathi-wikifolio** [comment]
Solution was to render Custom Top tabs

```
const MaterialTopTabs = ({
  state,
  position,
  ...rest
}: MaterialTopTabBarProps) => {
  return (
    <View style={styles.container}>
      {state.routes.map((route, index) => (
        <MaterialTopTab
          key={route.name}
          {...{state, position, index, route}}
          {...rest}
        />
      ))}
      <MaterialTabIndicator {...{state, position}} />
    </View>
  );
};
```


```
const MaterialTabIndicator = ({state, position}: TProps) => {
  const {animatedStyle} = useController({state, position});

  return <Animated.View style={[styles.tabBarIndicatorStyle, animatedStyle]} />;
};
```

```
 <TabNavigator.Navigator
      tabBar={MaterialTopTabs}
```

**Comment by skry17** [comment]
I am also facing the same issue

**Comment by adel121** [comment]
Facing same issue

**Comment by swey** [comment]
Same problem here. 
- Navigating via Tab Bar / Code works fine
- `position` has the right value while swiping
- As soon the screens fully transitioned after swiping, the `position` gets a wrong value

**Comment by AlexCernik** [comment]
> Same problem here.
> 
> * Navigating via Tab Bar / Code works fine
> * `position` has the right value while swiping
> * As soon the screens fully transitioned after swiping, the `position` gets a wrong value

Hi, try add this [PR](https://github.com/react-navigation/react-navigation/pull/12664)

**Comment by devansh-enclave** [comment]
> I am facing the same issue as in the video. When swiping the tab pages, the indicator initially moves to the correct place, but then bounces a bit back (same thing as in the video)
> 
> Versions: "@react-navigation/material-top-tabs": "7.2.12", "react-native": "0.79.2", New arch enabled

Hey where you able to get a fix for this or any other library for the same ?

**Comment by santhosh-umapathi-wikifolio** [comment]
Hi, Any updates on this issue. Still its not resolved. Kindly look into this when you have some free time

**Comment by gentil-kadson** [comment]
Still won't work

**Comment by EricB84300** [comment]
Hi it still does not work event with the last updates.
does anyone have a workaround if the bug is not fix ?

**Comment by AlexCernik** [comment]
> Hi it still does not work event with the last updates.
> does anyone have a workaround if the bug is not fix ?

Hi, To test the fix [PR](https://github.com/react-navigation/react-navigation/pull/12664), update `react-native-tab-view/lib/module/PagerViewAdapter.js` with the proposed solution.

**Comment by EricB84300** [comment]
Thx @AlexCernik  I will try that

**Comment by santhosh-umapathi-wikifolio** [comment]
> > Hi it still does not work event with the last updates.
> > does anyone have a workaround if the bug is not fix ?
> 
> Hi, To test the fix [PR](https://github.com/react-navigation/react-navigation/pull/12664), update `react-native-tab-view/lib/module/PagerViewAdapter.js` with the proposed solution.

As mentioned in the comments of that proposed fix, it does not work as well. https://github.com/react-navigation/react-navigation/pull/12664#issuecomment-3370475706

**Comment by santhosh-umapathi-wikifolio** [comment]
> Thx [@AlexCernik](https://github.com/AlexCernik) I will try that

you can give it a try, but a lot already did and it does not work as well - https://github.com/react-navigation/react-navigation/pull/12664#issuecomment-3370475706

**Comment by EricB84300** [comment]
This problem is still present and all the infos seems to have been provided
so please don't close it

**Comment by EricB84300** [comment]
This problem is still present and all the infos seems to have been provided
so please don't close it

**Comment by iyosayi0x** [comment]
I'm facing a similar issue with the tab bar glitching when I switch between screens, its snaps back for a bit before snapping back forward

**Comment by NJneeraj** [comment]
Similar Issue

**Comment by troZee** [comment]
It has been fixed here https://github.com/react-navigation/react-navigation/pull/12664 

Please test this version of pager https://github.com/callstack/react-native-pager-view/releases/tag/v8.0.1

**Comment by EricB84300** [comment]
@troZee  the problem is still present

**Comment by AlexCernik** [comment]
@troZee Hi, the problem persists on Samsung Galaxy J8 (Android 10)

**Comment by EricB84300** [comment]
the problem is still present

**Comment by iyosayi0x** [comment]
I got tired of waiting for a fix that works with expo router, so I built something minimal for my use case with react native pager view + react native reanimated

```tsx
import { BRAND_COLORS, GREY_COLORS } from "@/lib/constants/colors";
import { ReactNode, useRef, useState } from "react";
import { InteractionManager, Pressable, View } from "react-native";
import PagerView, { PagerViewOnPageScrollEvent } from "react-native-pager-view";
import Animated, {
  SharedValue,
  interpolateColor,
  useAnimatedStyle,
  useDerivedValue,
  useSharedValue,
} from "react-native-reanimated";

/**
 * types
 */
type PageConfig = {
  title: string;
  component: ReactNode;
};

type PageScrollState = "idle" | "dragging" | "settling";

interface IProps {
  pages: PageConfig[];
  initialPage?: number;
  onPageChange?: (index: number) => void;
  onPageScrollStateChanged?: (state: PageScrollState) => void;
  scrollEnabled?: boolean;
}

export default function CustomPagerView({
  pages,
  initialPage = 0,
  onPageChange,
  onPageScrollStateChanged,
  scrollEnabled = true,
}: IProps) {
  /**
   * refs
   */
  const pagerRef = useRef<PagerView>(null);

  /**
   * shared values - single source of truth for "where between pages are we"
   */
  const progress = useSharedValue(initialPage);
  const [containerWidth, setContainerWidth] = useState(0);
  const tabWidth = useDerivedValue(() =>
    pages.length > 0 ? containerWidth / pages.length : 0,
  );

  /**
   * state — pages mount lazily: only render a page once it has been visited
   * (or swiped toward), then keep it mounted so revisits don't refetch. This
   * keeps off-screen tabs — and their network requests — out of first paint.
   */
  const [visitedPages, setVisitedPages] = useState<Set<number>>(
    () => new Set([initialPage]),
  );

  /**
   * methods
   */
  const markVisited = (index: number) => {
    setVisitedPages((prev) => {
      if (prev.has(index)) return prev;
      const next = new Set(prev);
      next.add(index);
      return next;
    });
  };

  const handlePageScroll = (e: PagerViewOnPageScrollEvent) => {
    const { position, offset } = e.nativeEvent;
    progress.value = position + offset;
  };

  const goToPage = (index: number) => {
    pagerRef.current?.setPage(index);
  };

  /**
   *
   * Mount a page's content only after its transition has fully settled, so the
   * heavy first render never competes with the swipe/tab animation. The page
   * shows empty for the tail of the slide, then fills in (with its own
   * skeletons) — keeping the gesture itself smooth.
   */

  const handlePageSelected = (index: number) => {
    InteractionManager.runAfterInteractions(() => markVisited(index));
    onPageChange?.(index);
  };

  /**
   * computed
   */
  const indicatorStyle = useAnimatedStyle(() => ({
    width: tabWidth.value,
    transform: [{ translateX: progress.value * tabWidth.value }],
  }));

  return (
    <View className="flex-1">
      {/* Tab row */}
      <View
        className="flex-row border-b border-grey-100 relative"
        onLayout={(e) => {
          setContainerWidth(e.nativeEvent.layout.width);
        }}
      >
        {pages.map((page, i) => (
          <TabLabel
            key={page.title}
            label={page.title}
            index={i}
            progress={progress}
            onPress={() => goToPage(i)}
          />
        ))}
        <Animated.View
          className="absolute bottom-0 h-[2px] bg-brand-700"
          style={indicatorStyle}
        />
      </View>

      {/* Pages */}
      <PagerView
        ref={pagerRef}
        initialPage={initialPage}
        onPageScroll={handlePageScroll}
        onPageSelected={(e) => handlePageSelected(e.nativeEvent.position)}
        onPageScrollStateChanged={(e) =>
          onPageScrollStateChanged?.(e.nativeEvent.pageScrollState)
        }
        scrollEnabled={scrollEnabled}
        style={{ flex: 1 }}
      >
        {pages.map((page, i) => (
          <View key={page.title} style={{ flex: 1 }}>
            {visitedPages.has(i) ? page.component : null}
          </View>
        ))}
      </PagerView>
    </View>
  );
}

function TabLabel({
  label,
  index,
  progress,
  onPress,
}: {
  label: string;
  index: number;
  progress: SharedValue<number>;
  onPress: () => void;
}) {
  const textStyle = useAnimatedStyle(() => {
    const distance = Math.min(Math.abs(progress.value - index), 1);
    return {
      color: interpolateColor(
        distance,
        [0, 1],
        [BRAND_COLORS[700], GREY_COLORS[250]],
      ),
    };
  });

  return (
    <Pressable className="flex-1 py-4" onPress={onPress}>
      <Animated.Text
        style={[
          textStyle,
          { textAlign: "center", fontFamily: "DMSans-SemiBold" },
        ]}
      >
        {label}
      </Animated.Text>
    </Pressable>
  );
}

```

#### Sample Usage 
```tsx
  <CustomPagerView
    pages={[
      {
        title: "All",
        component: <VibeScreen type="all" />,
      },
      {
        title: "Photos",
        component: <VibeScreen type="photos" />,
      },
      {
        title: "Videos",
        component: <VibeScreen type="videos" />,
      },
    ]}
  />
```

Hope this helps ❤️

**Comment by EricB84300** [comment]
> I got tired of waiting for a fix that works with expo router, so I built something minimal for my use case with react native pager view + react native reanimated
> 
> import { BRAND_COLORS, GREY_COLORS } from "@/lib/constants/colors";
> import { ReactNode, useRef, useState } from "react";
> import { InteractionManager, Pressable, View } from "react-native";
> import PagerView, { PagerViewOnPageScrollEvent } from "react-native-pager-view";
> import Animated, {
>   SharedValue,
>   interpolateColor,
>   useAnimatedStyle,
>   useDerivedValue,
>   useSharedValue,
> } from "react-native-reanimated";
> 
> /**
>  * types
>  */
> type PageConfig = {
>   title: string;
>   component: ReactNode;
> };
> 
> type PageScrollState = "idle" | "dragging" | "settling";
> 
> interface IProps {
>   pages: PageConfig[];
>   initialPage?: number;
>   onPageChange?: (index: number) => void;
>   onPageScrollStateChanged?: (state: PageScrollState) => void;
>   scrollEnabled?: boolean;
> }
> 
> export default function CustomPagerView({
>   pages,
>   initialPage = 0,
>   onPageChange,
>   onPageScrollStateChanged,
>   scrollEnabled = true,
> }: IProps) {
>   /**
>    * refs
>    */
>   const pagerRef = useRef<PagerView>(null);
> 
>   /**
>    * shared values - single source of truth for "where between pages are we"
>    */
>   const progress = useSharedValue(initialPage);
>   const [containerWidth, setContainerWidth] = useState(0);
>   const tabWidth = useDerivedValue(() =>
>     pages.length > 0 ? containerWidth / pages.length : 0,
>   );
> 
>   /**
>    * state — pages mount lazily: only render a page once it has been visited
>    * (or swiped toward), then keep it mounted so revisits don't refetch. This
>    * keeps off-screen tabs — and their network requests — out of first paint.
>    */
>   const [visitedPages, setVisitedPages] = useState<Set<number>>(
>     () => new Set([initialPage]),
>   );
> 
>   /**
>    * methods
>    */
>   const markVisited = (index: number) => {
>     setVisitedPages((prev) => {
>       if (prev.has(index)) return prev;
>       const next = new Set(prev);
>       next.add(index);
>       return next;
>     });
>   };
> 
>   const handlePageScroll = (e: PagerViewOnPageScrollEvent) => {
>     const { position, offset } = e.nativeEvent;
>     progress.value = position + offset;
>   };
> 
>   const goToPage = (index: number) => {
>     pagerRef.current?.setPage(index);
>   };
> 
>   /**
>    *
>    * Mount a page's content only after its transition has fully settled, so the
>    * heavy first render never competes with the swipe/tab animation. The page
>    * shows empty for the tail of the slide, then fills in (with its own
>    * skeletons) — keeping the gesture itself smooth.
>    */
> 
>   const handlePageSelected = (index: number) => {
>     InteractionManager.runAfterInteractions(() => markVisited(index));
>     onPageChange?.(index);
>   };
> 
>   /**
>    * computed
>    */
>   const indicatorStyle = useAnimatedStyle(() => ({
>     width: tabWidth.value,
>     transform: [{ translateX: progress.value * tabWidth.value }],
>   }));
> 
>   return (
>     <View className="flex-1">
>       {/* Tab row */}
>       <View
>         className="flex-row border-b border-grey-100 relative"
>         onLayout={(e) => {
>           setContainerWidth(e.nativeEvent.layout.width);
>         }}
>       >
>         {pages.map((page, i) => (
>           <TabLabel
>             key={page.title}
>             label={page.title}
>             index={i}
>             progress={progress}
>             onPress={() => goToPage(i)}
>           />
>         ))}
>         <Animated.View
>           className="absolute bottom-0 h-[2px] bg-brand-700"
>           style={indicatorStyle}
>         />
>       </View>
> 
>       {/* Pages */}
>       <PagerView
>         ref={pagerRef}
>         initialPage={initialPage}
>         onPageScroll={handlePageScroll}
>         onPageSelected={(e) => handlePageSelected(e.nativeEvent.position)}
>         onPageScrollStateChanged={(e) =>
>           onPageScrollStateChanged?.(e.nativeEvent.pageScrollState)
>         }
>         scrollEnabled={scrollEnabled}
>         style={{ flex: 1 }}
>       >
>         {pages.map((page, i) => (
>           <View key={page.title} style={{ flex: 1 }}>
>             {visitedPages.has(i) ? page.component : null}
>           </View>
>         ))}
>       </PagerView>
>     </View>
>   );
> }
> 
> function TabLabel({
>   label,
>   index,
>   progress,
>   onPress,
> }: {
>   label: string;
>   index: number;
>   progress: SharedValue<number>;
>   onPress: () => void;
> }) {
>   const textStyle = useAnimatedStyle(() => {
>     const distance = Math.min(Math.abs(progress.value - index), 1);
>     return {
>       color: interpolateColor(
>         distance,
>         [0, 1],
>         [BRAND_COLORS[700], GREY_COLORS[250]],
>       ),
>     };
>   });
> 
>   return (
>     <Pressable className="flex-1 py-4" onPress={onPress}>
>       <Animated.Text
>         style={[
>           textStyle,
>           { textAlign: "center", fontFamily: "DMSans-SemiBold" },
>         ]}
>       >
>         {label}
>       </Animated.Text>
>     </Pressable>
>   );
> }
> #### Sample Usage
>   <CustomPagerView
>     pages={[
>       {
>         title: "All",
>         component: <VibeScreen type="all" />,
>       },
>       {
>         title: "Photos",
>         component: <VibeScreen type="photos" />,
>       },
>       {
>         title: "Videos",
>         component: <VibeScreen type="videos" />,
>       },
>     ]}
>   />
> Hope this helps ❤️

thx
I am tired too and even wondering to stop use it....
maybe we will try you solution

**Comment by EricB84300** [comment]
the issues is still present.

**Comment by EricB84300** [comment]
the issues is still present.
If someone could solve it would be apreciated
