### ISSUE TITLE
[Bug]: Bottom sheet causes layout shift or extra bottom padding when navigating from headerless to headered screen (New Architecture)

### ISSUE THREAD

**Issue by azizbecha** [react-navigation/react-navigation#12559]
### Version
v7

### Reanimated Version
v3

### Gesture Handler Version
v2

### Platforms
Android

When using @gorhom/bottom-sheet with the latest version, react-navigation, and the new architecture enabled in React Native, navigating from a screen with headerShown: false to a screen with headerShown: true causes an empty space/padding to appear at the bottom of the screen.

This issue does not occur in the old architecture. Seems like a layout/styling conflict between BottomSheet, screen transitions, and safe area calculations in the new architecture.

I already made sure that my app is wrapped by GestureHandlerRootView and flex: 1

This issue appeared after upgrading to the latest versions.

### 🔧 Environment
"@gorhom/bottom-sheet": "5.1.2",
"@react-navigation/native": "7.1.6",
"@react-navigation/native-stack": "7.3.10",
"react-native-gesture-handler": "2.25.0",
"react-native-reanimated": "3.17.4",
"react-native-safe-area-context": "^5.4.0",
"react-native-screens": "^4.0.0",

### Screenshots

![Image](https://github.com/user-attachments/assets/43c7e7d6-d45f-40a6-9553-8b0c0deea287)
![Image](https://github.com/user-attachments/assets/884a5f98-ad51-4ae4-85c7-13c82f418383)

### 🔁 Reproduction Steps
Enable New Architecture in a React Native app

Install and configure:

@react-navigation/native with a basic stack navigator

@gorhom/bottom-sheet (v5)

Create two screens:

ScreenA: headerShown: false, contains a

ScreenB: headerShown: true, standard content

From ScreenA, navigate to ScreenB using navigation.navigate('ScreenB')

Observe: an unexpected blank space appears at the bottom of ScreenB

### Expected behavior

Moving between screens without having an empty space at the bottom when not using header.

### Reproduction

none

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [x] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [] I've removed the packages that I don't use

| Package                              | Version  |
| ------------------------------------ | -------- |
| @react-navigation/native            | 7.1.6    |
| @react-navigation/native-stack      | 7.3.10   |
| react-native-screens                | 4.0.0    |
| react-native-safe-area-context      | 5.4.0    |
| react-native-gesture-handler        | 2.25.0   |
| react-native-reanimated             | 3.17.4   |
| react-native-pager-view             | 6.7.0    |
| react-native                        | 0.79.1   |
| node                                | 22.14.0  |
| npm or yarn                         | 1.22.22  |

**Comment by FightFarewellFearless** [comment]
+1 same issue here

**Comment by azizbecha** [comment]
#### Fixed by replacing ```native-stack``` with ```stack```

### Before
```ts
import { createNativeStackNavigator } from '@react-navigation/native-stack';

const Stack = createNativeStackNavigator();
```

### After
```ts
import { createStackNavigator } from '@react-navigation/stack';

const Stack = createStackNavigator();
```

@FightFarewellFearless

**Comment by FightFarewellFearless** [comment]
> #### Fixed by replacing `native-stack` with `stack`
> ### Before
> import { createNativeStackNavigator } from '@react-navigation/native-stack';
> 
> const Stack = createNativeStackNavigator();
> ### After
> import { createStackNavigator } from '@react-navigation/stack';
> 
> const Stack = createStackNavigator();
> [@FightFarewellFearless](https://github.com/FightFarewellFearless)

Yes, but i need to use native-stack, i think this issue still needs to be opened

**Comment by klawijuice** [comment]
@azizbecha  +1 same issue

**Comment by Irashad** [comment]
same issue

**Comment by azizbecha** [comment]
@Irashad  This issue is caused by adding ```headerShown: true```, not the bottom sheet.
I got a temporary fix which is using React Native Paper's ```AppBar``` component

**Comment by sgtpsibin** [comment]
have you try to upgrade react-native-screens?
