### ISSUE TITLE
swipeEnabled prop has no effect — swipe gesture cannot be disabled

### ISSUE THREAD

**Issue by CMLCNL** [react-navigation/react-navigation#12851]
### Current behavior

The swipeEnabled prop in react-native-tab-view does not seem to work.
Setting swipeEnabled={false} has no effect — users can still swipe between tabs.

This happens on both iOS and Android.

### Expected behavior

```
<TabView
  navigationState={state}
  renderScene={renderScene}
  onIndexChange={setIndex}
  swipeEnabled={false}
  renderTabBar={props => <TabBar {...props} />}
/>
```

Even with swipeEnabled={false}, swipe gestures remain active.

Expected Behavior

When swipeEnabled={false}:

Users should NOT be able to swipe between tabs.

Tab transitions should only be possible via the TabBar.

Actual Behavior

Swiping continues to work normally.
The swipeEnabled prop appears to be ignored.

Additional Notes

It may be related to props not being passed correctly to react-native-pager-view.

Also tested with different gesture-handler configurations — same result.

### Reproduction

github.com

### Platform

- [x] Android
- [x] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [ ] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [x] react-native-tab-view

### Environment

package	version
@react-navigation/native	^7.0.15
@react-navigation/native-stack	^7.2.1
react-native-tab-view	4.2.0
react-native-screens	4.16.0
react-native-safe-area-context	5.2.0
react-native-gesture-handler	2.28.0
react-native-reanimated	4.0.2
react-native-pager-view	7.0.0
react-native	0.81.4

**Comment by cumen** [comment]
I have the same problem

**Comment by glyhakan** [comment]
I am dealing with the same issue too

**Comment by avcialper** [comment]
i am experiencing the same issue

**Comment by onurzorluer** [comment]
houston, we have a problem!

**Comment by jorgeatlivo** [comment]
Experiencing this too, it's pretty annoying. It seems I can do the first swipe to a page even is swipe enabled is set to false, but not swipe back.

**Comment by denysoleksiienko** [comment]
This is `react-native-pager-view` issue and was fixed in 7.0.2
https://github.com/callstack/react-native-pager-view/issues/1028

**Comment by UPROOT01** [comment]
i think there has been a regression in `react-native-pager-view`, because i am having again this issue (and many others actually) with version 8.0.0, but not with version 7.0.2

**Comment by witkospiotr** [comment]
Issue still exist. In my case even if I have swipeEnabled={false}, it block swipe gesture for SwipeListView from react-native-swipe-list-view which is rendered through renderScene.
