### ISSUE TITLE
Android - transition animation glitch when navigating back with new architecture enabled

### ISSUE THREAD

**Issue by mlazari** [react-navigation/react-navigation#12897]
### Current behavior

A stack navigator with 2 screens, each screen contains a scroll view with some items (the scroll view on the second screen is not necessary, but helps to reproduce the issue a bit easier). To reproduce the issue:
1. Start scrolling the list and while it's still scrolling due to inertia navigate to the second screen.
2. Wait a bit and navigate back
3. See a weird jump at the end of the transition back to the first screen

https://github.com/user-attachments/assets/97055f48-de72-4b75-8575-d81e059bbcaa

In slow motion (to see better what happens):

https://github.com/user-attachments/assets/746ae797-bcd0-4cea-9f1d-dd8b45fc9eb7

In the project I am working on this happens without scrolling a scrollview before navigating, but I could not find how to reproduce that in a minimal repro.

### Expected behavior

That jump at the end should not happen, same as when using old architecture (you can try it in the old-arch branch in the repro repository):

https://github.com/user-attachments/assets/0439bc85-a7b1-43c2-8816-a4cf14cf162a

### Reproduction

https://github.com/mlazari/navrepro

### Platform

- [x] Android
- [ ] iOS
- [ ] Web
- [ ] Windows
- [ ] MacOS

### Packages

- [ ] @react-navigation/bottom-tabs
- [ ] @react-navigation/drawer
- [ ] @react-navigation/material-top-tabs
- [x] @react-navigation/stack
- [ ] @react-navigation/native-stack
- [ ] react-native-drawer-layout
- [ ] react-native-tab-view

### Environment

- [X] I've removed the packages that I don't use

| package                                | version |
| -------------------------------------- | ------- |
| @react-navigation/native               | 7.1.25
| @react-navigation/stack                | 7.6.12
| react-native-screens                   | 4.16.0
| react-native-safe-area-context         | 5.6.2
| react-native-gesture-handler           | 2.28.0
| react-native                           | 0.81.5
| expo                                   | 54.0.27
| node                                   | 23.3.0
| npm or yarn                            | 10.9.0

**Comment by shahana0994** [comment]
I am also facing the same issue on Android. Is there any solution?

**Comment by mlazari** [comment]
Opened https://github.com/software-mansion/react-native-screens/issues/3483

**Comment by BlueShork** [comment]
Same problem, any solution ?

**Comment by mlazari** [comment]
I am not sure this issue is related to `react-native-screens` though, since I removed it completely in a separate branch https://github.com/mlazari/navrepro/tree/no-react-native-screens and the issue is still reproducing. The only difference I see is that without `react-native-screens` the scrollview from the first screen seems to continue scrolling in background after navigating to the second screen, so you have to navigate back quickly, while it's still scrolling to see the issue. With `react-native-screens` it seems like it pauses the scroll on first screen until you navigate back, so you can wait longer on the second screen and the issue is still reproducible when you navigate back later.

**Comment by mlazari** [comment]
The width of the gap when the screen jumps to the left seems to come from here: https://github.com/react-navigation/react-navigation/blob/%40react-navigation/stack%407.6.12/packages/stack/src/TransitionConfigs/CardStyleInterpolators.tsx#L362

<img width="1080" height="2400" alt="Image" src="https://github.com/user-attachments/assets/5cef20a7-e2d3-48ec-b9aa-9bf559f219b0" />

If I change -96 to -200 for example, the size of that gap increases to 200.

It seems like `next.progress` animates from 1 to 0 then suddenly jumps to 1 right before `next` becomes undefined which sets translateX to 0 and brings the screen back into the correct place. I couldn't verify it though, because the listener I add to the `next.progress` animated value doesn't fire, probably because of this issue: https://github.com/facebook/react-native/issues/49719

**Comment by mlazari** [comment]
I was able to log the animated value change of next.progress by reverting a change in react-native, as per https://github.com/facebook/react-native/issues/49719#issuecomment-3179664900 and I don't see the value jumping back to 1 at the end.

But I found this react-native issue which seems to be the same issue as far as I can tell: https://github.com/facebook/react-native/issues/50496

I tried setting `useNativeDriver: false` at this line https://github.com/react-navigation/react-navigation/blob/%40react-navigation/stack%407.6.12/packages/stack/src/views/Stack/Card.tsx#L253 and it does indeed fix the screen jump.

**Comment by mlazari** [comment]
@shahana0994 @BlueShork As a workaround, these [animations](https://reactnavigation.org/docs/stack-navigator/#animations) seem to not be affected by that bug as far as I can tell, so you can try them if that's acceptable for your app:
```
fade
fade_from_bottom
slide_from_bottom
none
```

**Comment by moeezally** [comment]
Do we have a permanent fix for this instead of a workaround, which works in some cases and doesn't work in some?

**Comment by mlazari** [comment]
An update on my previous comment. While those 4 animation options seem to work in the repro project, the only one that works without issues in my real project is `none` (i.e. no animation).

Since the issue is reproducible without react-native-screens, I think the bug is either in react-navigation or in react-native (the issue looks somehow related to https://github.com/facebook/react-native/issues/50496 but I am not 100% sure it is the same issue).

I tried my best to find some more clues to find what the root cause is, but unfortunately couldn't so far.

The only thing I observed is that it seems like the animated progress value seems to jump back to its initial value for a moment after animating to a final value, and that seems to happen when something "heavy" is going on (In the repro project it's the momentum scrolling of a scrollview, in my project is probably something else). At least the jump of the screen seems to correspond to that initial value, as I wrote in my comment above (https://github.com/react-navigation/react-navigation/issues/12897#issuecomment-3665749124).

Also in a Pixel emulator from Android Studio is much harder to reproduce it. On real devices like Samsung Galaxy A52 and Samsung Galaxy S23 Ultra it reproduces easily.

Also the issue seems to go away until app restart after hot reload when making changes to some specific files as I mentioned here: https://github.com/software-mansion/react-native-screens/issues/3483#issuecomment-3660693222

I would appreciate if someone could take a look at this or at least point me what else I could try to debug it. Thank you!

**Comment by huytdps13400** [comment]
I am also facing the same issue on Android. Is there any solution?

**Comment by mikelros** [comment]
~~Downgrading to @react-navigation/stack 7.6.3 solved it for me.~~

It must be a different thing! Didn't test the repro. Sorry for the noise.

**Comment by mlazari** [comment]
@mikelros I think I saw your comment somewhere previously and tried downgrading to that version, but it didn't fix it for me. Do you have new architecture enabled? What version of expo (if you use it) and react-native do you have installed? Also the version of the other @react-native/* packages you're using. Thank you!

**Comment by mlazari** [comment]
I created a branch in my repro using @react-navigation/stack 7.6.3: https://github.com/mlazari/navrepro/tree/stack-downgrade The issue is still reproducible for me.

**Comment by Nader-CS** [comment]
any solution yet ?

**Comment by macielsousadasilva** [comment]
I'm having the same problems, has anyone found a solution?

These animations didn't work for me:

fade
fade_from_bottom
slide_from_bottom
none

"@react-navigation/bottom-tabs": "^7.4.7",
"@react-navigation/drawer": "^7.5.9",
"@react-navigation/elements": "^2.6.4",
"@react-navigation/native": "^7.1.17",
"@react-navigation/native-stack": "^7.3.26",
"@react-navigation/stack": "^7.4.10",

**Comment by khethelogp** [comment]
Using this worked for me

```
import { createNativeStackNavigator } from "@react-navigation/native-stack"
createNativeStackNavigator()
```

and not

 ```
import { createStackNavigator } from "@react-navigation/stack"
createStackNavigator()
```

**Comment by BaraJabali** [comment]
> Using this worked for me
> 
> ```
> import { createNativeStackNavigator } from "@react-navigation/native-stack"
> createNativeStackNavigator()
> ```
> 
> and not
> 
> ```
> import { createStackNavigator } from "@react-navigation/stack"
> createStackNavigator()
> ```

thanks it worked for me

**Comment by chathuralakmal** [comment]
> Using this worked for me
> 
> ```
> import { createNativeStackNavigator } from "@react-navigation/native-stack"
> createNativeStackNavigator()
> ```
> 
> and not
> 
> ```
> import { createStackNavigator } from "@react-navigation/stack"
> createStackNavigator()
> ```

This Works. But the problem is in our app we have some custom header styling and native-stack does not support it,

**Comment by mlazari** [comment]
Exactly, `@react-navigation/native-stack` works, but it is not the same thing as `@react-navigation/stack` and it's not possible to replace it without affecting styling.

**Comment by arnoldc** [comment]
same dillema for me going back flickers the screen , exactly how it was describe here 

for the workaround, its not possible for me
can see a big perf issue when disabling useNativeDriver and cant use native-stack :(

**Comment by JosephPoplar** [comment]
In my react-native v0.77.3(new arch enabled) ,downgrade react-navigation versions worked for me.
```
    "@react-navigation/bottom-tabs": "6.5.11",
    "@react-navigation/native": "6.1.9",
    "@react-navigation/stack": "6.3.20",
    "react-native-screens": "4.13.1",
```

**Comment by ben-snaize-fg** [comment]
For our iOS and Android Apps, downgrading to `"@react-navigation/stack": "7.4.2"` sorted the issue _however_ it made all other slide animations glitchy. This is on RN `0.82.1`

**Comment by zarv1k** [comment]
Just checked different versions of `@react-navigation/stack`: `7.6.3` has NO such issue. The issue reproduces in versions from `7.6.4` to `7.8.5` at the moment

**Comment by mlazari** [comment]
> Just checked different versions of `@react-navigation/stack`: `7.6.3` has NO such issue. The issue reproduces in versions from `7.6.4` to `7.8.5` at the moment

@zarv1k Maybe your issue is different or something, because I tested that version in the repro repo and it didn't fix the issue: https://github.com/react-navigation/react-navigation/issues/12897#issuecomment-3744310215

**Comment by zarv1k** [comment]
@mlazari Maybe, who knows. In my case the flickering is noticeable on previous/outgoing screen while transitioning forward and also weird flashing on back transition. It happens ONLY if you transition from/to screen with bottom-tabs.

https://github.com/user-attachments/assets/f8a84151-328a-43c1-8258-796e9a626a99

There are no such issues like on video attached in `7.6.3`

**Comment by mlazari** [comment]
@zarv1k Yes, looks like the same issue. Maybe in `7.6.3` is just less likely to happen. What versions do you have for the other `@react-navigation/*` dependencies? Maybe I can give it a try in my real app later to see if it makes any difference for me.

**Comment by zarv1k** [comment]
@mlazari 

Using this stack I have no such issues during forward/backward transition from/to screens with bottom-tabs:

```
"react-native": "0.84.1",
"@react-navigation/bottom-tabs": "7.15.5",
"@react-navigation/native": "7.1.33",
"@react-navigation/stack": "7.6.3",
"react-native-screens": "4.24.0",
```

https://github.com/user-attachments/assets/cbed6117-3624-4d26-9900-4e544f246104

**Comment by moonhee0507** [comment]
```typescript
screenOptions: {
  ...TransitionPresets.SlideFromRightIOS,
  transitionSpec: {
    ...TransitionPresets.SlideFromRightIOS.transitionSpec,
    ...(Platform.OS === 'android' && {
      close: {
        animation: 'timing',
        config: {
          duration: 150,
        }
      }
    })
  },
},
```

**Comment by ben-snaize-fg** [comment]
Update from our App - we removed all the `CardStyleInterpolator` usages and replaced them with the stack based `animation` options. This fixed the glitch.

**Comment by balsick** [comment]
it looks like the issue is solved if the same strategy of setting a timeout to call the animate as in the lines above is applied on the `maybeAnimated` method in the `Card`.

https://github.com/react-navigation/react-navigation/blob/main/packages/stack/src/views/Stack/Card.tsx#L398

On the `7.8.4` version I've applied this diff

```diff
diff --git a/node_modules/@react-navigation/stack/lib/module/views/Stack/Card.js b/node_modules/@react-navigation/stack/lib/module/views/Stack/Card.js
index a51c3db..92f08b4 100644
--- a/node_modules/@react-navigation/stack/lib/module/views/Stack/Card.js
+++ b/node_modules/@react-navigation/stack/lib/module/views/Stack/Card.js
@@ -267,9 +267,9 @@ function Card({
         // When route was closed due to a gesture, the animation would've happened already
         // It's still important to trigger the animation so that `onClose` is called
         // If `onClose` is not called, cleanup step won't be performed for gestures
-        animate({
-          closing
-        });
+        timeoutRef.current = setTimeout(() => {
+          animate({ closing });
+        }, 0);
       } else if (typeof previousOpening === 'boolean' && opening && !previousOpening) {
         // This can happen when screen somewhere below in the stack comes into focus via rearranging
         // Also reset the animated value to make sure that the animation starts from the beginning
diff --git a/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx b/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
index d4d214e..a9f0769 100755
--- a/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
+++ b/node_modules/@react-navigation/stack/src/views/Stack/Card.tsx
@@ -423,7 +423,9 @@ function Card({
         // When route was closed due to a gesture, the animation would've happened already
         // It's still important to trigger the animation so that `onClose` is called
         // If `onClose` is not called, cleanup step won't be performed for gestures
-        animate({ closing });
+        timeoutRef.current = setTimeout(() => {
+          animate({ closing });
+        }, 0);
       } else if (
         typeof previousOpening === 'boolean' &&
         opening &&
```

**Comment by AlixH** [comment]
Still have the issue with 7.8.9 and adding this to the screen fixes it for me
```tsx
        options={{cardStyleInterpolator: noParallaxInterpolator}}
```
```
function noParallaxInterpolator({ current, next, layouts }: StackCardInterpolationProps) {
  const translateX = next
    ? next.progress.interpolate({
        inputRange: [0, 1],
        outputRange: [0, -layouts.screen.width * 0.3],
        extrapolate: 'clamp',
      })
    : current.progress.interpolate({
        inputRange: [0, 1],
        outputRange: [layouts.screen.width, 0],
        extrapolate: 'clamp',
      });
  return {
    cardStyle: { transform: [{ translateX }] },
  };
}
```

**Comment by Splicer97** [comment]
same issue

**Comment by J-scuba** [comment]
I had the same issue and what I found was that when new arch is enabled, every native driven animation will trigger a scheduledUpdate
in createAnimatedPropsHook.js to sync the end animated value back to the js fabric. This scheduled updates can be called by other animations that cause the fabric picked up a stale navigation props for the other unfinished animations. For example, you have navigation animation forFadeFromBottomAndroid as Animation-A and TopBarBackButtonOpacityAnimation as Animation-B. When navigate, both animations are triggered and driven by native. Animation-B finished early, and ask Fabric to sync the latest animated opacity to the js layer by calling schedulUpdate(), However, at this point Animation-A hasn't finished yet, the translateX is still at the begining of the animation, say -96, the stale translateX is flushed along with animation-B complete updates <---- this causes the issue. 
Later when animation-A finished, it will reset the view props back to the correct state. 

createAnimatedPropsHook.js uses this line to sync the native props back to the js layer, and it is only enabled for fabric. 
`if (node.__isNative) { if (isFabricNode) { scheduleUpdate(...) } }`

In my case it is TouchableOpacity that created the parallel animation. 

The react native also seems to have another issue, when the animiation finished, it doesn't update js the latest value before notify the animation ended this could also cause the update happens too early. Still investigating this part.
