### ISSUE TITLE
Reset stack from other stack inside tab

### ISSUE THREAD

**Issue by EstebanBP** [react-navigation/react-navigation#2291]
###My navigators

Stack
  -TabNav
     --Tab1
       ---Stack1 (routes A, B)
    --Tab2
       ---Stack2 (routes C, D)

### Expected Behavior
From A, I want to move to Tab2 and reset stack to [C,D]

### Current Behavior
This does work but just navigate, do not reset, so I stack on top of everything I had:

		const navigateAction = NavigationActions.navigate({
			routeName: 'Stack2',
			params: {},
			action: NavigationActions.navigate({
				routeName: 'D'
			})
		});
		this.props.navigation.dispatch(navigateAction);

This doesn't work:

		const navigateAction = NavigationActions.navigate({
			routeName: 'Stack2',
			params: {},
			action: NavigationActions.reset({
				index: 0,
				actions: [
					NavigationActions.navigate({routeName: 'C'}),
					NavigationActions.navigate({routeName: 'D'})
				]
			})
		});
I get "There is no route defined for key "C". Must be one of: 'A', 'B'

What am I doing wrong?

**Comment by webcorebrasil** [comment]
I have a very similar problem as well:

DrawerNavigator:
 - Home (React.Component)
 - Profile (React.Component)
 - Assessment: (StackNavigator)
     - Intro
     - Test
     - Review
     - Results

From the Home screen the user selects the profile, it navigates to the Profile screen with the profile params, the user then have a button to evaluate this profile, as soon as the user clicks on that button it navigates to the Assessment screen (which is a StackNavigator with headerMode: 'none'). At the end, the user will be in the Results screen and there is a button there that the user can open the Home screen again. As the user will be able to assess other profiles, it has to reset the stack.

`_onGoToHomeButtonClicked(){

	NavigationActions.reset({
		index: 0,
		actions: [
			NavigationActions.navigate({
				routeName: 'Home',
			}),
		]
	})

	this.props.navigation.dispatch(resetAction)

}`

And as soon as the user clicks on that button, it throws an error:  There is no route defined for key "Home". Must be one of: 'Intro', 'Test', 'Review', 'Results'

I've already tested all kinds of workarounds and none of them worked.

**Comment by vendramini** [comment]
Same: https://stackoverflow.com/questions/45512060/reset-react-navigation-stack-from-drawer

**Comment by diz00** [comment]
Having the exact same issue.

**Comment by jhalborg** [comment]
Same as: https://github.com/react-community/react-navigation/issues/1127 I think, too

**Comment by quadsurf** [comment]
The need to reset from one nested stack to another nested stack, or from a nested stack to the root stack, is a very common use case for memory conservation.

With react-navigation as is, when a user logs out, I am forced to push more stack on top of existing stack because "reset" does not work from nested components, which slows down my app's performance and ultimately the UX my app's users expect. Furthermore, because I can't unmount components that either have real-time subscriptions or polling in place, when a user logs out, these pub/sub and/or polling requests continue on in an un-authenticated state, yielding awful UX.

**Comment by sikorsky555** [comment]
This bug leads to inconsistent behavior in a user interface. We have multiple StackNavigators nested inside of a DrawerNavigator. One of our screens has a TextInput. Because we are unable to reset the navigation stack to the root or another view within the tree, every time we enter the Stack with the input, the keyboard is shown. 
I have tried to force the navigation to happen without animation, reset as far as we can in the tree and then perform navigation, but the components don't seem to go away. So resetting doesn't work, navigating to another Stack and then back causes issues, I can't seem to find a solution to this problem. The keyboard is always shown after that screen in that stack has been hit.

Has anybody found a workaround for the problem listed by @webcorebrasil?

**Comment by rpopovici** [comment]
@EstebanBP potential solution in this PR #2292

**Comment by boomfly** [comment]
Passing key props makes all working!!))
```
reset() {
    const { navigate } = this.props.navigation
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'Login'})
      ],
      key: null // THIS LINE
    })
    this.props.navigation.dispatch(resetAction)
  }
```

**Comment by lucianomlima** [comment]
@boomfly works for me! Thanks!

**Comment by NYamaguchi415** [comment]
@boomfly I'm getting an 

> undefined is not an object (evaluating 'this.props.navigation')

is this the correct way to use? 

`
React, { Component } from 'react';
import { View, Button } from 'react-native';
import { NavigationActions } from 'react-navigation';

class FinalScreen extends Component {
  reset() {
    const { navigate } = this.props.navigation
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'home' })
      ],
      key: null
    });
    this.props.navigation.dispatch(resetAction);
  }

  render() {
    return (
      <View>
        <Button
          title='exit out'
          onPress={this.reset}
        />
      </View>
    );
  }
}

export default FinalScreen;
`

**Comment by lucianomlima** [comment]
@NYamaguchi415 you have lost context in the method reset.
You need to declare as arrow function or use bind.
```
import React, { Component } from 'react';
import { View, Button } from 'react-native';
import { NavigationActions } from 'react-navigation';

class FinalScreen extends Component {
  reset = () => {
    const { navigate } = this.props.navigation
    const resetAction = NavigationActions.reset({
      index: 0,
      actions: [
        NavigationActions.navigate({ routeName: 'home' })
      ],
      key: null
    });
    this.props.navigation.dispatch(resetAction);
  }

  render() {
    return (
      <View>
        <Button
          title='exit out'
          onPress={this.reset}
        />
      </View>
    );
  }
}

export default FinalScreen;
```

**Comment by boomfly** [comment]
@NYamaguchi415 you need to bind context of reset method:
```
<Button
  title='exit out'
  onPress={this.reset.bind(this)}
/>
```

**Comment by NYamaguchi415** [comment]
Ah I see, thanks guys. I corrected this, but running back into the original error stating that the routeName must be one of the screens within the same stack. For some reason including the key: null is not working for me.

**Comment by lsps9150414** [comment]
@EstebanBP Hey, I have the exact same need. Adding `key: null` only point to the root navigator which is not what I need. Have you solved it and could you share how? Thanks!

**Comment by ljuborados** [comment]
If I understood correctly you can use key prop to define which StackNavigator do you want to reset, 
but I still don't see a way of getting a key for a certain StackNavigator..

**Comment by lsps9150414** [comment]
@ljuborados The key should be the screen key you give to the navigator. However I tired and it didn't work :/

**Comment by gzLonglilin** [comment]
How to implement a subview to a certain item of the Tab view？

**Comment by EstebanBP** [comment]
@lsps9150414 I couldnt do it, and I'm facing this problem again in other app Im working on.
Using the same example: 
Stack
-TabNav
--Tab1
---Stack1 (routes A, B)
--Tab2
---Stack2 (routes C, D)

From A, I can go Stack 2 and navigate to D. But If I had previously navigated to D, it will push D again so Stack 2 would be [C, D, D]
I'd like to reset the stack, but I do not understand why this doesn't work (from route A): 
```
const action = NavigationActions.navigate({
      routeName: 'Tab2',
      action: NavigationActions.reset({
        index: 1,
        actions: [
          NavigationActions.navigate({
            routeName: 'C',
          }),
         NavigationActions.navigate({
            routeName: 'D',
          }),
        ],
      }),
    });
```

**Comment by lsps9150414** [comment]
@EstebanBP thanks for sharing. I've found that if you use redux, integrate with redux and manipulate the nav state directly may be the easiest way to do complex navigations.

**Comment by mvanroon** [comment]
@lsps9150414 facing the same problem, might go with your advice... although redux integration is such a pain and makes code so much more complicated

**Comment by brentvatne** [comment]
can someone please create an example on https://snack.expo.io that clearly reproduces the issue faced here? it is very helpful for us to work on a fix

**Comment by mgscreativa** [comment]
Hi @brentvatne I have setup a basic example for this issue https://snack.expo.io/@mgscreativa/complex-react-navigation

If you navigate through Home stack, you will get redirected to second screen of History stack, then if you switch to Home tab, you will see that last Home stack screen is active.

What is the correct way to tell Home Stack in Home2.js that it should navigate to History2 from History stack and also reset himself...

**Comment by mgscreativa** [comment]
Well, I think It's not, in my real project with the above code I get my Home screen (first stack item in the tab navigator) reset...I need to go bacl to that screen, not reset it, I mean, the component of that stack item gets redrawn, and I don't want that...

**Comment by mgscreativa** [comment]
Sorry for so many replies, to be more clear, please take a look at the snack, if you see first screen has a timer. After navigating the app and go back to Home tab you will see timer reset to 0...

My use case needs to get that screen not reset at all. In the example, the timer should keep counting after navigation, not get reset to 0

So in summary:

1. Need to do deep navigation on first tab (which is a stack navigator embedded in the first tab of a tab navigator)
2. At some point in navigation, my app needs to navigate to another screen in another stack, which is also embedded in a tab navigator (which is the second tab)
3. Performing that action, should set the active screen of the first tab stack navigator but not reset it

**Comment by mgscreativa** [comment]
Hi @brentvatne  I think I found it! take a look at the `onFinishNavigationWithNavigate` method. Would yo be so kind to tell me if that's the correct way t do it. It serves my usecase as a champ...

**Comment by n1ru4l** [comment]
@mgscreativa Do you have an example for v2?

**Comment by brentvatne** [comment]
> Hi @brentvatne I think I found it! take a look at the onFinishNavigationWithNavigate method. Would yo be so kind to tell me if that's the correct way t do it. It serves my usecase as a champ...

if it works, it works!

**Comment by nellybaz** [comment]
The Answer is createSwitchNavigator, it those not stackup your navigation 
https://reactnavigation.org/docs/en/auth-flow.html

**Comment by eliasrodeloso** [comment]
I have an StackNavigator inside a DrawerNavigator, and none of the solutions listed above have worked for me. Once I find a workaround I will tell!

**Comment by Raj-Madheshia** [comment]
It worked for me
     --Tab1
              ---Stack1 (routes A, B)
      --Tab2
             ---Stack2 (routes C, D)
suppose you want to move from C  to A , than create Your navigation as given below

 --stack X -> MainScreen
 --stack Y -> Tab1
                         ---Stack1 (routes A, B)
               --Tab2
                        ---Stack2 (routes C, D)

**MainScreen snippet** 
```
export default class mainScreen extends React.Component{
    componentWillMount(){
        this.props.navigation.navigate('stack Y')
    }
    render(){
        return(
            <View style={{flex:1}}>
            </View>
        )
    }
}
```
**Now for moving from C to A   call movetoA** 
```
movetoA = () => {
        this.props.navigation.navigate("stack X");
        this.props.navigation.navigate("stack Y");
}
```
This will redirect to A

**Comment by augustosamame** [comment]
I tried all the solutions here and the only one that worked was @eliasrodeloso. A beer is owed.

**Comment by iamshadmirza** [comment]
> ```js
> action: NavigationActions.navigate({
>         routeName: `Discover`
>       })
> ```

This worked for me. Thanks.

**Comment by tconn89** [comment]
I don't think `StackActions.popToTop()` works if you are already on the first route of the stack.  I just need to unmount my current stack completely and navigate to another one.

**Comment by swethasahithi** [comment]
@tconn89 Did you find any solution for this?

**Comment by elisegriset92** [comment]
Hello, stuck with the same problem in react navigation v5. Does anyone have a working solution ? Thanks

**Comment by kayzenkayzen** [comment]
I cannot find a solution to do this with react navigation v5

`
--Tab1
    - StackA
        - Route A1 ( The main screen of Tab1 )
        - Route A2 ( A child screen )
--Tab2
    - StackB
        - Route B1 ( The main screen of Tab2 )
        - Route B2 ( A child screen )
`

I want to reset from Route B2 to route A2 having the route A1 in the history, its means that A2 has back button to back to Route A1

Does anyone have a solution to do this? Thanks!

**Comment by chileap** [comment]
I stuck with this problem. Anyone found the solution?

**Comment by rarenatoe** [comment]
I am stuck at this too. I am doing something like this for v5:

```
import { createRef } from 'react';
import { TabActions } from '@react-navigation/native';

export const navigationRef = createRef();

export function reset({ tab, routes }) {
  navigationRef.current?.dispatch(TabActions.jumpTo(tab));
  navigationRef.current?.reset({
    index: routes.length - 1,
    routes,
  });
}
```

But the the reset action will fail when the destination tab's stack hasn't been initialized.

**Comment by hellotoby** [comment]
I believe the solution for this in v5 is here: https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator

**Comment by danfmaia** [comment]
> I believe the solution for this in v5 is here: https://reactnavigation.org/docs/nesting-navigators/#rendering-initial-route-defined-in-the-navigator

This is working! And it's in the official docs, so it's the most recommended solution. I'm just still having problems regarding the drawer being open after the user relogins. =/

**Comment by gregdburns** [comment]
I was able to do the following with React Navigation 6.x - this effectively resets one stack inside of a tab navigator from within another stack inside the tab navigator.

So, back to the original navigation setup:

Stack
-TabNav
--Tab1
---Stack1 (routes A, B)
--Tab2
---Stack2 (routes C, D)

```navigation.dispatch(() => {
      const rootNavigationState = navigation.getParent().getState()
      const routes = rootNavigationState.routes
      const stack2Route= routes.find(r => r.name === 'Stack2')
      navigation.getParent().reset({
        ...rootNavigationState,
        routes: [
          { name: 'Stack1' },
          stack2Route
        ],
        index: 1
      })
    })
```

This will reset Stack1 (it will unmount all screens that were navigated to within that route and go back to the first screen), while preserving the state in Stack2.
