### ISSUE TITLE
Nested Navigator goback problems.

### ISSUE THREAD

**Issue by fenglu09** [react-navigation/react-navigation#2549]
My Nested Navigatior:
```
StackNavigator
  loginScreen
  registerScreen
  tabNavigator
      tab1(StackNavigator)
           screen1
           screen2
      tab2(StackNavigator)
           screen3
           screen4
```
When  navigate to `tab2 -> screen3 ->screen4->screen2`, if `navigation.goback()`  in `screen2`, it go `tab1` rather than `screen4`. How can I goback to `screen4` when use `navigation.goback()`?

My Environment:
- react-navigation : 1.0.0-beta.11
- react-native    : 0.46.1
- node  : 6.9.1

**Comment by spencercarli** [comment]
Can you put together a sample project for this? `goBack` has some issues (both in code and documentation) and the more running examples we can have for this will aid in improvement. Thanks!

**Comment by fenglu09** [comment]
Here is the [demo](https://github.com/fenglu09/navigationBackDemo) .
home -> home page 2 -> message page2 then goback;
the desired result should be goback to `home page2`,but actual result is goback to `message` tab.

**Comment by jinxac** [comment]
Can you try `navigation.dispatch(NavigationActions.back())` ? Even i was facing the same issue, it works for me

**Comment by santomegonzalo** [comment]
@jinxac I had the same problem and now when I'm using your solution I'm seeing the following error https://github.com/react-community/react-navigation/issues/2938

**Comment by jinxac** [comment]
@santomegonzalo this is fixed in latest version. Can you try it out?

**Comment by namxam** [comment]
@santomegonzalo I have the exact same issue, but your quick fix does not fix it. Neither did an update to beta21.

Honestly I have a hard time understanding how the navigation state is handled. From what I see, it is a nested structure. Where each navigator handles its own state. Hitting back would mean, that multiple navigators would have to handle it. Or is my navigator setup somehow broken? I would have expected a flat structure. And call back() just pops the last item.

**Comment by Masoodt** [comment]
this is my working solution for reset back to home (root) without creating new route

```
let k = this.categoriesNav.state.nav.routes[1].key;
this.categoriesNav.dispatch(NavigationActions.back({key: k}));

```
categoriesNav is refrenced to my stack navigator

**Comment by ericvicenti** [comment]
@namxam, you are correct that the navigation state is a nested structure.

The navigation action will get passed to the deepest router, so that it can override back behavior in that area of the app. If the deeper router does not handle the action, the topmost router will handle the action. Feel free to open a follow-up issue- hopefully we already support the use case, and we can just fix up the documentation.

In reference to the original question by @fenglu09, it looks like you want custom behavior for the StackRouter within tab1 (because usually a stack router handles the back action and allows you to go back). You can override `Tab1Navigator.router.getStateForAction` to ignore the BACK action.
