### ISSUE TITLE
Can not switch tab until navigate back animation ends

### ISSUE THREAD

**Issue by helele90** [react-navigation/react-navigation#3471]
### Current Behavior

It seems like a bug. [this is video](https://www.youtube.com/watch?v=LHCu-Cm8tS4&feature=youtu.be)

If I switch back to tab2 immediately after returning, It will automatically switch to tab1.
If I wait a minute switch to tab2, there is no problem.
All interfaces may be triggered.

[Snack Expo](https://snack.expo.io/r1ye4TK8M)

### Expected Behavior

 The last time in the video is Expected Behavior.

### How to reproduce

It seems that the navigation animation does not end before switching tabs, it will fire.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 1.0
| react-native     | 50.1
| node             | v8
| npm or yarn      | npm 6.4

**Comment by kelset** [comment]
Can you please provide a repro with [Snack Expo](https://snack.expo.io/)?

**Comment by helele90** [comment]
@kelset  [this is Snack Expo](https://snack.expo.io/ryilXTKIf)

**Comment by brentvatne** [comment]
fixed and released 1.0.1, thanks for the report with the video and the snack! ❤️

**Comment by kgdev** [comment]
I believe the same fix exists for the StackRouter. Should we apply the same fix to StackRouter?

**Comment by dazweeja** [comment]
Agree with @kgdev. The same bug still exists in StackRouter, but in that case it's a simple one-line fix - change line 545 in master from:

`action.type === NavigationActions.SET_PARAMS`

to:

`action.type === NavigationActions.SET_PARAMS || action.type === StackActions.COMPLETE_TRANSITION`
