### ISSUE TITLE
iPad > TabBarBottom > Icons are not appearing

### ISSUE THREAD

**Issue by joncursi** [react-navigation/react-navigation#3704]
On iOS / Android phones, the tab icons appear normally. But on tablets / iPad, the icons are not present. Just the text labels.

Version: `react-navigation@1.5.0`

@brentvatne I noticed a relevant change was made in the `1.5.0` release to address this on phones, perhaps the change was incomplete and didn't include tablets?

**Comment by brentvatne** [comment]
fixed https://github.com/react-navigation/react-navigation/releases/tag/v1.5.2

**Comment by joncursi** [comment]
I just upgraded but my iPad tabs are still appearing to be icon-less:

![screen shot 2018-03-12 at 6 10 05 pm](https://user-images.githubusercontent.com/4974609/37312237-9c33029e-2620-11e8-8559-2be05d6b0938.png)

**Comment by brentvatne** [comment]
will need you to create an issue with a reproducible example as i cannot repro

<img width="708" alt="screen shot 2018-03-13 at 10 37 44 am" src="https://user-images.githubusercontent.com/90494/37359346-93ff8ac2-26aa-11e8-96cc-0021995cb3df.png">

**Comment by Sommerfeld** [comment]
For me it is not working when I do not specify the width of the Icon-Element.

```js
// visible
tabBarIcon: ({ tintColor, focused }) => (
  <View style={{ backgroundColor: 'red', width: 10 }}>
    <Text>A</Text>
  </View>
),

// not visible
tabBarIcon: ({ tintColor, focused }) => (
  <View style={{ backgroundColor: 'red' }}>
    <Text>A</Text>
  </View>
),
```

**Comment by brentvatne** [comment]
this should be resolved. if it is not working as expected still on the latest version, please create a new issue with a runnable example on https://snack.expo.io -- thanks!
