### ISSUE TITLE
SafeAreaView breaks on rotation+navigation

### ISSUE THREAD

**Issue by TheAlmightyBob** [react-navigation/react-navigation#4006]
When wrapping screens in the react-navigation JS-based version of SafeAreaView (i.e. https://github.com/react-community/react-native-safe-area-view ), rotating the device and then navigating between screens can lead to the safe area margins being lost.

This is most easily/consistently reproducible by:
- Navigate forward to a screen
- Rotate
- Navigate back to the previous screen
- The previous screen no longer respects the safe area. 

But it is also sometimes seen when navigating forward, especially if there are also tabs involved.
![navigationvssafeareatabs](https://user-images.githubusercontent.com/7707864/38885048-6ead817e-4226-11e8-9ef7-212c88813d11.gif)
![navigationvssafeareanotabs](https://user-images.githubusercontent.com/7707864/38885083-899b6744-4226-11e8-9362-736d99f0ee6a.gif)

As the top GIF shows, rotating the device while it's displaying the screen with the broken safe area will "fix" it, but that's not a great user experience.

Setting up a repro project is simple:
- Use `exp init` and create a tabs project (only using this because it's the fastest way I know to spin up a react-navigation demo app)
- Wrap each screen in a `SafeAreaView` _imported from react-navigation (not react-native)_
- Add a stack navigation action (for the demo GIFs I just moved the LinksScreen from the tab routes to the stack routes and changed the "learn more" button to go there)

This does _not_ repro with the react-native version of SafeAreaView, however that is incompatible with react-navigation's tabs (#3767).

@davepack

**Comment by davepack** [comment]
Have you tried adding `forceInset={{horizontal: ‘always’}}`? This is definitely something I ran into in my testing and I believe adding that should fix it. I can’t test it atm and it’s been a while since I encountered so I’m not remembering exactly.

**Comment by TheAlmightyBob** [comment]
That seems to help the actual screen content in initial testing (have not tested extensively yet).

But it does not fix the navigation header, which is also affected by this, since that is rendered by react-navigation (I did not include this in the above GIFs since I wasn't expecting such a workaround to be suggested).

So if that is indeed the solution, then it needs to be fixed in https://github.com/react-navigation/react-navigation/blob/master/src/views/Header/Header.js

**Comment by brentvatne** [comment]
moving to umbrella issue
