### ISSUE TITLE
v2: Still pushy navigate between nested StackNavigator sub-routes

### ISSUE THREAD

**Issue by agomai** [react-navigation/react-navigation#4063]
### Current Behavior

`Navigate` action between a nested `StackNavigator`'s child route (e.g. *…Second.Second2*) to another nested and already visited `StackNavigator`'s child route (e.g. *…First.First2*) pushes a duplicate navigator (e.g. *…First.First2*) although it already exists from a previous navigation.

Using a [sub `action`](https://v2.reactnavigation.org/docs/en/navigation-actions.html#navigate) to `Navigate` to an existing `StackNavigator`'s (*First.First2*) child-route does not work – the navigator is focused but the sub-`action` seems not to be handled.

### Expected Behavior

V2 introduces [less pushy `navigate`](https://v2.reactnavigation.org/blog/#navigateroutename-in-stacknavigator-is-less-pushy).

It's expected that "less pushy navigate" applies to navigation between nested navigators child routes as well. So *…First.First2* => *…Second.Second2* => *…First.First2* does not push a duplicate *First.First2* `StackNavigator` (*First*).

Also it's expected that a sub-`action` can be used to `Navigate` to a child route (e.g. *First.First2*) of an existing nested navigator.

### How to reproduce

Navigator structure:

~~~JavaScript
export const RootNavigator = createSwitchNavigator({
    Login: createDummyScreen('Login'),
    Main: createStackNavigator(
        {
            Other: createDummyScreen('Leaf'),
            First: createStackNavigator(
                {
                    First1: createDummyScreen('First1'),
                    First2: createDummyScreen('First2'),
                }
            ),
            Second: createStackNavigator(
                {
                    Second1: createDummyScreen('Second1'),
                    Second2: createDummyScreen('Second2'),
                }
            ),
        }
    )
});
~~~

**Navigate between sub-routes**

Expected: `navigation.dispatch(…'First2'…)` navigates back to existing `First.First2` navigator
Actual: duplicate `First.First2` is pushed

~~~
navigation.dispatch(NavigationActions.navigate({routeName: 'First2'}));
navigation.dispatch(NavigationActions.navigate({routeName: 'Second2'}));
navigation.dispatch(NavigationActions.navigate({routeName: 'First2'}));
~~~

It works with an explicit intermediate step to `First` navigator

~~~
navigation.dispatch(NavigationActions.navigate({routeName: 'First1'}));
navigation.dispatch(NavigationActions.navigate({routeName: 'Second2'}));
navigation.dispatch(NavigationActions.navigate({routeName: 'First'}));
navigation.dispatch(NavigationActions.navigate({routeName: 'First2'}));
~~~

**Using sub-`action`**

Expected: `navigation.dispatch(… action …)` navigates to `First1`.
Actual: navigates to `First2`. Seems to find `First` but not run `action` to navigate to `First.First2`

~~~
navigation.dispatch(NavigationActions.navigate({routeName: 'First2'}));
navigation.dispatch(NavigationActions.navigate({routeName: 'Second2'}));
navigation.dispatch(NavigationActions.navigate({
	routeName: 'First',
	action: NavigationActions.navigate({
		routeName: 'First1'
	})
}));
~~~

With the [example app](https://github.com/agomai/react-navigation-issue-nested-navigation) you can reproduce the behavior:

* See `nested-navigation.js`
* Run the application `react-native run-ios`.
* Enable *Remote JS debugging*.
* Enter the above mentioned commands (`navigation.dispatch(…)`) into the developer tools console (`navigation` passed to screens is exposed to `global`)
* Check navigation state to see pushes of duplicate navigators: Enter `rootNavigator.state.nav` into the developer tools console (`ref` to `RootNavigator` exposed to `global`).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.0-rc.3
| react-native     | 0.55.3
| node             | 8.10.0
| npm      | 5.8.0

**Comment by brentvatne** [comment]
thanks for the report! I copied the example into a Snack and made it a bit easier to repro, see https://snack.expo.io/rJpO2mCnG

**Comment by brentvatne** [comment]
fixed in 2.0.0-rc.5

**Comment by agomai** [comment]
Awesome work 👏 Thanks a lot for the quick response!
I can confirm that the above *navigate between sub-routes* case is fixed 🎉

I'm still experiencing the *sub-action not handled*  issue:

Expected: `navigation.dispatch(… action …)` navigates to `First1`.
Actual: navigates to `First2`.

~~~
navigation.dispatch(NavigationActions.navigate({routeName: 'First2'}));
navigation.dispatch(NavigationActions.navigate({routeName: 'Second2'}));
navigation.dispatch(NavigationActions.navigate({
	routeName: 'First',
	action: NavigationActions.navigate({
		routeName: 'First1'
	})
}));
~~~

I added displaying the routes in the [example app](https://github.com/agomai/react-navigation-issue-nested-navigation):

`navigation.dispatch(NavigationActions.navigate({routeName: 'First2'}));`
<img width="244" alt="1 first2" src="https://user-images.githubusercontent.com/38727586/39309802-235e852a-4969-11e8-9ef5-576336a69880.png">

`navigation.dispatch(NavigationActions.navigate({routeName: 'Second2'}));`
<img width="244" alt="2 second2" src="https://user-images.githubusercontent.com/38727586/39309843-3a4b086c-4969-11e8-83e1-f2006fde5a5f.png">

`navigation.dispatch(NavigationActions.navigate({
	routeName: 'First',
	action: NavigationActions.navigate({
		routeName: 'First1'
	})
}));`
<img width="244" alt="3 first first1" src="https://user-images.githubusercontent.com/38727586/39309862-43fc69e6-4969-11e8-9048-2f5c664fbd31.png">

Is using sub-`action` for `Navigate` between nested navigators expected to work now?

**Comment by brentvatne** [comment]
can you create a new issue for that and try to isolate it more, like what I did in the snack that I shared? (basically remove *anything* that is unrelated, and make it possibly to interact with it and see the issue in snack easily)

**Comment by agomai** [comment]
Sorry for the delayed response, I created #4111.
