### ISSUE TITLE
Performance issues may caused by Navigator rerender bug

### ISSUE THREAD

**Issue by cbjs** [react-navigation/react-navigation#4412]
serious performance issue encountered after upgrading from v1.x to v2.x.

I submitted a issue:  https://github.com/react-navigation/react-navigation/issues/4282

It may be caused by rerendering problem mentioned in this issue
https://github.com/react-navigation/react-navigation/issues/4346

I create a sample project to show this issue. 4 simple Screens with only createBottomTabNavigator is used, 
```js
import React, { Component } from 'react';
import { Text, View, } from 'react-native';
import { createBottomTabNavigator } from 'react-navigation';

const ScreenTitle = ({title}) => {
    return <View style={{flex:1, justifyContent: 'center', alignItems: 'center'}}>
      <Text style={{ fontSize: 80, fontWeight: 'bold'}}>{title}</Text>
    </View>;
}
class Boards extends Component {
  render() {
    const { navigation } = this.props;
    console.warn('render boards');
    return <ScreenTitle title="boards"/>;
  }
}

class Profile extends Component {
  render() {
    const { navigation } = this.props;
    console.warn('render profile');
    return <ScreenTitle title="profile"/>;
  }
}

class Message extends Component {
  render() {
    const { navigation } = this.props;
    console.warn('render message');
    return <ScreenTitle title="message"/>;
  }
}

class Explore extends Component {
  render() {
    const { navigation } = this.props;
    console.warn('render explore');
    return <ScreenTitle title="explore"/>;
  }
}

const Home = createBottomTabNavigator({
  boards: {
    screen: Boards,
    navigationOptions: ({navigation}) => ({
      title: 'Boards',
    })
  },
  explore: {
    screen: Explore,
    navigationOptions: ({navigation}) => ({
      title: 'Explore',
    })
  },
  message: {
    screen: Message,
    navigationOptions: ({navigation}) => ({
      title: 'Message',
    })
  },
  profile: {
    screen: Profile,
    navigationOptions: ({navigation}) => ({
      title: 'Profile',
    })
  },
}, {
  initialRouteName: 'explore',
  tabBarPosition: 'bottom',
  swipeEnabled: false,
  animationEnabled: false,
  lazy: true,
  tabBarOptions: {
    showLabel: true,
    labelStyle: {
    },
    tabStyle: {
      padding: 13,
    },
    indicatorStyle: { height: 0 }
  }
});

export default Home;
```

v2.0.2 with this issue on master branch
https://github.com/cbjs/NavDemo

warn messages(from render method) will be shown, while click tabs.

v1.x without this issue on v1 branch
https://github.com/cbjs/NavDemo/tree/v1

no messages, while clicking tabs except for the first time.

I found that the navigation object is changed in the shouldComponentUpdate method. 
@vonovak @brentvatne

**Comment by satya164** [comment]
Can repro. Doesn't look it's specific to tab navigator. When I push a screen in stack navigator, the previous screen is re-rendered too. Can confirm that the navigation prop changes by placing a console log in `SceneView`.

**Comment by smadey** [comment]
Slow +1

**Comment by brentvatne** [comment]
will open a PR for this shortly, tested this locally and caching the descriptors resolves the issue

**Comment by brentvatne** [comment]
2.1.0 should resolve this issue https://github.com/react-navigation/react-navigation/releases/tag/2.1.0

**Comment by mortezaalizadeh** [comment]
The issue still exists and is not resolved yet. I tested it against both v2.1.0 and v2.2.3 and it still re-renders the screen that the user navigates from and is not shown on the screen. Is there any plan to fix it? Cheers

**Comment by brentvatne** [comment]
@mortezaalizadeh - provide the repro, this does not happen in my tests. https://stackoverflow.com/help/mcve

**Comment by mortezaalizadeh** [comment]
@brentvatne, can't do it, man, the repo is private and I don't have the authority to share it with the public. I need to find a way to create another repo and reproduce the issue there, but I can 100% guarantee it is still happening. I have a new branch for this upgrade and I am using the latest version of react-navigation. At the moment, I am keeping every other branches' changes sync with this branch, but it is just too difficult to keep them in sync. :(

**Comment by brentvatne** [comment]
i think you didn't read that link. i'm not asking you to share your code, i'm asking you to reproduce the issue you encounter in a minimal example case. if you can't do this, nobody can help you on any issue in open source :(

**Comment by elizamaria** [comment]
In my case this happens when I use swipeEnabled on a screen from a stackNavigator inside a TabNavigator
