### ISSUE TITLE
Error: There is no route defined... after switching tabs inside drawer scenes

### ISSUE THREAD

**Issue by Mtnt** [react-navigation/react-navigation#4429]
### Current Behavior
https://github.com/Mtnt/drawerSample - repo with a sample

`Error: There is no route defined for key 'Stack0'. Must be one of: 'scene2','scene3'`

### Expected Behavior

The `Tab0.Stack0.scene0` is opened.

### How to reproduce

Navigation stack (default is made by `initialRouteName` config property):
```
Drawer
  Tab0(default)
    Stack0(default)
      scene0(default)
      scene1
    Stack1
      scene2(default)
      scene3
  Tab1
    Stack2(default)
      scene4
```
Test path (made by pressing drawer menu and tabs):
```
Tab0.Stack0.scene0 ->
Tab0.Stack1.scene2 ->
Tab1.Stack2.scene4 ->
Tab0(.Stack0.scene0) - in parentheses because the error is happened here
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.0.4
| react-native     | 0.55.4
| node             | 10.0.0
| npm           | 6.1.0

# ALSO

### Current Behavior

`Tab0.Stack1.scene2` is opened

### Expected Behavior

The `Tab0.Stack0.scene0` is opened (cos it is a default tab).

### How to reproduce

Navigation stack is the same.
Test path: 
```
Tab0.Stack0.scene0 ->
Tab0.Stack1.scene2 ->
Tab1.Stack2.scene4 ->
navigation.navigate("Tab0") - press big red button
```

**Comment by brentvatne** [comment]
hi! I copied this example over to https://snack.expo.io/BJ0FZyyM7 and ran it and it worked as expected. perhaps the issue you encountered has been resolved since react-navigation@2.0.4 (we're at 2.5.x currently)

**Comment by Mtnt** [comment]
So, I just tried again with react-navigation@2.6.2 and the issue is still there =(
I don`t know how expo can affect to it... Below is gifs with samples.

**Comment by Mtnt** [comment]
@brentvatne So, I just tried again with react-navigation@2.6.2 and the issue is still there =(
I don`t know how expo can affect to it... Below is gifs with samples.

Case with error
![tags](https://user-images.githubusercontent.com/1556235/42448242-42d22d98-8385-11e8-8a9c-fa8cf2e83067.gif)

Case with unexpected result tab
![button](https://user-images.githubusercontent.com/1556235/42448304-782e0c14-8385-11e8-903e-d25c86c33399.gif)

**Comment by Mtnt** [comment]
@brentvatne do you see notifications about comments on a closed issue? =)

**Comment by hengsoo** [comment]
@Mtnt  Checkout issue #4351 & #3696

**Comment by seanmorton** [comment]
I believe https://github.com/react-navigation/react-navigation-drawer/pull/16 will solve this problem.
