### ISSUE TITLE
SafeAreaView umbrella issue

### ISSUE THREAD

**Issue by brentvatne** [react-navigation/react-navigation#4589]
SafeAreaView has some problems. Let's track those here.

- https://github.com/react-navigation/react-navigation/issues/4008
- https://github.com/react-navigation/react-navigation/issues/4006
- https://github.com/react-navigation/react-navigation/issues/3767
- https://github.com/react-navigation/react-navigation/issues/4165

**Comment by brentvatne** [comment]
@janicduplessis is doing some valuable upstream stuff here: https://github.com/facebook/react-native/pull/19921

**Comment by henriquea** [comment]
Yo @brentvatne 👋, it looks like all issues were closed. Is this still an issue in the latest release?

**Comment by TheAlmightyBob** [comment]
@henriquea It is still an issue. The other issues were closed simply as a result of creating this issue, presumably to de-clutter the issues list.

**Comment by brentvatne** [comment]
waiting for this which will address many of the issues: https://github.com/facebook/react-native/pull/20999

**Comment by DavOnGit** [comment]
Can we please get an update on this?

**Comment by TheAlmightyBob** [comment]
@DavOnGit I believe #3767 has been fixed. I _expect_ #4008 has been, but have not had a chance to revisit that issue. I completely forgot about the rotation issue (which _might_ mean it was fixed?), and don't know anything about the other issue.

**Comment by DavOnGit** [comment]
I'm still seeing something like #4006 with stacknavigation, alleviated by setting forceinset

**Comment by TheAlmightyBob** [comment]
@DavOnGit ah, that might be why I forgot about it then. I think we've gotten into the habit of just using `forceinset` everywhere.

**Comment by brentvatne** [comment]
we are migrating to https://github.com/th3rdwave/react-native-safe-area-context in an upcoming minor release which will resolve many problems with safe area view
