### ISSUE TITLE
Focus events not triggered when going back quickly (iOS)

### ISSUE THREAD

**Issue by sebk** [react-navigation/react-navigation#4674]
### Desired Feature

I want to use the "focus" events ('willFocus'/'didFocus') to handle the styling of a button when going back to the previous screen (via StackNavigator).

### Current (failure) Behavior

When going back via the top left back button quickly (immediately pressing the back button) the focus events aren't called at all. 
Going back after waiting a little bit, then the focus events are called correctly.

### How to reproduce

An example project is created: https://github.com/sebk/NavigationBugTest

To reproduce: 
Start the App on iOS, press the button on the HomeScreen (this will open SecondScreen) and immediately press on the top left back button in the navigation bar. 
The button on the HomeScreen will remain red, because the focus events aren't called (or look at the logs in the chrome dev tools console).

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 2.6.2
| react-native     | 0.56.0
| node             | 9.5.0
| yarn      | 1.7.0

**Comment by ericvicenti** [comment]
Ok this looks like a very real bug, pretty easy to reproduce with your example code here.

My plan is to get a test to cover this, then it will be easier to fix and stay fixed

**Comment by roma86** [comment]
I have related bug with `_willFocus`. It not triggered when going forward quickly too.

Here is the log example which i think help you understand what i mean.

Trigger `this.props.navigation.navigate(...` not very quick (user tap next button in Nav Bar from screen with ID 1.)
```
componentDidMount: screenID: 1
_willFocus: screenID: 1
componentDidMount: screenID: 2
_willFocus: screenID: 2
```

Trigger `this.props.navigation.navigate(...` quickly after screen appear (user tap next button in Nav Bar from screen with ID 1.)
```
componentDidMount: screenID: 1
_willFocus: screenID: 1
componentDidMount: screenID: 2
// expected to see _willFocus here, but it does not executed
```

Here is the pseudo code for this logging:  
```
export default class Screen extends React.Component {
...

componentDidMount() {
    const screenID = this.props.navigation.getParam('screenID');
    console.log('componentDidMount: screenID:', screenID);
    this.props.navigation.setParams({ handleNext: this._handleNext });

    this.subs = [
        this.props.navigation.addListener('willFocus', payload => {
           this._willFocus();
        }),

        this.props.navigation.addListener('willBlur', () => {
            this._willBlur();
        }),
    ];
}

_willFocus() {
    const screenID = this.props.navigation.getParam('screenID');
    console.log('FormPage _willFocus: screenID:', screenID);
}
```

**Comment by fbartho** [comment]
Sadly, I'm exhibiting this too.

**Comment by CrossCampusDev** [comment]
I am definitely experiencing this issue on 2.18.0 and it is happening as far back as 2.1.0. I found this as our app is reaching production release, so this is a potentially serious problem for us. I also tried 3.0.0-alpha.13 which was released yesterday, but that is redboxing me on the gesture handlers. I realize that is unrelated, but please let me know if I can provide any additional information and/or provide any other sort of help with this issue. I have subscribed to the issue.

**Comment by ericvicenti** [comment]
Hey folks, finally I've gotten to the bottom of this, and the fix will be released in the next version of react-navigation core

https://github.com/react-navigation/react-navigation-core/commit/cdc4d9192d5d3add1739cde47034050e52df70b4

**Comment by eriveltonelias** [comment]
Hey folks, 

this was solved, follow on https://github.com/react-navigation/react-navigation/issues/4822

Thanks @brentvatne and @ericvicenti !

**Comment by nervouself** [comment]
Hey, I also get the same issue.
When you switch quickly between two pages,the `state.isTransitioning` is always `true`, so [here](https://github.com/react-navigation/react-navigation/blob/665736d754b00c4d89c0d6b1a6e5446c416bdd03/src/getChildEventSubscriber.js#L135) will never be called, and then all events will not be triggered.

**Comment by windandsonw** [comment]
The problem is not solved，in"react-navigation": "^3.6.1",I also encountered this problem

**Comment by BranceLee** [comment]
A=>B=>A, I solve it by `setTimeout` 2s to navigate A from B, and will run the willFocus on A page.

**Comment by celineotter** [comment]
> A=>B=>A, I solve it by `setTimeout` 2s to navigate A from B, and will run the willFocus on A page.

2seconds!!! That is unusable for us. Any other advice? 
We see this still with 
```
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^2.0.16",
```

**Comment by celineotter** [comment]
> Should be fixed starting in react-navigation `3.0.0-alpha.15`, or `@react-navigation/core 3.0.0-alpha.15`

I am still experiencing this is in
```
    "react-navigation": "^4.0.10",
...
"@react-navigation/core@^3.5.1":
```

steps for us to repro:

start on A, 
=> go to B 
=> go to C 
=> back to B 
=> *very quickly* go to C (or any other screen, ay D) 
=> back to B, no `willFocus` is triggered

**Comment by raajnadar** [comment]
Try upgrading to latest version! Maybe your issue will get fixed.
