### ISSUE TITLE
cardStyle backgroundColor not applying in v3

### ISSUE THREAD

**Issue by BrendonSled** [react-navigation/react-navigation#5253]
### Current Behavior

- When setting a custom card background color in the StackNavigator the card always is white

### Expected Behavior

- To be the custom color like in v2

### How to reproduce

```
createStackNavigator({ Info }, {
    cardStyle: {
        backgroundColor,
    },
}),
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.0.0
| react-native     | 0.57.4

**Comment by BrendonSled** [comment]
My guess is this line,
https://github.com/react-navigation/react-navigation-stack/blob/master/src/views/StackView/StackViewCard.js#L85

The style is applied and not overwritten

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by BrendonSled** [comment]
> hi! please make your code runnable either on https://snack.expo.io without any extraneous code

https://snack.expo.io/ryBgDLVR7

**Comment by eriveltonelias** [comment]
thanks for the repro @BrendonSled and @iAlirezaKML

**Comment by andresmanikis** [comment]
I think that the default background color also changed in v3. In v2 was grey and in v3 is white. Could you confirm this?

**Comment by fedealva** [comment]
@andresmanikis you are right. The default color changed to white which is breaking the style of my app. Does anybody know how to fix this?

Thanks

**Comment by brentvatne** [comment]
fixed in https://github.com/react-navigation/react-navigation-stack/pull/62 and deploying shortly

**Comment by dereknelson** [comment]
@brentvatne I upgraded to react-navigation^3.0.1 and I still have the white background, do I have to manually apply that background color?

**Comment by BrendonSled** [comment]
@dereknelson yes, you can see my example above for how to configure the background color

**Comment by brentvatne** [comment]
white is the default background color now so yeah. I need to update blog post for breaking changes to include that

**Comment by vjsingh** [comment]
Anybody who happens to find this, you may need to add ```transparentCard: true``` after upgrading to 3.0. @brentvatne I couldn't find anything about this in the breaking changes.

This is one of Brent's snacks that may help you, and copied below is the full text needed to get transparent cards to work on a StackNavigator:
https://snack.expo.io/@notbrent/transparentcard
```
    transparentCard: true,
    // These two are to make the background transparent
    cardStyle: {
      backgroundColor: 'transparent',
    },
    transitionConfig: () => ({
      containerStyle: {
        backgroundColor: 'transparent',
      },
    }),

```

**Comment by SehanRathnayake** [comment]
This issue is still existing for nested stack navigators  
"react-navigation": "4.0.10",
