### ISSUE TITLE
createMaterialTopTabNavigator renders wrong view on IOS

### ISSUE THREAD

**Issue by jchavezjs** [react-navigation/react-navigation#5754]
### Current Behavior

createMaterialTopTabNavigator renders the first screen that is defined in the routes, even when i define a diferent initialRouteName. Nevertheless, the tab defined in initialRouteName is focused, even when the screen rendered is not the right one. This only happens to me on IOS, Android seems to work well. Also, i tried using the createMaterialTopTabNavigator from react-navigation-tabs for testing, and it worked well on IOS.

This is my code

```
const RewardsTabs = createMaterialTopTabNavigator(
  {
    MyRewards: {
      screen: MyRewards,
      navigationOptions: {
        title: 'RECOMPENSAS',
      },
    },
    Offers: {
      screen: Offers,
      navigationOptions: {
        title: 'OFERTAS',
      },
    },
    Favourites: {
      screen: Favourites,
      navigationOptions: {
        title: 'FAVORITOS',
      },
    },
  },
  {
    initialRouteName: 'Offers',
    tabBarOptions: {
      activeTintColor: '#979CA8',
      inactiveTintColor: '#B7BAC7',
      scrollEnabled: true,
      style: {
        backgroundColor: '#FFF',
        elevation: 0,
        borderBottomColor: '#DFE2EF',
        borderBottomWidth: 1,
      },
      labelStyle: {
        fontSize: 14,
        fontWeight: '500',
      },
      indicatorStyle: {
        backgroundColor: '#00D395',
        height: 1,
        marginBottom: -1,
      },
    },
  }
);
```
In my case, the screen from MyRewards is rendered but the tab that is focused is Offers.

### Expected Behavior

createMaterialTopTabNavigator have to render the screen that is defined in the routes for the initialRouteName. 

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.5.1
| react-native     | 0.59.2
| node             |  8.10.0
| npm or yarn      | 4.6.1

**Comment by eriveltonelias** [comment]
hi! please make your code runnable either on https://snack.expo.io without any extraneous code

**Comment by yanush** [comment]
same happened to me after upgrading to react-native 0.59.2
initialRouteName stopped working completely

**Comment by jchavezjs** [comment]
> 
> 
> hi! please make your code runnable either on https://snack.expo.io without any extraneous code

I can't reproduce the bug on snack. Maybe the react native version that it uses is diferent from 0.59.2 but I create a totally new project just with the tabs and it happened again with an IPhone. This is the project repo.

https://github.com/jchavezjs/react-navigation-bug-test

Also, i did a capture from the app running on the device that shows how it looks this bug.

![index](https://user-images.githubusercontent.com/11198281/55259786-43244580-522c-11e9-8685-4d5ef493bcfd.jpg)

**Comment by Victor-Jansson** [comment]
Same behavior here, android works, but not ios.

"react-native": "0.59.1"
"react-navigation": "3.5.1"

**Comment by brentvatne** [comment]
try installing react-navigation-tabs@2.0.0-alpha and importing `createMaterialTopNavigator` from there

**Comment by yanush** [comment]
@brentvatne, trying to do so failed, since I'm using a custom bar component and now it can't find this.props.position.interpolate :(

**Comment by Victor-Jansson** [comment]
@brentvatne using react-navigation-tabs@2.0.0-alpha solves this issue on iOS. Thanks.

**Comment by brentvatne** [comment]
@yanush - you'll need to update to use the new reanimated api, so rather than using `position.interpolate` you need to import `interpolate` from reanimated (https://github.com/kmagiera/react-native-reanimated) and then do `interpolate(position, { ... stuff ... })`

**Comment by yanush** [comment]
@brentvatne - thanks, it worked, though for some reason the performance is not as good as it used to be. After clicking a tab there is a small delay before it's actually focused. Are they planning on fixing this issue in the near future?

**Comment by brentvatne** [comment]
@yanush - can you provide a reproducible example and post an issue on http://github.com/react-navigation/react-navigation-tabs about that?

**Comment by yanush** [comment]
I think the problem is that it lazy loads tabs content each time I move to them, instead of loading everything beforehand

**Comment by macrozone** [comment]
fyi: the same error happens on older versions. I am using 2.6.2, because i need the animated older `createTabNavigator`. 

I try now to upgrade react-navigation...

**Comment by osdnk** [comment]
@brentvatne 
I don't feel that `react-navigation-tabs` is ready for production. Feeling of this component has to be polished a bit and I want to stay now with 1.x. Could you suggest some workaround?

/@jinchung

**Comment by brentvatne** [comment]
@osdnk - not totally sure what the best workaround would be, @satya164 would be the best person to answer that question

**Comment by levibuzolic** [comment]
Same issue here, can't replicate on snack as they're still targeting 0.57.x investigating if I can get a fix happening in user-land.

**Comment by levibuzolic** [comment]
I believe I've found the cause and I've opened a PR on `react-native-tab-view` which fixes the issue in my test case: https://github.com/react-native-community/react-native-tab-view/pull/762

**Comment by viralS-tuanlv** [comment]
this issues did reslove? i had the same here

**Comment by yanush** [comment]
it's still not solved for me with the latest versions

**Comment by osdnk** [comment]
This issue is resolved. If you face the problem, please assure that you have the newest 1.x version in `yarn.lock`.

@brentvatne, @satya164 
Can we close it?

**Comment by satya164** [comment]
I just released a new version of the `react-navigation` package with updated dependency on `react-navigation-tabs`. So now you just have to update `react-navigation` in your dependencies.

In the long run, you should migrate your code to use the latest version of [`react-navigation-tabs`](https://github.com/react-navigation/tabs) directly instead.

I'm closing the issue since it's fixed. Please let me know if you still experience it with the latest version and I will re-open it.

**Comment by yanush** [comment]
Finally fixed! thanks!

**Comment by Sotatek-HieuDuong** [comment]
it's still not solved for me with the latest versions

**Comment by osdnk** [comment]
@Sotatek-HieuDuong 
What's the version of `react-navigation-tabs` and `react-native-tab-view` in your `yarn.lock`?

**Comment by Sotatek-HieuDuong** [comment]
> @Sotatek-HieuDuong
> What's the version of `react-navigation-tabs` and `react-native-tab-view` in your `yarn.lock`?

react-navigation-tabs@~1.1.3:
  version "1.1.3"
  resolved "https://registry.yarnpkg.com/react-navigation-tabs/-/react-navigation-tabs-1.1.3.tgz#72dded7764cffc6b1de029cd1f0468da3976ed30"
  integrity sha512-MP3QIiIPA1YNqAsL0x55tU+KoTXHrBucicR6eA5aC1wgkk9Hh++DzS34pXrC6u5LZ59MWu7FWjrSFS1aDxqHyg==
  dependencies:
    hoist-non-react-statics "^2.5.0"
    prop-types "^15.6.1"
    react-lifecycles-compat "^3.0.4"
    react-native-tab-view "^1.4.0"

**Comment by truongnv91** [comment]
I's still get error with latest versions react navigation and react-navigation-tabs
