### ISSUE TITLE
Cannot read property 'Direction' of undefined

### ISSUE THREAD

**Issue by pssgo** [react-navigation/react-navigation#6071]
### Current Behavior

![image](https://user-images.githubusercontent.com/16378134/61041635-40c5b000-a405-11e9-9bc2-d9a4e1479c3b.png)

### Expected Behavior

i hope it's work..

### How to reproduce

```javascript
class DetailsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        <Text>Details!</Text>
      </View>
    );
  }
}

class HomeScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        {/* other code from before here */}
        <Button
          title="Go to Details"
          onPress={() => this.props.navigation.navigate('Details')}
        />
      </View>
    );
  }
}

class SettingsScreen extends React.Component {
  render() {
    return (
      <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
        {/* other code from before here */}
        <Button
          title="Go to Details"
          onPress={() => this.props.navigation.navigate('Details')}
        />
      </View>
    );
  }
}

const HomeStack = createStackNavigator({
  Home: HomeScreen,
  Details: DetailsScreen,
});

const SettingsStack = createStackNavigator({
  Settings: SettingsScreen,
  Details: DetailsScreen,
});

export default createAppContainer(createBottomTabNavigator(
  {
    Home: HomeStack,
    Settings: SettingsStack,
  },
  {
    /* Other configuration remains unchanged */
  }
));
```

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 3.11.0
| react-native     |0.60.0
| node             |v10.16.0
| npm or yarn      | 6.9.0/1.16.0

**Comment by satya164** [comment]
Please check the latest docs: https://reactnavigation.org/docs/en/getting-started.html

**Comment by corpsyal** [comment]
Follow this instructions, worked for me after hours of research: https://www.youtube.com/watch?v=NcQhDlC7hT8

**Comment by satya164** [comment]
It's sad that people are making and linking to youtube videos to fix the issue instead of sending a PR to the documentation which would help everyone.

**Comment by pssgo** [comment]
This does not solve my problem. I follow the configuration of the official website and the official example does not work

**Comment by erdong0604** [comment]
I also watched the YouTube video upstairs, but it didn't solve my problem.

**Comment by erdong0604** [comment]
I think I've solved it . All you need to do is change react-native.config.js 
```
module.exports = {
  dependencies: {
    "react-native-gesture-handler": {
      platforms: {
        ios: null
      }
    }
  }
};

```

**Comment by erdong0604** [comment]
> Follow these instructions, worked for me after hours of research: https://www.youtube.com/watch?v=NcQhDlC7hT8



> This does not solve my problem. I follow the configuration of the official website and the official example does not work

Look at the following answers

**Comment by aguilared** [comment]
I follow the configuration of the official website and the official example does not work,   

**do not work!!!**
### Cannot read property 'Direction' of undefined
<unknown>
... /node_modules/react-native-gesture-handler/Directions.js:3:38

**Comment by aguilared** [comment]
Ready!

 "postinstall": "jetify"
  },
  "dependencies": {
    "react": "16.8.6",
    "react-native": "0.60.3",
    "react-native-gesture-handler": "^1.3.0",
    "react-navigation": "^3.11.1"

"jetifier": "^1.6.2",

**Comment by satya164** [comment]
@aguilared you say official docs, but that's exactly what official docs say, to install jetifier and add it to post install

**Comment by Methodician** [comment]
@satya164 the docs linked above? I can't find anything about jetifier... I guess I'll have to click that youtube video.

**Comment by satya164** [comment]
@Methodician latest React Native cli includes jetifier, so I have removed it from the docs

**Comment by Methodician** [comment]
It seems like denial. Like others I have followed the official docs, I uninstalled and reinstalled, Updated packages... pretty sure there's a real problem.

If it sheds any light on the issue: react-navigation DOES work for me, if I'm only using "createBottomTabNavigator" but as soon as I try to use "createStackNavigator" alone or in combo, I get that error.

Until there is a fix or work-around I can't see any reason to keep banging at it.

**Comment by satya164** [comment]
@Methodician I have updated docs like 5 times after finding issues, and tried in a freshly inited project to test that it works.

I have talked to the React Native CLI team several times on how to make this easier for users which resulted in the latest version include jetifier by default. I removed jetifier from the docs after CLI team told me that it's no longer needed, and I'll add it back since seems people are still on older version of CLI. I am aware that it's a real problem.

Meanwhile nobody has sent a PR to update the docs even if they managed to to fix the issue and haven't provided a repro which actually shows the issue. So let's not blame each other.

Anyway, you need to install jetifier: https://github.com/mikehardy/jetifier if you're on latest React Native (0.60). If you're on older RN version, the docs are up-to-date on that since we haven't changed anything about it.

**Comment by ilmatic** [comment]
@satya164 I'm unclear on what the proposed solution is here. Do I just install jetifier? I did that, but I am still seeing the error. I'm only running in iOS simulator, and it seems like the youtube video is for Android?

On react-native 0.60.4, react-native-cli 2.0.1, iOS simulator 10.2.1.

Thanks!

**Comment by satya164** [comment]
@ilmatic you need to run `pod install` as mentioned in the docs

**Comment by ilmatic** [comment]
Hopefully this can be helpful for people running into the same thing: nothing in the above thread helped for me (working on iOS Simulator), the solve was adding this line to `ios/Podfile`:

`pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'`

followed by running `pod install`

**Comment by aguilared** [comment]
Create a new app, RN 0.60.4 and follow the steps to install react-navigation

**Comment by devika7** [comment]
> pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'

Hi, After performing this, I am getting this error in my Xcode -->'React/RCTEventDispatcher.h' file not found 

Did you face this issue? How to solve it?

**Comment by aguilared** [comment]
Update Reacts to:   "react": "16.8.6",
"react-native": "0.60.4",


Lucks

**Comment by smallGear** [comment]
It needs a rebuild after adding libraries to reflect that changes.
react-native run-android (ios)

**Comment by sugaE** [comment]
> > pod 'RNGestureHandler', :podspec => '../node_modules/react-native-gesture-handler/RNGestureHandler.podspec'
> 
> Hi, After performing this, I am getting this error in my Xcode -->'React/RCTEventDispatcher.h' file not found
> 
> Did you face this issue? How to solve it?


It's mostlg because xcode cannot find React.

try:
add correct react path to search headers path of projects you drag into(that is RNGestureHandler.xcodeproj)
and you also need to:
add  $(SRCROOT)/../node_modules/react-native-gesture-handler/ios/ to the Header Search Paths in your original project's Build Settings

**Comment by BasappaBaligar** [comment]
I resolved this issue by linking the npm module with react native using the command
react-native link react-native-gesture-handler
and rerunning the app using 
react-native run-ios
