### ISSUE TITLE
TextInput copy/paste not working with react-navigation + react-native-screens

### ISSUE THREAD

**Issue by zgajo** [react-navigation/react-navigation#6201]
### Current Behavior

- What code are you running and what is happening?
Cannot copy / cut / paste from TextInput component when using React Navigation with react-use-screens

- Code that doesn't work
```
import React from 'react';
import {Button, ScrollView, Text} from 'react-native';
import {TextInput} from 'react-native-gesture-handler';
import {
  createAppContainer,
  createStackNavigator,
  createSwitchNavigator,
} from 'react-navigation';

// After removing useScreens everything works as it should have
import {useScreens} from 'react-native-screens';
useScreens();

class DetailsScreen extends React.Component {
  render() {
    return (
      <ScrollView>
        <TextInput placeholder="Test copy/paste" />
        <Text>Details Screen</Text>
        <Button
          title="Go to Details... again"
          onPress={() => this.props.navigation.navigate('Details')}
        />
      </ScrollView>
    );
  }
}

export default createAppContainer(
  createStackNavigator({
    Details: DetailsScreen,
  }),
);

```

- Screenshot of screen that doesn't work
[http://imgbox.com/S3twL3Hk](http://imgbox.com/S3twL3Hk)

### Expected Behavior

- What do you expect should be happening?
Should have possibility to paste text into TextInput or Copy/Cut text from TextInput
- Include a screenshot if it makes sense.
[http://imgbox.com/Crxg4SOq](http://imgbox.com/Crxg4SOq)

### How to reproduce

- I've tried the similar code with `react-router-native` and `useScreens()` and everything works fine

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation |^3.11.1
| react-native     |0.60.5
| react-native-screens             |^1.0.0-alpha.23
| react-native-gesture-handler      |^1.3.0
| react-native-reanimated      |^1.2.0

**Comment by dylanbartley** [comment]
also having this issue

**Comment by yitelee** [comment]
same here

**Comment by mistikk** [comment]
same issue on rn 61.2

**Comment by dimonchik-com** [comment]
same issue on rn 0.61.5

**Comment by dimonchik-com** [comment]
I found a fix for my problem 
`<TextInput style={[styles.input, {height: Platform.OS == 'android' ? 40 : 20}]} ... />`

**Comment by zgajo** [comment]
This issue is solved with `react-native-screens: 2.0.0-beta.13`

**Comment by jjg77** [comment]
@zgajo 
I upgraded to the version you stated, but the problem still persists.

**Comment by huylvdev** [comment]
In componentDidMount or useeffect(with hook) add :
 setTimeout(() => {
            this.setState({ editable: true });
        }, 100);

**Comment by cashon1120** [comment]
I tried the above solution but its not working in my project, but I found a new way,  like this:
...
const [height, setHeight] = useState(35);
useEffect(() => {
  setHeight(40);
}, []);
...
return <TextInput  style={[styles.input, {height}]} />
