### ISSUE TITLE
TypeScript not recognizing the type of tabBarOptions in react-navigation-tabs

### ISSUE THREAD

**Issue by thepost** [react-navigation/react-navigation#6308]
I've tried this with `react-navigation` 4.0.0 and 4.0.5, both don't recognize the type of the `tabBarOptions` prop even if I define it as `BottomTabBarOptions`.

Sample code:
```
const bottomTabBarOptions: BottomTabBarOptions = {
  showLabel: false,
  style: {
    borderTopWidth: 0,
  },
};

const test = createBottomTabNavigator(
  {
    Screen1: { screen: Screen1 },
    Screen2: { screen: Screen2 }
  },
  {
    tabBarOptions: bottomTabBarOptions,
  }
);
```

### Current Behavior

Error logged:
```
Argument of type '{ tabBarOptions: BottomTabBarOptions; }' is not assignable to parameter of type 'CreateNavigatorConfig<{}, NavigationTabRouterConfig, Partial<NavigationBottomTabOptions>, NavigationTabProp<NavigationRoute<NavigationParams>, any>>'.
  Object literal may only specify known properties, and 'tabBarOptions' does not exist in type 'CreateNavigatorConfig<{}, NavigationTabRouterConfig, Partial<NavigationBottomTabOptions>, NavigationTabProp<NavigationRoute<NavigationParams>, any>>'.
```

### Expected Behavior

- If the tabBarOptions are defined as type BottomTabBarOptions, it's expected that the type should be recognized.

### Your Environment

| software         | version
| ---------------- | -------
| react-navigation | 4.0.5
| react-native     | 0.59.9
| node             | 11.9.0
| npm or yarn      | 6.8.0

**Comment by satya164** [comment]
https://github.com/react-navigation/tabs/issues/163

**Comment by thepost** [comment]
Why was this closed @satya164? The linked issue didn't have a resolution, as there are still people having this issue in the most recent version. I am one of them.

**Comment by satya164** [comment]
Because there is another issue open in the relevant repo.. There is no point of having 2 issues open.

**Comment by thepost** [comment]
That issue was closed when I opened this one. I see that it's been reopened now.

**Comment by EternalChildren** [comment]
It's still have some small problem. don't have the safeAreaInset property in tabBarOptions
![image](https://user-images.githubusercontent.com/27210994/65102487-cc5b4e80-d9fd-11e9-9cf3-612bb0fb6da6.png)

**Comment by thepost** [comment]
Likewise, there's been no solution around this yet. Both here or in [this issue](https://github.com/react-navigation/tabs/issues/163). Also, the issue in here is so different that it warrants re-opening.

@satya164 I can get on a call with you if you want to understand the issue completely.

**Comment by satya164** [comment]
> Likewise, there's been no solution around this yet

I have already fixed all of the issues that were mentioned in the linked report and this report in the latest version.

It's very hard for me to follow issues in comments of closed issues. If you're still facing a problem with the latest version or I missed something, please open a new bug report with code to repro in https://github.com/react-navigation/tabs.

Sorry, I don't want a call. A bug report with the list of issues instead of comments and is good enough for me to understand.

**Comment by thepost** [comment]
Code to reproduce is provided above. If you tried testing it before closing it due to a completely unrelated issue that you thought was related, you would see that it's reproducible. What should happen is to simply reopen this issue. Do you want me to create a duplicate issue with exactly the same content? 

I'm sorry @satya164, what is the normal process for creating issues in this library? I took time out to document it well, if there is another process outside the normal Github issue logging conventions, please document it.

**Comment by satya164** [comment]
@thepost the error message you posted is `Object literal may only specify known properties, and 'tabBarOptions' does not exist in type` which is the same as https://github.com/react-navigation/tabs/issues/163#issuecomment-531452999 and is fixed in https://github.com/react-navigation/tabs/commit/9b2086d15d62e25f59e7e010ecb01c08e065bd7b

anyway, I see that you're using a type `BottomTabBarOptions` which we don't export. I cannot reproduce the issue with the code you provided because I don't know what's in this type. you need to provide a runnable demo/at least full code as per the issue template where I can reproduce the issue.

please just open a new issues in https://github.com/react-navigation/tabs with a proper repro and I'll debug it. there's no reason to argue with me here. it just wastes both of our time and doesn't contribute to actually fixing the issue.

**Comment by alejomendoza** [comment]
Still get the issue with "@react-navigation/bottom-tabs": "^6.0.0-next.20"

**Comment by seyaobey-dev** [comment]
There is still an issue with types 3 years after the ticket was opened!! I cannot follow the [official tutorial of this component](https://reactnavigation.org/docs/bottom-tab-navigator/) using typescript: it is very hard to use this component in typescript. Please can you fix this issue?
