### ISSUE TITLE
react-native-safe-area-context reports incorrect bottom inset for some Android devices

### ISSUE THREAD

**Issue by JuanLuisGarciaBorrego** [react-navigation/react-navigation#7251]
**The tab menu, when I create the android apk, adds a lower margin on android devices. With expo client it does not generate it. (Attached images).**

```
const MainStack = createBottomTabNavigator(
    {
        Home: {
            screen: HomeScreen,
        },
      ....
    }, {
        defaultNavigationOptions: ({navigation}) => ({
            tabBarIcon: ({focused, tintColor}) =>
                <GetTabBarIcon navigation={navigation} focused={focused} tintColor={tintColor}/>,
        }),
        tabBarOptions: {
            activeTintColor: '#D84859',
            inactiveTintColor: '#212529',
            labelStyle: {
                fontFamily: 'InterUI_regular'
            },
            tabStyle: {      /*I've tried to force the height 45, padding, margin: 0*/
                backgroundColor: '#fff',
                height: 45,
                padding: 0,
                margin:0,
                bottom: 0,
                flex: 1,
                width: '100%',
            },
            style: {
                width: '100%',
                height: 45,
                padding: 0,
                bottom: 0,
                margin: 0,
                backgroundColor: '#fff',
                overflow: 'hidden'
            }
        },
        initialRouteName: 'Inicio'
    }
);
```
**Image error (.APK)**
![Screenshot_2020-02-15-20-20-45-44](https://user-images.githubusercontent.com/5416367/74594068-5aca0f80-5032-11ea-8ed5-de689e5b0407.jpg)

**Image ok (expo client local) **
![Screenshot_2020-02-15-20-22-54-763_host exp exponent](https://user-images.githubusercontent.com/5416367/74594078-7f25ec00-5032-11ea-828c-b6936d793ece.jpg)

| software                     | version |
| ---------------------------- | ------- |
| Android               |  9 Xiaomi  note 7 and 9 Xiaomi MI A1
| react-navigation             | 4.1.1 (I've updated it to this version and it doesn't work either)
| react-navigation-tabs        | ^2.7.0 (I've updated it to this version and it doesn't work either)
| react-native-reanimated      | ~1.2.0
| react-native-gesture-handler | ~1.3.0
| react-native-screens         | ~1.0.0-alpha.23
| react-native                 | https://github.com/expo/react-native/archive/sdk-35.0.0.tar.gz
| expo                         |  ^35.0.0
| node                         | v12.12.0
| yarn                  | 1.19.1

**Comment by Ashoat** [comment]
I am seeing this with `@react-navigation/native@5.2.6` and `@react-navigation/bottom-tabs@5.4.1`

**Comment by Ashoat** [comment]
I'm not yet sure about the header stuff, but the issue with `bottom-tabs` is occurring because `react-native-safe-area-context` is reporting an incorrect value for the `bottom` inset on my Android device. I am admittedly testing on a pretty ancient device.

Worth noting that the issue is not specific to release builds. Will continue investigating.

**Comment by Ashoat** [comment]
This issue was resolved by upgrading to `react-native-safe-area-context@1.0.0`. Background [here](https://github.com/th3rdwave/react-native-safe-area-context/issues/39).

**Comment by schieck0** [comment]
Any other tips for those who still have the problem on react-native-safe-area-context@1.0.0 and 1.0.2?
