### ISSUE TITLE
navigation.navigate() not enforcing params in TypeScript

### ISSUE THREAD

**Issue by oli-laban** [react-navigation/react-navigation#7936]
**Current Behavior**

I've followed the guide [here](https://reactnavigation.org/docs/typescript#type-checking-screens) to set up type checking, but `navigation.navigate()` isn't enforcing that the params are passed to the screen.

```
// rootStackNavigator.tsx

export type RootStackParamList = {
  Login: undefined;
  Leads: undefined;
  WebView: { url: string };
};

...
```

```
// screens/Login/index.ts

interface Props {
  navigation: StackNavigationProp<RootStackParamList, 'Login'>;
}

class Login extends Component<Props> {
  ...
}
```

Calling `navigation.navigate('WebView')` in the above component does not error.

**Expected Behavior**

`navigation.navigate('WebView')` should error if the param `{ url: 'something' }` is not passed.

Typing for the navigate method:
```
navigate<RouteName extends keyof ParamList>(...args: ParamList[RouteName] extends undefined | any ? [RouteName] | [RouteName, ParamList[RouteName]] : [RouteName, ParamList[RouteName]]): void;
```

The `ParamList[RouteName] extends undefined | any` conditional check in the typing is obviously returning `true` and the type that is being enforced on the call is:
```
navigate<"WebView">(...args: ["WebView"] | ["WebView", {
    url: string;
}]): void
```

I would expect the resulting type to be:
```
navigate<"WebView">(...args: ["WebView", {
    url: string;
}]): void
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | iOS 13.3
| @react-navigation/native       | 5.1.3
| @react-navigation/stack        | 5.2.8
| react-native-gesture-handler   | 1.6.1
| react-native-safe-area-context | 0.7.3
| react-native-screens           | 2.4.0
| react-native                   | 0.61.5
| node                           | 12.12.0
| npm or yarn                    | yarn 1.19.1
| typescript | 3.8.3

**Comment by Miyou** [comment]
I had the same issue. Solved it by changing the typing for the navigate method to:
`navigate<RouteName extends keyof ParamList>(...args: ParamList[RouteName] & undefined extends never ? [RouteName, ParamList[RouteName]] : [RouteName] | [RouteName, ParamList[RouteName]]): void;`

I'm very new to typescript and I would have thought that simply removing the `| any` in the original typing would have worked, but it seems that for example `string | undefined` does not extend undefined for some reason.

So the way I solved it was by doing an intersection with undefined and seeing if that extends never. If the type we intersect with undefined is not undefined or a union with undefined the result will be never. Since no type extends never except itself, this should work. It seems right to me, and some simple testing confirms it, but I'm still not 100% sure since I'm so new to Typescript. If someone can confirm that this is correct I'm happy to create a PR.

**Comment by Miyou** [comment]
Ah, so apparently undefined extends a type which is a union with undefined. So a simpler solution is:
`navigate<RouteName extends keyof ParamList>(...args: undefined extends ParamList[RouteName] ?  [RouteName] | [RouteName, ParamList[RouteName]] : [RouteName, ParamList[RouteName]]): void;`

Again, it would be good if someone with more experience with Typescript could confirm that this is the right way to do it.

**Comment by satya164** [comment]
Duplicate of #6931

**Comment by Miyou** [comment]
> Duplicate of #6931

Sorry but it's not a duplicate. That issue refers to a problem with the other function overload of navigate. It would be great if you could confirm that my solution would be a good way to fix this issue. In that case I'd be happy to submit a PR.

**Comment by rtrembecky** [comment]
@Miyou maybe you have better chance of having this fixed by submitting a PR right away 😄 I'd like to see some movement here too 🙏

**Comment by mleister97** [comment]
Issue still present. I can pass any variables to the .navigate function without even a warning.

**Comment by Miyou** [comment]
@satya164 This can be closed now that @jeanregisser PR was merged
