### ISSUE TITLE
Attempted to assign to readonly property @react-navigation/native

### ISSUE THREAD

**Issue by Angelk90** [react-navigation/react-navigation#8125]
**Current Behavior**

Hi @satya164 , The code can be found at the following link: https://snack.expo.io/NpIwPZ!uo

It is based on an example of the component: `react-native-animated-tabbar`
But it seems that the problem is on the module `@react-navigation/native`, which on snack.expo does not seem to work properly, giving me the following error:

```
Device: (857:881) Attempted to assign to readonly property.
  Evaluating module://@react-navigation/native.js
  Evaluating module://App.tsx.js
  Loading module://App.tsx
```

**Expected Behavior**

The code is very simple, I expect to be able to move between the various screens.

**Comment by LoganWlv** [comment]
Getting the exact same error on the demo snack example in the getting started docs for Stack https://snack.expo.io/@loganwlv/14d924

Following the getting started guide with an expo configuration, ends up in a blank screen with no logs but I guess it's the same issue. 

Reproductible doing : 

**1) expo init      (blank js)**
**2) install deps :** 
- npm install @react-navigation/native
- expo install react-native-gesture-handler react-native-reanimated react-native-screens react-native-safe-area-context @react-native-community/masked-view
- npm install @react-navigation/stack

**3) Make a simple App.js template :** 

```
import React from 'react';
import { StyleSheet, View } from 'react-native';
import { NavigationContainer } from '@react-navigation/native';
import { createStackNavigator } from '@react-navigation/stack';
import FirstComponent from './FirstComponent';
import SecondComponent from './SecondComponent';

const Stack = createStackNavigator();

export default function App() {
  return (
    <View style={styles.container}>
      <NavigationContainer initialRouteName='FirstComponent'>
        <Stack.Navigator>
          <Stack.Screen
            name='FirstComponent'
            component={FirstComponent}
            options={{ title: 'FirstComponent' }}
          />
          <Stack.Screen
            name='SecondComponent'
            component={SecondComponent}
            options={{ title: 'SecondComponent' }}
          />
        </Stack.Navigator>
      </NavigationContainer>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});

```

**Comment by Angelk90** [comment]
@LoganWlv : I'm not understanding, neither the example posted nor the code seem to work on snack.expo.

**Comment by LoganWlv** [comment]
basically just saying that there is the same issue on the Stack example

**Comment by Angelk90** [comment]
@LoganWlv : So there is no solution is a module bug, right?

**Comment by Angelk90** [comment]
@satya164 : Is there any news regarding this issue?

**Comment by raajnadar** [comment]
Tested and found the issue is fixed in the latest version of react navigation v5.

**Comment by Angelk90** [comment]
@LoganWlv , @raajnadar :

It still doesn't work, the problems persist, do I have to open another issue?

Link: https://snack.expo.io/6aeFxqz4C
 ```
Device: (857:881) Unable to resolve module 'module://@react-navigation/stack.js'
  Evaluating module://@react-navigation/stack.js
  Evaluating module://App.tsx.js
  Loading module://App.tsx
```

**Comment by raajnadar** [comment]
It does not happen when you use latest version in the package.json.

**Comment by joaopiopedreira** [comment]
Sorry for reopening but I'm on the react navigation versions below and still having this issue.

```json
"@react-navigation/bottom-tabs": "^5.11.8",
"@react-navigation/native": "^5.9.3",
"@react-navigation/stack": "^5.14.3",
```
the error stack is:
```
TypeError: Attempted to assign to readonly property.

This error is located at:
    in Home (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at BottomTabView.tsx:55)
    in SceneContent (at BottomTabView.tsx:171)
    in RCTView (at View.js:34)
    in View (at ResourceSavingScene.tsx:68)
    in RCTView (at View.js:34)
    in View (at ResourceSavingScene.tsx:63)
    in ResourceSavingScene (at BottomTabView.tsx:165)
    in RCTView (at View.js:34)
    in View (at src/index.native.js:123)
    in ScreenContainer (at BottomTabView.tsx:145)
    in SafeAreaProviderCompat (at BottomTabView.tsx:144)
    in BottomTabView (at createBottomTabNavigator.tsx:45)
    in BottomTabNavigator (at BottomTabNavigator.tsx:25)
    in BottomTabNavigator (at SceneView.tsx:122)
    in StaticContainer
    in StaticContainer (at SceneView.tsx:115)
    in EnsureSingleNavigator (at SceneView.tsx:114)
    in SceneView (at useDescriptors.tsx:153)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:245)
    in RCTView (at View.js:34)
    in View (at CardContainer.tsx:244)
    in RCTView (at View.js:34)
    in View (at CardSheet.tsx:33)
    in ForwardRef(CardSheet) (at Card.tsx:573)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:555)
    in PanGestureHandler (at GestureHandlerNative.tsx:13)
    in PanGestureHandler (at Card.tsx:549)
    in RCTView (at View.js:34)
    in View (at createAnimatedComponent.js:165)
    in AnimatedComponent (at createAnimatedComponent.js:215)
    in ForwardRef(AnimatedComponentWrapper) (at Card.tsx:544)
    in RCTView (at View.js:34)
    in View (at Card.tsx:538)
    in Card (at CardContainer.tsx:206)
    in CardContainer (at CardStack.tsx:620)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:84)
    in MaybeScreen (at CardStack.tsx:613)
    in RCTView (at View.js:34)
    in View (at Screens.tsx:54)
    in MaybeScreenContainer (at CardStack.tsx:495)
    in CardStack (at StackView.tsx:462)
    in KeyboardManager (at StackView.tsx:458)
    in SafeAreaProviderCompat (at StackView.tsx:455)
    in RCTView (at View.js:34)
    in View (at StackView.tsx:454)
    in StackView (at createStackNavigator.tsx:87)
    in StackNavigator (at navigation/index.tsx:84)
    in RootNavigator (at navigation/index.tsx:68)
    in EnsureSingleNavigator (at BaseNavigationContainer.tsx:409)
    in ForwardRef(BaseNavigationContainer) (at NavigationContainer.tsx:91)
    in ThemeProvider (at NavigationContainer.tsx:90)
    in ForwardRef(NavigationContainer) (at navigation/index.tsx:64)
    in Navigation (at App.tsx:80)

```

**Comment by raajnadar** [comment]
I tested the snack example from the https://reactnavigation.org/docs/stack-navigator/#api-definition website it is working perfectly for me.

I clicked on the try this example on snack.

**Comment by joaopiopedreira** [comment]
Thank you @raajnadar, I'll give it a go
