### ISSUE TITLE
Drawer Navigation Snack for 5x does not work.

### ISSUE THREAD

**Issue by SeanRenet** [react-navigation/react-navigation#8232]
Drawer Navigation Snack for 5x does not work.

Device: (862:881) Unable to resolve module 'module://fbjs/lib/invariant.js'
  Evaluating module://fbjs/lib/invariant.js
  Evaluating module://react-native-reanimated.js
  Evaluating module://@react-navigation/drawer.js
  Evaluating module://App.js.js
  Loading module://App.js

**Comment by raajnadar** [comment]
in package.json of snack add `"fbjs": "1.0.0"`  or `"fbjs": " latest"`this should fix the issue.

**Comment by SeanRenet** [comment]
@raajnadar I would love to pretend I know what you are talking about, but adding that line to the snack didn't seem to fix it.  Is there anyway for you guys to fix it since its the official documentation snack?

**Comment by raajnadar** [comment]
Actually snack is made by expo. And I read that solution in their forums. So you should create a new issue in https://github.com/expo/snack-web
