### ISSUE TITLE
currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput

### ISSUE THREAD

**Issue by SConaway** [react-navigation/react-navigation#8457]
**Current Behavior**

I am using a compound navigation setup. It goes `NavigationContainer > AuthStack`. AuthStack consists of `TabStack` as well as a few screens. If I am in one of those screens and swipe back (on iOS, native gesture), I get this warning: 
````
currentlyFocusedField is deprecated and will be removed in a future release. Use currentlyFocusedInput
````

I think it might be caused by the RN release candidate, so if it is, this would be a good warning to address. This seems similar to #8414, but I don't know if they're related.

**Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS                 |13.6 latest beta|
| @react-navigation/native       |^5.5.1|
| @react-navigation/stack        |^5.5.1|
| react-native-gesture-handler   |^1.6.1|
| react-native-safe-area-context |^3.0.5|
| react-native-screens           |^2.8.0|
| react-native                   |0.63.0-rc.1|
| expo                           |N/A|
| node                           |14.4.0|
| yarn                    |2.0.0-rc.33|

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/react-navigation/commit/35d6b9e3a4a28a59b3b11a67acbf7753d41705ae

**Comment by slauzinho** [comment]
@satya164 Is it possible to also fix for v4?

**Comment by hharrari-labs** [comment]
@satya164 Is it possible to also fix for v3 ? ^^
Thank you !

**Comment by italomlp** [comment]
> @satya164 Is it possible to also fix for v4?

I managed to do it with [patch-package](https://www.npmjs.com/package/patch-package). Basically, in your `react-navigation` files from `node_modules` you need to replace all:
```
TextInput.State.currentlyFocusedField();
```

occurrences with : 
```
TextInput.State.currentlyFocusedInput
    ? TextInput.State.currentlyFocusedInput()
    : TextInput.State.currentlyFocusedField();
```
and run
> npx patch-package

This command will create all patches for the files changes on `node_modules`. Also, you need to add patch-package as a dependency and run it after post install (most likely [`patch-package` readme](https://github.com/ds300/patch-package#readme) said):

- for **npm**
> npm i patch-package

- for **yarn**
> yarn add patch-package postinstall-postinstall

- and in your `package.json`:
```
"scripts": {
+  "postinstall": "patch-package"
 }
```

More details in https://github.com/ds300/patch-package

**Comment by SConaway** [comment]
Or, if you use yarn, you could let yarn natively handle the patch. You can even use `patch-package` to create the patch, then just apply via changing the "version" in `package.json`:  `"package-x-y-z": "patch:package-x-y-z@a.b.c#./patches/package-x-y-z.patch"`, just change the names / versions.

**Comment by ming436534** [comment]
More precisely, after changing the files, use ```npx patch-package react-navigation/@react-navigation/native``` to create a patch

**Comment by raul-madrigal** [comment]
I'm using the latest versions and I'm still getting this error, anyone with a solution?

```
    "react": "16.13.1",
    "react-native": "0.63.2",
    "@react-navigation/compat": "5.2.4",
    "@react-navigation/core": "5.12.2",
    "@react-navigation/native": "5.7.2",
    "@react-navigation/routers": "5.4.10",
    "@react-navigation/stack": "5.8.0",
```

**Comment by Maskedman99** [comment]
I'm also facing  the same issue on latest version
```
    "@react-native-community/masked-view": "0.1.10",
    "@react-navigation/native": "^5.7.2",
    "@react-navigation/stack": "^5.5.1",
    "react": "16.13.1",
    "react-native": "0.63.2",
    "react-native-gesture-handler": "1.7.0",
    "react-native-reanimated": "1.9.0",
    "react-native-safe-area-context": "^3.1.1",
    "react-native-screens": "2.9.0",
```

**Comment by Eric-Andrade** [comment]
Facing same issue 

   ```
 "react": "^16.13.1",
    "react-native": "^0.63.2",
    "react-native-gesture-handler": "^1.7.0",
    "react-navigation": "^4.4.0",
    "react-navigation-stack": "^2.8.2",
    "react-navigation-tabs": "^2.9.0",
```

**Comment by watadarkstar** [comment]
I fixed it for 4.x here: https://github.com/react-navigation/react-navigation/pull/8684

**Comment by xclidongbo** [comment]
> @satya164 Is it possible to also fix for v3 ? ^^
> Thank you !

v3 修复了吗?

**Comment by alanyong91** [comment]
any news on this ?

**Comment by jsbls** [comment]
🚀 4.4.1 was released earlier today on [npmjs](https://www.npmjs.com/package/react-navigation). There are also releases for stack, tabs, etc.

**Comment by longmaba** [comment]
Still the same issue guys
  "@react-navigation/native": "^5.7.6",
    "@react-navigation/stack": "^5.9.3",

**Comment by tanmoythander** [comment]
I am using,
```
"react-native": "0.63.3",
"react-navigation": "4.4.2",
"react-navigation-drawer": "2.3.3",
"react-navigation-stack": "2.8.4"
```
which has solved my issue.
But i had `native-base@2.13.14` installed, which was also causing same issue. So I had to use this patch using [patch-package](https://github.com/ds300/patch-package),

```
diff --git a/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js b/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
index 9e71a3a..8867003 100644
--- a/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
+++ b/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
@@ -339,7 +339,9 @@ function KeyboardAwareHOC(
           keyboardSpace -= _KAM_DEFAULT_TAB_BAR_HEIGHT
         }
         this.setState({ keyboardSpace })
-        const currentlyFocusedField = TextInput.State.currentlyFocusedField()
+        const currentlyFocusedField = TextInput.State.currentlyFocusedInput
+					? findNodeHandle(TextInput.State.currentlyFocusedInput())
+					: TextInput.State.currentlyFocusedField()
         const responder = this.getScrollResponder()
         if (!currentlyFocusedField || !responder) {
           return
@@ -462,7 +464,9 @@ function KeyboardAwareHOC(
     }
 
     update = () => {
-      const currentlyFocusedField = TextInput.State.currentlyFocusedField()
+			const currentlyFocusedField = TextInput.State.currentlyFocusedInput
+				? findNodeHandle(TextInput.State.currentlyFocusedInput())
+				: TextInput.State.currentlyFocusedField()
       const responder = this.getScrollResponder()
 
       if (!currentlyFocusedField || !responder) {

```

So if you still face the issue due to `native-base@2.13.14`, add a file named, **@codler+react-native-keyboard-aware-scroll-view+1.0.0.patch** inside the directory **patches** and paste the contents above. Add `"postinstall": "patch-package"` under **scripts** in **package.json**. Then install [patch-package](https://github.com/ds300/patch-package),
```
npm i patch-package
```

**Comment by watadarkstar** [comment]
@longmaba What version of react-navigation are you using?

**Comment by longmaba** [comment]
> @longmaba What version of react-navigation are you using?

@watadarkstar I'm using the 2 packages:
```"@react-navigation/native": "^5.7.6",
"@react-navigation/stack": "^5.9.3",```

**Comment by aviemore** [comment]
Still same issue

```
 "@react-navigation/bottom-tabs": "^5.9.2",
 "@react-navigation/native": "^5.7.6",
 "@react-navigation/stack": "^5.9.3",
```

**Comment by kalyanijamunkar10** [comment]
i added following plugin and fixed it.
```
  "@react-navigation/core": "^5.13.1",
    "@react-navigation/native": "^5.8.1",
    "@react-navigation/stack": "^5.11.0",
```

**Comment by AnurajDev** [comment]
Any fixes for version  3.11.1 ?

**Comment by ajaytheone1994** [comment]
we can fixed it by replacing currnetylyFocusedField to currentlyFocusedInput.
 
![WhatsApp Image 2020-11-23 at 19 18 11](https://user-images.githubusercontent.com/44599669/99969614-c068da80-2dc0-11eb-8a7a-22fe85c3ad23.jpeg)

**Comment by comanzanares** [comment]
for `"react-navigation": "^3.11.0"`
`yarn patch-package @react-navigation/native` worked for me just in case someone is getting this message (after making the changes in `node_modules`)
<img width="793" alt="Screen Shot 2020-12-01 at 16 48 06" src="https://user-images.githubusercontent.com/13682575/100789280-00e5db00-33f5-11eb-8730-714f5b30f2f3.png">

**Comment by AnurajDev** [comment]
For version **3.11.1**, the answers of @ajaytheone1994  and @comanzanares  helped me.

Found the usage of **currentlyFocusedField** under **_node_modules/@react-navigation/native/src/createKeyboardAwareNavigator.js._**

Replaced all instances of **currentlyFocusedField** with **currentlyFocusedInput**.

Then did the patching by **yarn patch-package @react-navigation/native**.

The warning vanished.

Thank you guys!

**Comment by luatnd** [comment]
> for `"react-navigation": "^3.11.0"`
> `yarn patch-package @react-navigation/native` worked for me just in case someone is getting this message (after making the changes in `node_modules`)
> <img alt="Screen Shot 2020-12-01 at 16 48 06" width="793" src="https://user-images.githubusercontent.com/13682575/100789280-00e5db00-33f5-11eb-8730-714f5b30f2f3.png">

I got this message too, because I forgot to save the file after making changes

**Comment by patricktan98** [comment]
> I am using,
> 
> ```
> "react-native": "0.63.3",
> "react-navigation": "4.4.2",
> "react-navigation-drawer": "2.3.3",
> "react-navigation-stack": "2.8.4"
> ```
> 
> which has solved my issue.
> But i had `native-base@2.13.14` installed, which was also causing same issue. So I had to use this patch using [patch-package](https://github.com/ds300/patch-package),
> 
> ```
> diff --git a/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js b/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
> index 9e71a3a..8867003 100644
> --- a/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
> +++ b/node_modules/@codler/react-native-keyboard-aware-scroll-view/lib/KeyboardAwareHOC.js
> @@ -339,7 +339,9 @@ function KeyboardAwareHOC(
>            keyboardSpace -= _KAM_DEFAULT_TAB_BAR_HEIGHT
>          }
>          this.setState({ keyboardSpace })
> -        const currentlyFocusedField = TextInput.State.currentlyFocusedField()
> +        const currentlyFocusedField = TextInput.State.currentlyFocusedInput
> +					? findNodeHandle(TextInput.State.currentlyFocusedInput())
> +					: TextInput.State.currentlyFocusedField()
>          const responder = this.getScrollResponder()
>          if (!currentlyFocusedField || !responder) {
>            return
> @@ -462,7 +464,9 @@ function KeyboardAwareHOC(
>      }
>  
>      update = () => {
> -      const currentlyFocusedField = TextInput.State.currentlyFocusedField()
> +			const currentlyFocusedField = TextInput.State.currentlyFocusedInput
> +				? findNodeHandle(TextInput.State.currentlyFocusedInput())
> +				: TextInput.State.currentlyFocusedField()
>        const responder = this.getScrollResponder()
>  
>        if (!currentlyFocusedField || !responder) {
> ```
> 
> So if you still face the issue due to `native-base@2.13.14`, add a file named, **@codler+react-native-keyboard-aware-scroll-view+1.0.0.patch** inside the directory **patches** and paste the contents above. Add `"postinstall": "patch-package"` under **scripts** in **package.json**. Then install [patch-package](https://github.com/ds300/patch-package),
> 
> ```
> npm i patch-package
> rm -rf node_modules ios/Pods
> npm install && cd ios && pod install && cd ..
> ```

After implemented warning and error still persist shown, any solution?

**Comment by SConaway** [comment]
admins, should this issue be locked? Just wondering since things seem to be getting a bit off topic here and the issue has been solved for ~6 months.

**Comment by patricktan98** [comment]
> admins, should this issue be locked? Just wondering since things seem to be getting a bit off topic here and the issue has been solved for ~6 months.

Please do provide the "solution" that you mentioned.
I'm still encountering this issue.

**Comment by shahidcodes** [comment]
I am using latest @react-nativigation version, still facing the problem

``` "@react-navigation/bottom-tabs": "^5.3.1",
    "@react-navigation/native": "^5.2.1",
    "@react-navigation/stack": "^5.2.16",

**Comment by zoobibackups** [comment]
same issue. 
```
` "dependencies": {
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/clipboard": "^1.5.1",
    "@react-native-community/cookies": "^5.0.1",
    "@react-native-community/google-signin": "^5.0.0",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-native-community/picker": "^1.8.1",
    "@react-native-community/slider": "^3.0.3",
    "@react-native-firebase/app": "^10.7.0",
    "@react-native-firebase/auth": "^10.7.0",
    "@react-navigation/bottom-tabs": "^5.11.8",
    "@react-navigation/drawer": "^5.12.2",
    "@react-navigation/material-bottom-tabs": "^5.3.14",
    "@react-navigation/native": "^5.9.3",
    "@react-navigation/stack": "^5.14.3",
    "@twotalltotems/react-native-otp-input": "^1.3.11",
    "faker": "^5.4.0",
    "google-libphonenumber": "^3.2.16",
    "install": "^0.13.0",
    "lottie-react-native": "^3.5.0",
    "native-base": "^2.15.2",
    "npm": "^7.5.4",
    "react": "16.13.1",
    "react-native": "0.63.4",
    "react-native-admob": "^2.0.0-beta.6",
    "react-native-admob-native-ads": "^0.4.1",
    "react-native-android-notification-listener": "^2.0.0",
    "react-native-android-recyclerview": "^1.0.2",
    "react-native-animatable": "^1.3.3",
    "react-native-awesome-pin": "^1.3.1",
    "react-native-call-detection": "^1.9.0",
    "react-native-contacts": "^6.0.4",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "^1.9.0",
    "react-native-image-crop-picker": "^0.36.0",
    "react-native-image-slider-box": "^1.0.12",
    "react-native-intent-launcher": "^0.2.1",
    "react-native-largelist": "^1.2.12",
    "react-native-largelist-v3": "^3.0.15",
    "react-native-linear-gradient": "^2.5.6",
    "react-native-material-menu": "^1.2.0",
    "react-native-modal": "^11.6.1",
    "react-native-navigation-bar-color": "^2.0.1",
    "react-native-neomorph-shadows": "^1.1.2",
    "react-native-otp-textinput": "0.0.8",
    "react-native-paper": "^4.7.1",
    "react-native-permissions": "^3.0.1",
    "react-native-ratings": "^8.0.1",
    "react-native-reanimated": "^1.13.2",
    "react-native-responsive-fontsize": "^0.5.0",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^3.1.9",
    "react-native-screens": "^2.15.2",
    "react-native-share": "^6.0.0",
    "react-native-shared-element": "^0.7.0",
    "react-native-shimmer-placeholder": "^2.0.7",
    "react-native-splash-screen": "^3.2.0",
    "react-native-spring-scrollview": "^2.0.23",
    "react-native-star-rating": "^1.1.0",
    "react-native-svg": "^12.1.0",
    "react-native-vector-icons": "^8.0.0",
    "react-native-virtualized-waterfall": "^1.2.2",
    "react-navigation-shared-element": "^5.0.0-alpha1",
    "realm": "^10.2.0",
    "reanimated-bottom-sheet": "^1.0.0-alpha.22",
    "recyclerlistview": "^3.0.5",
    "rn-fetch-blob": "^0.12.0"
  },`
```
