### ISSUE TITLE
The App is crashing if you navigate very faster (Android)

### ISSUE THREAD

**Issue by felire** [react-navigation/react-navigation#8493]
**Current Behavior**

The only thing I am doing is navigating to one screen and then go fast back and repeat that behaviour very very quickly. If you do that very quickly you will get this error at some point:

![Screen Shot 2020-06-22 at 09 26 18](https://user-images.githubusercontent.com/11776795/85287569-d584ba80-b46a-11ea-9612-43e7a0c0d29c.png)

That is one of the errors I've got. I'd received other but I can't recreate it. But I proved that in a Release version and the app crashed. 

**Expected Behavior**

The expected behaviour should be that nothing strange happens and you can still navigating in your app like always

**How to reproduce**

- Having a Stack with two screens. You will have to navigate to one screen and then goBack faster to the other screen, and then repeat this behaviour very faster.

IMPORTANT: I'm using a CustomHeader and in the CustomHeader I'm using the `useNavigation` hook to execute the `goBack` method when the user press in the back button.

**Stack Trace**

```
Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException
Unable to execute operation dispatchViewManagerCommand on view with tag: 289, since the view does not exists
com.facebook.react.uimanager.UIImplementation.assertViewExists

com.facebook.react.uimanager.UIImplementation.assertViewExists (UIImplementation.java:836)
com.facebook.react.uimanager.UIImplementation.dispatchViewManagerCommand (UIImplementation.java:713)
com.facebook.react.uimanager.UIManagerModule.dispatchCommand (UIManagerModule.java:706)
com.facebook.react.uimanager.UIManagerModule.dispatchViewManagerCommand (UIManagerModule.java:689)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:151)
com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
android.os.Looper.loop (Looper.java:214)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:226)
java.lang.Thread.run (Thread.java:764)
```

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | Android
| @react-navigation/native       | ^5.5.1
| @react-navigation/stack        | ^5.5.1
| react-native-gesture-handler   | ^1.6.1
| react-native-safe-area-context |^3.0.2
| react-native-screens           | ^2.8.0
| react-native                   | 0.62.2
| expo                           | no
| node                           |
| npm or yarn                    | yarn

**Comment by felire** [comment]
It exist after updating

**Comment by raajnadar** [comment]
1st This is a warning so it won't be a problem.

2nd why are you navigating fastly? An user using your app won't do this.

3rd Did you try to reproduce this warning in production build?

**Comment by satya164** [comment]
> But I proved that in a Release version and the app crashed.

Please provide a stack trace of the crash

**Comment by codGmer** [comment]
I also get this problem, but not the error shown. I just get a blank screen.

**Comment by felire** [comment]
@satya164 Here is the Stacktrace in release mode:

```
Fatal Exception: com.facebook.react.uimanager.IllegalViewOperationException
Unable to execute operation dispatchViewManagerCommand on view with tag: 289, since the view does not exists
com.facebook.react.uimanager.UIImplementation.assertViewExists

com.facebook.react.uimanager.UIImplementation.assertViewExists (UIImplementation.java:836)
com.facebook.react.uimanager.UIImplementation.dispatchViewManagerCommand (UIImplementation.java:713)
com.facebook.react.uimanager.UIManagerModule.dispatchCommand (UIManagerModule.java:706)
com.facebook.react.uimanager.UIManagerModule.dispatchViewManagerCommand (UIManagerModule.java:689)
java.lang.reflect.Method.invoke (Method.java)
com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:151)
com.facebook.react.bridge.queue.NativeRunnable.run (NativeRunnable.java)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:27)
android.os.Looper.loop (Looper.java:214)
com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run (MessageQueueThreadImpl.java:226)
java.lang.Thread.run (Thread.java:764)
```

**Comment by felire** [comment]
It's not the same warning that I publish before, this is another thing

**Comment by felire** [comment]
@satya164 The issue was fixed? Or why did you closed?

**Comment by iagormoraes** [comment]
this issue still happens on the native 5.9.0 and stack 5.13.0.

**Comment by ShivamKumar2002** [comment]
Facing this issue even now. https://hastebin.com/lajeduxede here is log
