### ISSUE TITLE
Deep links to unopened application fail with 'navigation' object hasn't been initialized yet

### ISSUE THREAD

**Issue by timfpark** [react-navigation/react-navigation#8537]
**Current Behavior**

- What code are you running and what is happening?

I have added deep link support to my application that looks like this:

```
const ROUTING = {
  prefixes: ['https://my.app', 'myapp://'],
  config: {
    Main: {
      screens: {
        Explore: {
          path: 'map/:latitude/:longitude/:zoom',
          parse: {
            latitude: Number,
            longitude: Number,
            zoom: Number,
          },
        },
      },
    },
  },
};

...

export default function App() {
 
  return (
      <NavigationContainer linking={ROUTING} fallback={<Text>Loading...</Text>}>
            ....
      </NavigationContainer>
  );
}
```

**Expected Behavior**

- What do you expect should be happening?

This code works great when the application is already launched but when I try to use a deep link to launch the unlaunched application it fails with:

```
Error: The 'navigation' object hasn't been initialized yet. This might happen if you don't have a navigator mounted, or if the navigator hasn't finished mounting. See https://reactnavigation.org/docs/navigating-without-navigation-prop#handling-initialization for more details.

dispatch
    BaseNavigationContainer.tsx:140:10
listener
    useLinking.native.tsx:107:25
emit
    EventEmitter.js:189:10
__callFunction
    MessageQueue.js:425:19
__guard$argument_0
    MessageQueue.js:112:6
__guard
    MessageQueue.js:373:10
callFunctionReturnFlushedQueue
    MessageQueue.js:111:4
callFunctionReturnFlushedQueue
    [native code]:0
```

**How to reproduce**

I can provide a minimal repo application if this is not a known issue.  Please let me know.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | 13
| @react-navigation/native       | 5.6.1
| react-native                   |0.62
| expo                           |
| node                           |
| npm or yarn                    |

**Comment by timfpark** [comment]
Yes it still happens on upgrade

**Comment by JoeLeung32** [comment]
Still on @react-navigation/native version 5.7.0

At this version, I got below results:

Android:
- [x] Trigger by Push Notification
- [x] Trigger by In-App
- [x] Trigger by `xcrun simctl openurl booted ....`
- [x] Trigger by web page <a>

iOS:
- [x] Trigger by Push Notification
- [x] Trigger by In-App
- [ ] Trigger by `xcrun simctl openurl booted ....`
- [ ] Trigger by web page <a>

```
    "@react-native-community/async-storage": "1.11.0",
    "@react-native-community/masked-view": "0.1.10",
    "@react-native-community/netinfo": "5.9.4",
    "@react-navigation/bottom-tabs": "5.7.0",
    "@react-navigation/core": "5.12.0",
    "@react-navigation/native": "5.7.0",
    "@react-navigation/routers": "5.4.9",
    "@react-navigation/stack": "5.7.0",
    "react": "16.13.1",
    "react-native": "0.63.0",
```

**Comment by Vizards** [comment]
I have the same problem. Application "cold start" seems to trigger the `onReady` callback immediately. The 'navigation' object hasn't been initialized yet.

**Comment by JoeLeung32** [comment]
> I have the same problem. Application "cold start" seems to trigger the `onReady` callback immediately. The 'navigation' object hasn't been initialized yet.

No idea on that, I have not experience on native app, It seem like a problem inside the logic?

Coz @timfpark problem is no need to setup useRef() or useState()
Reference this part https://reactnavigation.org/docs/deep-linking/#universal-links

**Comment by randytorres** [comment]
I'm having the same issue, any updates on this?

**Comment by javascripter** [comment]
Having the same issue. Opening a notification when the app is unopened results in an immediate crash.
```
    "@react-navigation/bottom-tabs": "^5.6.1",
    "@react-navigation/compat": "^5.1.28",
    "@react-navigation/material-top-tabs": "^5.2.12",
    "@react-navigation/native": "^5.6.1",
    "@react-navigation/stack": "^5.6.2",
```

**Comment by javascripter** [comment]
After upgrading to RN 0.63.2 with the below dependencies, the crash problem seems to have been resolved!
```
    "@react-navigation/bottom-tabs": "^5.8.0",
    "@react-navigation/compat": "^5.2.5",
    "@react-navigation/material-top-tabs": "^5.2.16",
    "@react-navigation/native": "^5.7.3",
    "@react-navigation/stack": "^5.9.0",
```

**Comment by gilbertl** [comment]
I'm having similar problems: 

universal links work when the app is in background, but doesn't resolve if the app is going on its first launch.

I'm already on the latest packages mentioned by @javascripter 

I've considered hacking it and setting a timer to trigger the opening of the URL manually, but I'm not sure how to do this either. Linking.openURL('XXX') will open the universal link in the browser instead of my app.

**Comment by satya164** [comment]
Closing since you didn't provide a repro to debug the issue.

**Comment by danielrhodes** [comment]
I'm also seeing this. Was not able to replicate it locally, only in the App Store.

**Comment by danielrhodes** [comment]
Found the bug:

https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/useLinking.native.tsx#L108


```
        if (state) {
          const action = getActionFromState(state);

          if (action !== undefined) {
            navigation.dispatch(action);
          } else {
            navigation.resetRoot(state);
          }
}
```

If action is not defined, and the `navigation.dispatch` is called before the navigation is finished loading, it will result in this error.

If you replace the above code with this:
```
          if (action !== undefined) {
            const dangerousState = navigation.dangerouslyGetState();
            if (!dangerousState) {
              setTimeout(() => {
                navigation.dispatch(action);
              }, 150);
            } else {
              navigation.dispatch(action);
            }
          } else {
            navigation.resetRoot(state);
          }
        }
```

It works.

cc: @satya164 

One can replicate this by calling `Linking.openUrl(<some url scheme for your app>)`

**Comment by gilbertl** [comment]
> Found the bug:
> 
> https://github.com/react-navigation/react-navigation/blob/main/packages/native/src/useLinking.native.tsx#L108
> 
> ```ts
>         if (state) {
>           const action = getActionFromState(state);
> 
>           if (action !== undefined) {
>             navigation.dispatch(action);
>           } else {
>             navigation.resetRoot(state);
>           }
> }
> ```
> 
> If action is defined, and the `navigation.dispatch` is called before the navigation is finished loading, it will result in this error.
> 
> If you replace the above code with this:
> 
> ```ts
>           if (action !== undefined) {
>             const dangerousState = navigation.dangerouslyGetState();
>             if (!dangerousState) {
>               setTimeout(() => {
>                 navigation.dispatch(action);
>               }, 150);
>             } else {
>               navigation.dispatch(action);
>             }
>           } else {
>             navigation.resetRoot(state);
>           }
>         }
> ```
> 
> It works. One can replicate this by calling `Linking.openUrl(<some url scheme for your app>)` somewhere very early on in your app's startup.
> 
> cc: @satya164

Is there a plan to fix this? This bug is currently marked as "closed."

**Comment by teamzz111** [comment]
Please re open this issue.

**Comment by Svarto** [comment]
Have the same issue, hope there is some fix to this?

**Comment by davidmoss** [comment]
Updating to the latest @react-navigation/native fixes this since 5.8.6: https://github.com/react-navigation/react-navigation/commit/4c2379cec1e661aa132002fd1c50909ea64cb983

**Comment by Svarto** [comment]
@davidmoss looking at that commit, it would only add a warning that the navigation is not yet initialized? 

I will double check which version I'm using and test again, but if it was only that commit you referenced I wouldn't say that's a fix - it's just printing out to console the issue we are already discussing in this thread. Thanks a lot for the effort here, I'm super grateful, just trying to find a way to make navigating when opening a cold app from a deep link / notification work consistently.

**Comment by maxckelly** [comment]
Has anyone found a solution for this? I'm still facing the issue and on `"@react-navigation/native": "^5.9.3",`

**Comment by Svarto** [comment]
Same here!

**Comment by phatmann** [comment]
This is still happening and the timeout trick did not solve it for me.
