### ISSUE TITLE
Stack > Tab > Stack does not work in Web

### ISSUE THREAD

**Issue by simoneb** [react-navigation/react-navigation#9228]
I am trying to implement something exactly the same as what is described in [this page](https://reactnavigation.org/docs/screen-options-resolution/#setting-parent-screen-options-based-on-child-navigators-state) which has:

- a root stack navigator
- the first screen of the stack navigator is a tab navigator
- each of the tab screens is a stack

[This is the snack](https://snack.expo.io/?platform=android&name=Screen%20options%20with%20nested%20navigators%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2C%40react-navigation%2Fbottom-tabs%40%5E5.8.0%2C%40react-navigation%2Fdrawer%40%5E5.9.0%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.16%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.16%2C%40react-navigation%2Fnative%40%5E5.7.3%2C%40react-navigation%2Fstack%40%5E5.9.0%2Creact-native-paper%40%5E4.0.1%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-gesture-handler%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E2.15.1&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Freorganized-navigators.js) that's linked from the docs and you can see that in Web it's completely broken (all screens are empty), while it works on devices.

[Also tried updating packages](https://snack.expo.io/@simoneb/screen-options-with-nested-navigators-%7C-react-navigation?platform=android&name=Screen%20options%20with%20nested%20navigators%20%7C%20React%20Navigation&dependencies=%40expo%2Fvector-icons%40*%2C%40react-native-community%2Fmasked-view%40*%2C%40react-navigation%2Fbottom-tabs%40%5E5.8.0%2C%40react-navigation%2Fdrawer%40%5E5.9.0%2C%40react-navigation%2Fmaterial-bottom-tabs%40%5E5.2.16%2C%40react-navigation%2Fmaterial-top-tabs%40%5E5.2.16%2C%40react-navigation%2Fnative%40%5E5.7.3%2C%40react-navigation%2Fstack%40%5E5.9.0%2Creact-native-paper%40%5E4.0.1%2Creact-native-reanimated%40*%2Creact-native-safe-area-context%40*%2Creact-native-gesture-handler%40*%2Creact-native-screens%40*%2Creact-native-tab-view%40%5E2.15.1&sourceUrl=https%3A%2F%2Freactnavigation.org%2Fexamples%2F5.x%2Freorganized-navigators.js), same issue.

| software                       | version |
| ------------------------------ | ------- |
| @react-navigation/native       |  5.9.0

**Comment by elijahkim** [comment]
I'm running into the same issue. The actual component seems to be rendering then quickly getting clobbered by another div.

**Comment by satya164** [comment]
It should be fixed in latest version of `@react-navigation/bottom-tabs`

**Comment by simoneb** [comment]
> It should be fixed in latest version of `@react-navigation/bottom-tabs`

do you think it's fixed in material-bottom-tabs too?

**Comment by simoneb** [comment]
Also, based on the linked issue in the changelog, I see the original reporter that it's not fixed. https://github.com/react-navigation/react-navigation/issues/9225#issuecomment-764841389

**Comment by satya164** [comment]
> do you think it's fixed in material-bottom-tabs too

I haven't seen any issue in material-bottom-tabs. But also it's just a wrapper over React Native Paper's Bottom Navigation, so if you have any issue, you should open an issue there.

> Also, based on the linked issue in the changelog, I see the original reporter saying that it's not fixed.

Their comment was before the commit and release as you can see on GitHub. Also they reported the issue in drawer, but tested by updating bottom-tabs.

**Comment by simoneb** [comment]
Okay thanks for the clarification. I'll try it out.

**Comment by elijahkim** [comment]
Upgrading `@react-navigation/bottom-tabs` got me sorted. Thanks!
