### ISSUE TITLE
Invisible View created by ResourceSavingScene on Bottom Tabs

### ISSUE THREAD

**Issue by app-rc** [react-navigation/react-navigation#9241]
**Current Behavior**
Hi everyone,

- What code are you running and what is happening?
I set up, a small menu, with 2 bottom tabs.

When you scroll on MENU_1, all works fine. If you click MENU_2 and comme back MENU_1, scroll is no more working.
It seems that an hidden View is hover with overflow: hidden, position absolute, top 0, left 0, bottom 0 right 0...

When I inspect > BottomTabNavigator > BottomTabView > ResourceSavingScene > View > RCTView.

All packages are up to date :(

**Expected Behavior**

- What do you expect should be happening?
To scroll again on Menu_1 after tab switch.

**How to reproduce**
https://snack.expo.io/@app-rc/tabs

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
expo: 40.0.1
"expo-constants": "~9.3.1",
"react-native-screens": "~2.15.0",
"@react-navigation/native": "5.9.2",
"@react-navigation/bottom-tabs": "5.11.5",
"react-native-safe-area-context": "3.1.9"

node: v12.20.1
npm: 6.14.11

Thank you for your help :)

**Comment by app-rc** [comment]
Yes issue is still existing after upgrade to last version !

**Comment by SebastianDaehnrich** [comment]
i have the same issue

**Comment by klandell** [comment]
Same issue here

**Comment by thimo1** [comment]
Same with @react-navigation/drawer v5.12.0, after downgrading to 5.11.5, issue is gone.

**Comment by Maxime-Fleurant** [comment]
i use @react-navigation/bottom-tabs": "^5.11.5" and i have the same probleme

**Comment by Maxime-Fleurant** [comment]
@react-navigation/bottom-tabs downgraded to 5.11.3 worked for me

**Comment by frabanca** [comment]
Hi everyone!

The issue should not be closed: downgrading is not a solution in my opinion. 
I've this packages:

```json
"@react-navigation/drawer": "^5.12.2",
"@react-navigation/native": "^5.9.2",
"@react-navigation/stack": "^5.14.1",
```

I've the same problem. I've tried to install v . 5.11.5, v. 5.11.3 and also v. 5.10.9 of `@react-navigation/drawer`, but the issue remains.

The issue presents only on Android (v. 9), both iOS simulator (iPhone 12) and iPhone (tested on a iPhone 6S) works fine.

Any suggestion for some solution and/or some workaround?

Cheers

**Comment by app-rc** [comment]
Fixed in 5.11.6 !

**Comment by frabanca** [comment]
> Fixed in 5.11.6 !

Awesome! I'll wait for the release. Thanks

**Comment by frabanca** [comment]
Hi!

I suppose you are talking about v. 5.11.6 of "@react-navigation/bottom-tabs", but as per my previous post I don't have it installed. 
I only have: 

```json
 "@react-navigation/drawer": "^5.12.6",
  "@react-navigation/native": "^5.9.2",
  "@react-navigation/stack": "^5.14.1",
```

and the problem persists.

Any idea on how to fix?

**Comment by frabanca** [comment]
I've checked how you fixed this bug in v. 5.11.6 of "@react-navigation/bottom-tabs", and I applied the same fix in "@react-nativation/drawer". 

Quick-and-dirty fix: add this `pointerEvents="box-none"` to the "Animated.View" element in `node_modules/@react-navigation/drawer/src/views/Drawer.tsx` on row 695.

Final result:

```tsx
        <Animated.View
            accessibilityViewIsModal={isOpen && drawerType !== 'permanent'}
            removeClippedSubviews={Platform.OS !== 'ios'}
            onLayout={this.handleDrawerLayout}
            style={[
              styles.container,
              {
                transform: [{ translateX: drawerTranslateX }],
                opacity: this.drawerOpacity,
              },
              drawerType === 'permanent'
                ? // Without this, the `left`/`right` values don't get reset
                  isRight
                  ? { right: 0 }
                  : { left: 0 }
                : [
                    styles.nonPermanent,
                    isRight ? { right: offset } : { left: offset },
                    { zIndex: drawerType === 'back' ? -1 : 0 },
                  ],
              drawerStyle as any,
            ]}
            pointerEvents="box-none"
          >
            {renderDrawerContent({ progress })}
          </Animated.View>
```

This fix the problem also on "@react-nativation/drawer".

**Comment by bigcupcoffee** [comment]
@satya164 mind bumping bottom-tabs version on npm? It's just `5.11.6` for me 
![image](https://user-images.githubusercontent.com/24373206/105710009-2f78c180-5f1f-11eb-9b1b-f6baa2089e67.png)

**Comment by satya164** [comment]
@bigcupcoffee can you try 5.11.7?

**Comment by bigcupcoffee** [comment]
Works fine now 👍

**Comment by ndotie** [comment]
> > I've checked how you fixed this bug in v. 5.11.6 of "@react-navigation/bottom-tabs", and I applied the same fix in "@react-nativation/drawer".
> > Quick-and-dirty fix: add this `pointerEvents="box-none"` to the "Animated.View" element in `node_modules/@react-navigation/drawer/src/views/Drawer.tsx` on row 695.
> > Final result:
> > ```tsx
> >         <Animated.View
> >             accessibilityViewIsModal={isOpen && drawerType !== 'permanent'}
> >             removeClippedSubviews={Platform.OS !== 'ios'}
> >             onLayout={this.handleDrawerLayout}
> >             style={[
> >               styles.container,
> >               {
> >                 transform: [{ translateX: drawerTranslateX }],
> >                 opacity: this.drawerOpacity,
> >               },
> >               drawerType === 'permanent'
> >                 ? // Without this, the `left`/`right` values don't get reset
> >                   isRight
> >                   ? { right: 0 }
> >                   : { left: 0 }
> >                 : [
> >                     styles.nonPermanent,
> >                     isRight ? { right: offset } : { left: offset },
> >                     { zIndex: drawerType === 'back' ? -1 : 0 },
> >                   ],
> >               drawerStyle as any,
> >             ]}
> >             pointerEvents="box-none"
> >           >
> >             {renderDrawerContent({ progress })}
> >           </Animated.View>
> > ```
> > 
> > 
> > This fix the problem also on "@react-nativation/drawer".
> 
> _UPDATE_
> 
> Previous dirty-fix doesn't really solve the problem. The following works better in my case.
> 
> _Prerequisites_
> 
> * Install those packages:
> 
> ```json
> "@react-navigation/drawer": "^5.12.3",
> "@react-navigation/native": "^5.9.2",
> "@react-navigation/stack": "^5.14.2",
> ```
> 
> _How to fix_
> 
> * Go to /node_modules/@react-navigation/drawer/src/views/ResourceSavingScene.tsx
> * Search for "pointerEvents", you should find 3 occurrences. In each of this occurrence, replace 'none' with 'box-none'. Example: `pointerEvents={isVisible ? 'auto' : 'box-none'}`
> * Rebuild your app
> 
> I can see some line of code with this comment "box-none doesn't seem to work properly on Android", maybe this solution depends on the Android phone OS?. In my case it was an Android 10 on a Samsung S9+.

Thanks this works for me
