### ISSUE TITLE
Screen flickering when go back on iOS

### ISSUE THREAD

**Issue by hunterbmt** [react-navigation/react-navigation#9530]
**Current Behavior**

After upgrade to react navigation 4.4.4 and react-native-screen 3.0.0, sometimes when I go back from stack navigation, the screen will be flickered with previous screen content.
It doesn't happen all the time and won't happen if I disable detachPreviousScreen so it could be something relating to optimization?

**Expected Behavior**

Screen transition back smoothly, doesn't flickering

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |
| react-navigation               | 4.4.4
| react-navigation-stack         | 2.10.4
| react-navigation-tabs          | 2.11.0
| react-native-reanimated        | 2.1.0
| react-native-gesture-handler   | 1.10.2
| react-native-safe-area-context |
| react-native-screens           | 3.0.0
| expo                           | 41
| npm or yarn                    |yarn

**Comment by hunterbmt** [comment]
Upgraded to react-navigation-tabs 2.11.1, the issue still happened

**Comment by tinymobile** [comment]
I have the same problem.  Never happened with 4.x before but i had to upgrade to latest react native version and now it's happening across all my projects.  Any one have a solution to this other than upgrading to react navigation 5?

**Comment by KurtMar** [comment]
See https://github.com/react-navigation/react-navigation/issues/9256 which also lists related issues. I'm not quite sure what the problem is. I've just disabled react-native-screens, which mitigates the problem for me, but is not a long term solution.

**Comment by xuho** [comment]
I have same issue.
```
"react-native": "0.64.0",
 "react-native-screens": "^3.1.1",
  "react-navigation": "^4.4.4",
  "react-navigation-stack": "^2.10.4",
  "react-navigation-tabs": "^2.11.0",
```

**Comment by hunterbmt** [comment]
> I have same issue. And after read react-navigation document again, I see I do not `import 'react-native-gesture-handler';` on top of `index.js` file in root project folder.
> 
> ```
> "react-native": "0.64.0",
> "react-native-screens": "^3.1.1",
> "react-navigation": "^4.4.4",
> "react-navigation-stack": "^2.10.4",
> "react-navigation-tabs": "^2.11.0",
> ```

I could confirm this not fixing the problem

**Comment by hunterbmt** [comment]
> I have the same problem. Never happened with 4.x before but I had to upgrade to latest react native version and now it's happening across all my projects. Any one have a solution to this other than upgrading to react navigation 5?

could you confirm if upgrading to 5.x version will fix the problem ?

**Comment by tinymobile** [comment]
No, @hunterbmt , unfortunately I can't confirm that upgrading to 5.x will fix the problem. That was going to be my next port of call to try, but it's a very big change to all of my apps, so i'm looking for another solution.

It did fix it for me on one of my apps when I disabled react-native-screens (3.1.1) using this at the top of my app.js:

import { enableScreens } from 'react-native-screens';
enableScreens(false);

But on my other apps this caused a new error:
Exception thrown while executing UI block: unrecognized selector sent to instance.

**Comment by hunterbmt** [comment]
> No, @hunterbmt , unfortunately I can't confirm that upgrading to 5.x will fix the problem. That was going to be my next port of call to try, but it's a very big change to all of my apps, so i'm looking for another solution.
> 
> It did fix it for me on one of my apps when I disabled react-native-screens (3.1.1) using this at the top of my app.js:
> 
> import { enableScreens } from 'react-native-screens';
> enableScreens(false);
> 
> But on my other apps this caused a new error:
> Exception thrown while executing UI block: unrecognized selector sent to instance.

will try to upgrade to 5.x to see if we able to get rip of the problem. Disable react-native-screens won't be an ideal solution since it comes with a huge performance impact.
I will update if upgrading to 5.x makes any help.

**Comment by tinymobile** [comment]
@hunterbmt - I seem to have found a solution accidentally - in order to try and fix the exception bug I was getting by disabling Screens, I tried installing the earlier version of screens (2.18.0).  And that fixed the flicker - even without disabling screens!

Not 100% ideal as I don't know if any unknown consequences of having a slightly older version, but seems the issue is in react-native-screens@3.1.1 and if you can live with a slightly earlier version of screens while we wait for that to get fixed, then it might be a lot easier than upgrading to nav5.x.

What I did to install earlier version of screens:

npm install react-native-screens@2.18.1
cd ios && pod install && cd ..

I need to test it a bit more to see if any hidden implications, but wanted to let you know as you said you were going to embark on nav5.x upgrade which is a big code change.

**Comment by hunterbmt** [comment]
Thanks for your suggestion @tinymobile, unfortunately, we are using Expo, so downgrading is not an option. Plus the 2.18.x version contains a more critical issue - the app could be frozen and crash when you put the app to the background, then active it back and swipe back.
3.x fixed the problem but introduce the flickering.
Since it seems to be react-native-screen issue, I'm not that convince upgrading react-navigation to 5.x will help but we do have a possibility that the issue happened due to the combination of react-navigation screen structures and react-native-screen optimization, so I will test out the upgrade and let you know.

**Comment by lc3t35** [comment]
I have the same kind of jumping around behaviour 

![ScreenFlow](https://user-images.githubusercontent.com/921372/117580378-f6dcac80-b0f7-11eb-8bd2-0c16ec12e6a7.gif)

```
"@react-navigation/native": "^5.9.4",
"@react-navigation/stack": "^5.14.4",
"react-native-gesture-handler": "~1.10.2",
"react-native-screens": "~3.0.0",
"react-native-safe-area-context": "3.2.0",
"react-native": "0.63.4",
"expo": "^41.0.1",
```

**Comment by RyanTG** [comment]
This issue persists for me on 3.0.0, 3.2.0, and 2.18.1. And it wasn't present prior to upgrading to react navigation 4.4.4. I don't know the ins and outs of these things, but it kinda makes it seem like it's a react nav 4.4.4 issue. Are people seeing it on other react navigation releases?

**Comment by RyanTG** [comment]
This issue is probably going to fizzle and close if we can't get a snack repro. Is anyone here skilled at snacking to do it? I will try, but no promises.

**Comment by RyanTG** [comment]
I found this repo that someone made for the[ same issue](https://github.com/software-mansion/react-native-screens/issues/905) on the react-native-screen https://github.com/alexandrius/screens-flicker

**Comment by atkristin** [comment]
Downgrading to react-native-screens to 2.15.2 fixes the issue

**Comment by lc3t35** [comment]
@atkristin how can you downgrade with expo ?

**Comment by RyanTG** [comment]
Downgrading to 2.15.2 worked for me, as well.

@lc3t35 In package.json change it to `"react-native-screens": "2.15.2",` and then npm install. If you have React Navigation 5.x it might not be so easy because I saw someone say that screens is bundled with it...?

**Comment by mickeylam** [comment]
I've got flicking on Android, I can always see the background of my MainActivity during navigate to different pages using NavigationActions.
I am using react-navigation v4. Should I upgrade to v5 ? is it fixed in v5 ?

**Comment by satya164** [comment]
You don't need to downgrade. You can disable `react-native-screens` instead:

```js
import { enableScreens } from 'react-native-screens'

enableScreens(false);
```

**Comment by lc3t35** [comment]
@satya164 adding "react-native-screens": "2.15.2" and disabling react-native-screens doesn't solve the problem with react-navigation v5

@mickeylam it's @react-navigation/stack that embed "react-native-screens": "~2.10.1"

**Comment by satya164** [comment]
@lc3t35 your problem is unrelated to what this is issue about

**Comment by lc3t35** [comment]
> @lc3t35 your problem is unrelated to what this is issue about

If so, prove it ! Your comment doesn't help anybody, this is not what is expected from a member.
The flickering problem on iOS is described in many issues in this repo (https://github.com/react-navigation/react-navigation/issues/9560, https://github.com/react-navigation/react-navigation/issues/9557, https://github.com/react-navigation/react-navigation/issues/9153, https://github.com/react-navigation/react-navigation/issues/9091 ...) but also in other libraries (https://github.com/software-mansion/react-native-screens/issues/905), maybe there a problem with the navigation from react-navigation, or the wrong way we use it, maybe react-native-screens, maybe react-native-safe-area-context, maybe react-native. Many issues are also closed because the github bot asked for a repro.
I provided a snack : https://snack.expo.io/@shares/screens-flicker-v5 so you can please investigate.

**Comment by satya164** [comment]
> If so, prove it ! Your comment doesn't help anybody, this is not what is expected from a member.

There's nothing you can "expect" from me, I don't work for you. I don't have to prove anything to you. This is an open source library that you use for free.

Your video clearly shows some kind of jump while this issue is about blank screen/flickering and related to `react-native-screens`. Just because it sounds similar doesn't mean it's the same thing.

**Comment by lc3t35** [comment]
For those who will land here, expecting some help, searching for an answer about their flickering problem, I applied with expo sdk41 / react-navigation v5 , `enableScreens(false)` with react-native-screens 2.15.2 and changed `useSafeAreaInsets` which has performance issues as stated by [documentation](https://github.com/th3rdwave/react-native-safe-area-context#consumers) to a standard `SafeAreaInsetsContext.Consumer` to get the `insets`value and adapt View's padding accordingly. No more jump / flickering whatever you call this problem.

**Comment by zuccha** [comment]
Just for your information, I was having the same issue with React Navigation 4.4.0 and React Native Screens 2.17.1, and solved it by upgrading Screens to 3.4.0.

**Comment by douglaslondrina** [comment]
@zuccha, upgrading to 3.4.0 isn't an option for expo users, since expo 41 locks screens at 3.0.0.
The only solution that worked for me was to disable screens.

**Comment by RyanTG** [comment]
@douglaslondrina Expo SDK 42 is out now, and it uses 3.4.0.

**Comment by douglaslondrina** [comment]
Oh, missed that, thanks for pointing it out @RyanTG

**Comment by mirik999** [comment]
Expo sdk 42.
Downgrading from 3.4.0 to 2.15.2 worked for me.

**Comment by pedrobadm7** [comment]
Thanks, downgrade version of react-native-screens to 2.15.2 worked for me

**Comment by alexnaiman** [comment]
We recently updated to `react-native-reanimated` version 2+ and the flicker started appearing. After some digging, I disabled layout animations and the flickering stopped occurring. All I did was:

```javascript
// add this in your root file
import { enableLayoutAnimations } from 'react-native-reanimated';

enableLayoutAnimations(false);
```
We had to change some of our animations but the flicker is fixed. Hope it helps 😄

**Comment by Blindmikey** [comment]
Does the flicker occur when you're not animating opacity?

**Comment by e3bmo3ty** [comment]
> You don't need to downgrade. You can disable `react-native-screens` instead:
> 
> ```js
> import { enableScreens } from 'react-native-screens'
> 
> enableScreens(false);
> ```

actually this is worked for me

**Comment by erickgtzh** [comment]
For me worked set duration to '0'

```
  const animationConfig = {
    animation: 'timing',
    config: { duration: 0 },
  };
```

```
 <Example.Screen
        name="Example"
        component={Example}
        options={{
          transitionSpec: {
            open: animationConfig,
            close: animationConfig,
          }, // added
          headerShown: false,
        }}
      />
```
