### ISSUE TITLE
Wrong height returned by useBottomTabBarHeight in iOS

### ISSUE THREAD

**Issue by maurobender** [react-navigation/react-navigation#9573]
**Current Behavior**

I'm trying to se a margin bottom to my container view in order to not overlap the absolute positioned bottom bar but in IOS the value returned by `useBottomTabBarHeight` is the double of the tab bar height. In Android it's working correctly.

This is the code:

```js
// Screen
import React from 'react';
import { View } from 'react-native';
import { useBottomTabBarHeight } from '@react-navigation/bottom-tabs';
import { SafeAreaView } from 'react-native-safe-area-context';

const styles =  StyleSheet.create( {
	container: {
		width: '100%',
		height: '100%',
		backgroundColor: 'yellow'
	},
	innerContainer: {
		position: 'relative',
		display: 'flex',
		backgroundColor: 'red'
	}
} );

const TestScreen = () => {
	const tabBarHeight = useBottomTabBarHeight();

	return (
		<SafeAreaView style={styles.container}>
			<View style={[ styles.innerContainer, { marginBottom: tabBarHeight } ]}>
				<View style={{ height: '100%' }} />
			</View>
		</SafeAreaView>
	);
};

export default TestScreen;

// Main navigator
import * as React from 'react';
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';

import TestScreen from '../screens/Test/Test';

const Tab = createBottomTabNavigator();

const ICONS_PER_ROUTE = {
	Home: 'target'
};

const MainTabNavigator = () => (
	<Tab.Navigator
		tabBarOptions={{
			activeTintColor:' red',
			inactiveTintColor: 'blue',
			style: {
				position: 'absolute',
				backgroundColor: 'white',
				borderTopLeftRadius: 24,
				borderTopRightRadius: 24,
				borderColor: 'black',
				borderWidth: 1
			}
		}}
	>
		<Tab.Screen name="Test" component={TestScreen} />
	</Tab.Navigator>
);

export default MainTabNavigator;

// App.js
import React from 'react';
import { NavigationContainer } from '@react-navigation/native';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import MainTabNavigator from './navigation/MainTabNavigator';

const App = () => (
	<SafeAreaProvider>
		<NavigationContainer>
			<MainTabNavigator />
		</NavigationContainer>
	</SafeAreaProvider>
);

export default App;
```

And here are screenshots for:

#### iOS (wrong height)
<img src="https://user-images.githubusercontent.com/450467/118091784-853c8100-b3cb-11eb-9806-5824ae2d6f59.png" width="400" />

#### Android (correct height)
<img src="https://user-images.githubusercontent.com/450467/118091853-9f765f00-b3cb-11eb-938a-cfa7eedfb274.png" width="400" />

**Expected Behavior**

`useBottomTabBarHeight` to return the correct height so I can use it as the bottom margin of my container view.

**How to reproduce**

Just create an empty react native app with a bottom tab navigator and try to use the `useBottomTabBarHeight` to set the bottom margin of the container view. The sample code in the first step should be enough to reproduce it.

A sample snack  for expo can be found here: https://snack.expo.io/@mauro-amalgama/reac-navigation---usebottomtabbarheight-issue.

**Your Environment**

| software                      | version |
| ----------------------------- | ------- |
| iOS or Android                | iOS |
| @react-navigation/native      | ^5.9.4 |
| @react-navigation/bottom-tabs | ^5.11.10 |
| react-native-screens          | ^3.1.1 |
| react-native                  | 0.64.0 |
| expo                          | - |
| node                          | v12.22.1 |
| npm or yarn                   | 1.22.10 |

**Comment by satya164** [comment]
Fixed in https://github.com/react-navigation/react-navigation/commit/c99d127a89f422f8cb691ea2f3827ee163df6d9f

**Comment by gulsher7** [comment]
hey @maurobender did you try with android as notch mode. i'm still facing this issue in adnroid with notch mode.

**Comment by Nogias9x** [comment]
I'm facing this at notch mode, too. I don't have non-notch devices to test other cases.
