### ISSUE TITLE
`Cannot read property 'key' of undefined` in `useFocusEvents`

### ISSUE THREAD

**Issue by JeffGuKang** [react-navigation/react-navigation#9624]
**Current Behavior**

I am getting error report related to react-navigation 6

`
Cannot read property 'key' of undefined
`

node_modules/@react-navigation/core/src/useFocusEvents.tsx in useFocusEvents at line 22:48

```js
      emitter,
    }: Options<State>) {
      const navigation = React.useContext(NavigationContext);
      const lastFocusedKeyRef = React.useRef<string | undefined>();
      const currentFocusedKey = state.routes[state.index].key; // error
      // When the parent screen changes its focus state, we also need to change child's focus
      // Coz the child screen can't be focused if the parent screen is out of focus
      React.useEffect(
        () =>
```

**Expected Behavior**

- What do you expect should be happening?
  
  No error. r

- Include a screenshot or video if it makes sense.

  ```node_modules/@react-navigation/core/src/useFocusEvents.tsx in useFocusEvents at line 22:48```
![image](https://user-images.githubusercontent.com/216363/119602447-27c21e80-be26-11eb-8c38-9e286a933674.png)

**How to reproduce**

I share the stacked message

```
TypeError: Cannot read property 'key' of undefined
  at useFocusEvents(node_modules/@react-navigation/core/src/useFocusEvents.tsx:22:48)
  at useNavigationBuilder(node_modules/@react-navigation/core/src/useNavigationBuilder.tsx:502:3)
  at StackNavigator(node_modules/@react-navigation/stack/src/navigators/createStackNavigator.tsx:47:46)
  at renderWithHooks(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:3353:13)
  at updateFunctionComponent(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:4179:15)
  at beginWork$1(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7189:9)
  at performUnitOfWork(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6535:14)
  at workLoopSync(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6528:37)
  at renderRootSync(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6510:7)
  at performSyncWorkOnRoot(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:6239:52)
  at runWithPriority$argument_1(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:2048:25)
  at exports.unstable_getCurrentPriorityLevel(node_modules/scheduler/cjs/scheduler.production.min.js:18:343)
  at runWithPriority(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:2025:10)
  at flushSyncCallbackQueueImpl(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:2045:7)
  at flushSyncCallbackQueue(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:2037:3)
  at batchedUpdatesImpl(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:7822:9)
  at batchedUpdates(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:999:12)
  at _receiveRootNodeIDEvent(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1030:3)
  at ReactNativePrivateInterface.RCTEventEmitter.register$argument_0.receiveTouches(node_modules/react-native/Libraries/Renderer/implementations/ReactNativeRenderer-prod.js:1102:7)
  at apply(native)
  at __callFunction(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:414:27)
  at callFunctionReturnFlushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:113:12)
  at __guard(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:365:9)
  at callFunctionReturnFlushedQueue(node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:10)
```

I just get this error from error reporting(sentry)

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 |7.0
| @react-navigation/native       |6.0.0-next.2
| react-native                   |0.64.2
| expo                           |x
| node                           |x
| npm or yarn                    |yarn

**Comment by bogas04** [comment]
Were you able to fix it @JeffGuKang?

**Comment by JeffGuKang** [comment]
@bogas04 It is fixed in latest version

**Comment by JeffGuKang** [comment]
@bogas04 I do not have the error anymore in latest version rn-navigation.

**Comment by iphonic** [comment]
@satya164 This error still occur, have received several logs in Firebase Crashlytics using @react-navigation/native 6.0.8

useFocusEvents
JavaScriptError - Cannot read property 'key' of undefined

Non-fatal Exception: JavaScriptError
0  ???                            0x0 useFocusEvents + 244029 (main.jsbundle:244029:54:244029)
1  ???                            0x0 useNavigationBuilder + 243384 (main.jsbundle:243384:33:243384)
2  ???                            0x0 StackNavigator + 784261 (main.jsbundle:784261:89:784261)
3  ???                            0x0 renderWithHooks + 33146 (main.jsbundle:33146:24:33146)
4  ???                            0x0 updateFunctionComponent + 33831 (main.jsbundle:33831:32:33831)
5  ???                            0x0 beginWork$1 + 35758 (main.jsbundle:35758:215:35758)
6  ???                            0x0 performUnitOfWork + 35408 (main.jsbundle:35408:27:35408)
7  ???                            0x0 workLoopSync + 35402 (main.jsbundle:35402:55:35402)
8  ???                            0x0 renderRootSync + 35388 (main.jsbundle:35388:19:35388)
9  ???                            0x0 performSyncWorkOnRoot + 35163 (main.jsbundle:35163:36:35163)
10 ???                            0x0 flushSyncCallbacks + 32381 (main.jsbundle:32381:33:32381)
11 ???                            0x0 batchedUpdatesImpl + 36098 (main.jsbundle:36098:214:36098)
12 ???                            0x0 batchedUpdates + 31694 (main.jsbundle:31694:32:31694)
13 ???                            0x0 _receiveRootNodeIDEvent + 31716 (main.jsbundle:31716:19:31716)
14 ???                            0x0 receiveTouches + 31755 (main.jsbundle:31755:32:31755)
15 ???                            0x0 apply ((native):0:0)
16 ???                            0x0 __callFunction + 8162 (main.jsbundle:8162:38:8162)
17 ???                            0x0 anonymous + 7969 (main.jsbundle:7969:31:7969)
18 ???                            0x0 __guard + 8095 (main.jsbundle:8095:15:8095)
19 ???                            0x0 callFunctionReturnFlushedQueue + 7968 (main.jsbundle:7968:21:7968)



What could be the solution?

Thanks.

**Comment by ibrahim-ytl** [comment]
> [@satya164](https://github.com/satya164) This error still occur, have received several logs in Firebase Crashlytics using @react-navigation/native 6.0.8
> 
> useFocusEvents JavaScriptError - Cannot read property 'key' of undefined
> 
> Non-fatal Exception: JavaScriptError 0 ??? 0x0 useFocusEvents + 244029 (main.jsbundle:244029:54:244029) 1 ??? 0x0 useNavigationBuilder + 243384 (main.jsbundle:243384:33:243384) 2 ??? 0x0 StackNavigator + 784261 (main.jsbundle:784261:89:784261) 3 ??? 0x0 renderWithHooks + 33146 (main.jsbundle:33146:24:33146) 4 ??? 0x0 updateFunctionComponent + 33831 (main.jsbundle:33831:32:33831) 5 ??? 0x0 beginWork$1 + 35758 (main.jsbundle:35758:215:35758) 6 ??? 0x0 performUnitOfWork + 35408 (main.jsbundle:35408:27:35408) 7 ??? 0x0 workLoopSync + 35402 (main.jsbundle:35402:55:35402) 8 ??? 0x0 renderRootSync + 35388 (main.jsbundle:35388:19:35388) 9 ??? 0x0 performSyncWorkOnRoot + 35163 (main.jsbundle:35163:36:35163) 10 ??? 0x0 flushSyncCallbacks + 32381 (main.jsbundle:32381:33:32381) 11 ??? 0x0 batchedUpdatesImpl + 36098 (main.jsbundle:36098:214:36098) 12 ??? 0x0 batchedUpdates + 31694 (main.jsbundle:31694:32:31694) 13 ??? 0x0 _receiveRootNodeIDEvent + 31716 (main.jsbundle:31716:19:31716) 14 ??? 0x0 receiveTouches + 31755 (main.jsbundle:31755:32:31755) 15 ??? 0x0 apply ((native):0:0) 16 ??? 0x0 __callFunction + 8162 (main.jsbundle:8162:38:8162) 17 ??? 0x0 anonymous + 7969 (main.jsbundle:7969:31:7969) 18 ??? 0x0 __guard + 8095 (main.jsbundle:8095:15:8095) 19 ??? 0x0 callFunctionReturnFlushedQueue + 7968 (main.jsbundle:7968:21:7968)
> 
> What could be the solution?
> 
> Thanks.

Facing this as well at the moment.

**Comment by ibrahim-ytl** [comment]
> [@satya164](https://github.com/satya164) This error still occur, have received several logs in Firebase Crashlytics using @react-navigation/native 6.0.8
> 
> useFocusEvents JavaScriptError - Cannot read property 'key' of undefined
> 
> Non-fatal Exception: JavaScriptError 0 ??? 0x0 useFocusEvents + 244029 (main.jsbundle:244029:54:244029) 1 ??? 0x0 useNavigationBuilder + 243384 (main.jsbundle:243384:33:243384) 2 ??? 0x0 StackNavigator + 784261 (main.jsbundle:784261:89:784261) 3 ??? 0x0 renderWithHooks + 33146 (main.jsbundle:33146:24:33146) 4 ??? 0x0 updateFunctionComponent + 33831 (main.jsbundle:33831:32:33831) 5 ??? 0x0 beginWork$1 + 35758 (main.jsbundle:35758:215:35758) 6 ??? 0x0 performUnitOfWork + 35408 (main.jsbundle:35408:27:35408) 7 ??? 0x0 workLoopSync + 35402 (main.jsbundle:35402:55:35402) 8 ??? 0x0 renderRootSync + 35388 (main.jsbundle:35388:19:35388) 9 ??? 0x0 performSyncWorkOnRoot + 35163 (main.jsbundle:35163:36:35163) 10 ??? 0x0 flushSyncCallbacks + 32381 (main.jsbundle:32381:33:32381) 11 ??? 0x0 batchedUpdatesImpl + 36098 (main.jsbundle:36098:214:36098) 12 ??? 0x0 batchedUpdates + 31694 (main.jsbundle:31694:32:31694) 13 ??? 0x0 _receiveRootNodeIDEvent + 31716 (main.jsbundle:31716:19:31716) 14 ??? 0x0 receiveTouches + 31755 (main.jsbundle:31755:32:31755) 15 ??? 0x0 apply ((native):0:0) 16 ??? 0x0 __callFunction + 8162 (main.jsbundle:8162:38:8162) 17 ??? 0x0 anonymous + 7969 (main.jsbundle:7969:31:7969) 18 ??? 0x0 __guard + 8095 (main.jsbundle:8095:15:8095) 19 ??? 0x0 callFunctionReturnFlushedQueue + 7968 (main.jsbundle:7968:21:7968)
> 
> What could be the solution?
> 
> Thanks.

@iphonic did you find the solution?
