### ISSUE TITLE
Navigating to a nested stack screen does not always work (v6)

### ISSUE THREAD

**Issue by sumnerwarren** [react-navigation/react-navigation#9698]
**Current Behavior**

Our current navigation setup is:

Drawer
 -- Bookmarks Screen
 -- Events Stack
 ---- Events Tabs
 ------ Featured Events
 ------ Bookmarked Events
 ---- Events Detail

The Bookmarks Screen allows navigation to both Bookmarked Events (view all bookmarked events) and Events Detail (view specific bookmarked event). The navigation to Events Detail does not work if the user has previously used the tab interface to switch between Featured Events and Bookmarked Events. For example, this sequence fails:

1. Open Events Stack -> land on Featured Events
2. Switch to Bookmarked Events via bottom tab bar
3. Open Bookmarks Screen via drawer (unmounts Events Stack)
4. Open Events Detail via button on Bookmarks Screen
5. Observe landing on Featured Events instead of Events Detail

This sequence also fails:

1. Open Bookmarks Screen
2. Open Bookmarked Events via button on Bookmarks Screen
3. Switch to Featured Events via bottom tab bar
4. Open Bookmarked Screen via drawer
5. Open Events Detail via button on Bookmarks Screen
6. Observe landing on Bookmarked Events instead of Events Detail

If you omit step 2 from the first sequence or step 3 from the second sequence, the user correctly lands on Events Detail.

**Expected Behavior**

Both of these sequences should result in the user landing on Events Detail with the provided id parameter.

**How to reproduce**

See this snack for a minimal example of this issue: https://snack.expo.io/6KexDtiPb

1. Click "Go to event bookmarks"
2. Switch to Featured tab
3. Open "Links" via drawer
4. Click "Go to event detail"
5. Observe landing on "Bookmarks" tab

**Notes**
I initially thought this might be related to #6915 as it only happens when `unmountOnBlur = true`, but I tried the suggested workaround to no success. There are `screen` and `params` being provided when navigating to Events Detail that (as of v6) should overwrite the previously stored params, but this does not appear to happen. I was able to determine that the state of the `EventsStack` appears to be rehydrating instead of being created anew, so I suspect this has something to do with not properly clearing the Drawer router's state when the child Stack unmounts. Because the partial state being rehydrated is not stale, the new params are essentially ignored as best I can tell.

**Your Environment**

| software                       | version |
| ------------------------------ | ------- |
| iOS or Android                 | both |
| @react-navigation/native       | 6.0.0-next.13 |
| @react-navigation/drawer       | 6.0.0-next.17 |
| @react-navigation/bottom-tabs       | 6.0.0-next.18 |
| @react-navigation/stack       | 6.0.0-next.25 |
| react-native-reanimated        | 2.1.0 |
| react-native-gesture-handler   | 1.10.3 |
| react-native-safe-area-context | 3.2.0 |
| react-native-screens           | 3.0.0 |
| react-native                   | 0.63.2 |
| expo                           | SDK 41 |
| node                           | 14.17.0 |
| npm or yarn                    | yarn |

**Comment by sumnerwarren** [comment]
This issue also exists on the latest v5 versions.

**Comment by ajsmth** [comment]
Hi there - I was able to fix the example provided with the following configuration: 
```
      <Drawer.Navigator
        backBehavior="history"
        screenOptions={{ unmountOnBlur: false, lazy: true }}
      >
        <Drawer.Screen name="Links" component={Links} />
        <Drawer.Screen name="Events" component={Events} />
      </Drawer.Navigator>
```

Let me know if that fixes the issue for you - I know you mentioned something about `unmountOnBlur` but it wasn't clear

**Comment by sumnerwarren** [comment]
@ajsmth Yes, using `unmountOnBlur: false` does fix the issue (I've made my original description more clear). But we would like to use `unmountOnBlue: true`. I believe that option does not behave as expected.

**Comment by ajsmth** [comment]
Thanks for clarifying - I think you might be on the right track on this. To me the strangest behaviour is that switching tabs seems related to this issue - I was able to get the expected navigation state by removing the `screen` param and setting Bookmarks as the initial route, but this didn't seem to make any difference, I suspect its not resolving this state properly  @satya164 any ideas on where to start looking for this?

**Comment by sumnerwarren** [comment]
It looks like this was fixed by #9688, which I suspect would also resolve #9739 if backported to v5.

**Comment by chrisparton1991** [comment]
Thanks for mentioning my issue (#9739) @sumnerwarren, unfortunately the issue is still present in v6.0.0, I've updated the Snack in my issue to use v6.
